import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createCampaignAI,createLocalCampaignAI} from './ai-runtime.mjs';
import {openDirectorRecoveryStore} from './director-recovery-store.mjs';
import {createEngineClient,CONTRACT} from './engine-client.mjs';
async function waitFor(condition,label='observable director result'){const deadline=Date.now()+3000;while(!await condition()){assert(Date.now()<deadline,`Timed out waiting for ${label}`);await new Promise(resolve=>setTimeout(resolve,5));}}
const directorStatus=(f,status)=>()=>f.ai.status().lastDirector?.status===status;
const directorResolution=(input,revision,kind='cancelled')=>({contract:CONTRACT,campaignId:'fixture',commandId:input.commandId,ownerId:input.targetOwnerId,actorId:input.actorId,originalExpectedRevision:input.expectedRevision,revision,success:true,replayed:kind==='committed',resolution:kind,...(kind==='committed'?{receipt:{contract:CONTRACT,campaignId:'fixture',commandId:input.commandId,revision,success:true,replayed:true,result:{message:'Original ruling'}}}:{rejection:{contract:CONTRACT,campaignId:'fixture',commandId:input.commandId,ownerId:input.targetOwnerId,actorId:input.actorId,originalExpectedRevision:input.expectedRevision,revision,code:'COMMAND_CANCELLED',terminal:true}})});
const takeover=f=>{f.view.directorMode='human_gm';f.view.aiDirectorId='';f.view.decisionOpen=false;f.view.authorityEpoch++;};
test('human takeover explicitly resolves the durable director envelope without new inference',async()=>{const f=await fixture({unresolved:true});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));const saved=structuredClone(f.commands[0]);assert.equal((await f.ai.getDirectorRecovery({userId:'gm'})).ready,false);await assert.rejects(f.ai.resolveDirectorRecovery({userId:'gm',commandId:saved.commandId}));takeover(f);const info=await f.ai.getDirectorRecovery({userId:'gm'});assert.equal(info.ready,true);assert.equal(info.commandId,saved.commandId);assert(!JSON.stringify(info).includes(saved.payload.text));const value=await f.ai.resolveDirectorRecovery({userId:'gm',commandId:saved.commandId});assert.equal(value.resolution,'cancelled');assert.deepEqual(f.resolutions,[{ownerId:'gm',targetOwnerId:saved.ownerId,actorId:saved.actorId,commandId:saved.commandId,expectedRevision:saved.expectedRevision}]);assert.equal((await openDirectorRecoveryStore({file:join(f.directory,'recovery','fixture.sqlite'),campaignId:'fixture'})).get(),null);await f.notify();assert.equal(f.requests.length,1);assert.equal(f.commands.length,1);}finally{await f.close();}});
test('explicit director recovery denies wrong user and mismatched ID without clearing',async()=>{const f=await fixture({unresolved:true});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));takeover(f);await assert.rejects(f.ai.getDirectorRecovery({userId:'player'}));await assert.rejects(f.ai.resolveDirectorRecovery({userId:'player',commandId:f.commands[0].commandId}));await assert.rejects(f.ai.resolveDirectorRecovery({userId:'gm',commandId:'other'}));assert.equal(f.resolutions.length,0);f.revoke();await assert.rejects(f.ai.resolveDirectorRecovery({userId:'gm',commandId:f.commands[0].commandId}));assert.equal((await openDirectorRecoveryStore({file:join(f.directory,'recovery','fixture.sqlite'),campaignId:'fixture'})).get().commandId,f.commands[0].commandId);}finally{await f.close();}});
test('ambiguous and malformed explicit proofs retain director journal',async()=>{for(const failure of ['network','owner','revision','terminal']){const f=await fixture({unresolved:true,resolveCommand:async(input,view)=>{if(failure==='network')throw Error('lost');const value=directorResolution(input,view.revision+1);if(failure==='owner')value.ownerId='other';if(failure==='revision')value.rejection.originalExpectedRevision++;if(failure==='terminal')value.rejection.terminal=false;return value;}});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));takeover(f);await assert.rejects(f.ai.resolveDirectorRecovery({userId:'gm',commandId:f.commands[0].commandId}));assert.equal((await openDirectorRecoveryStore({file:join(f.directory,'recovery','fixture.sqlite'),campaignId:'fixture'})).get().commandId,f.commands[0].commandId);await f.notify();assert.equal(f.commands.length,1);assert.equal(f.resolutions.length,1);}finally{await f.close();}}});
test('explicit director resolution serializes and rechecks closure before durable clear',async()=>{let finish,entered=false;const held=new Promise(resolve=>finish=resolve);const f=await fixture({unresolved:true,resolveCommand:async(input,view)=>{entered=true;await held;return directorResolution(input,view.revision+1);}});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));takeover(f);const pending=f.ai.resolveDirectorRecovery({userId:'gm',commandId:f.commands[0].commandId});const rejected=assert.rejects(pending);await waitFor(()=>entered);const closing=f.ai.close();finish();await rejected;await closing;assert.equal((await openDirectorRecoveryStore({file:join(f.directory,'recovery','fixture.sqlite'),campaignId:'fixture'})).get().commandId,f.commands[0].commandId);}finally{finish();await f.close();}});
test('explicit committed director proof clears once and duplicate controls never redispatch',async()=>{let finish,entered=false;const held=new Promise(resolve=>finish=resolve);const f=await fixture({unresolved:true,resolveCommand:async input=>{entered=true;await held;return directorResolution(input,input.expectedRevision+1,'committed');}});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));takeover(f);const args={userId:'gm',commandId:f.commands[0].commandId},first=f.ai.resolveDirectorRecovery(args);await waitFor(()=>entered);const second=assert.rejects(f.ai.resolveDirectorRecovery(args));finish();assert.equal((await first).resolution,'committed');await second;assert.equal(f.resolutions.length,1);assert.equal((await f.ai.getDirectorRecovery({userId:'gm'})).status,'empty');assert.equal(f.commands.length,1);}finally{finish();await f.close();}});
test('explicit recovery waits for an in-flight dispatch before resolving the stored identity',async()=>{let release,entered=false;const gate=new Promise(resolve=>release=resolve);const f=await fixture({unresolved:true,beforeCommand:async()=>{entered=true;await gate;}});try{await f.emit();await waitFor(()=>entered);takeover(f);const saved=(await openDirectorRecoveryStore({file:join(f.directory,'recovery','fixture.sqlite'),campaignId:'fixture'})).get();const work=f.ai.resolveDirectorRecovery({userId:'gm',commandId:saved.commandId});await new Promise(resolve=>setTimeout(resolve,10));assert.equal(f.resolutions.length,0);release();assert.equal((await work).resolution,'cancelled');assert.equal(f.commands.length,1);assert.equal(f.resolutions.length,1);}finally{release();await f.close();}});
test('explicit clear failure keeps the original director journal available',async()=>{const directory=await mkdtemp(join(tmpdir(),'director-explicit-clear-'));const store=await openDirectorRecoveryStore({file:join(directory,'recovery','fixture.sqlite'),campaignId:'fixture'});const f=await fixture({directory,unresolved:true,directorStore:{get:store.get,save:store.save,clear:async()=>{throw Error('disk locked');}}});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));takeover(f);await assert.rejects(f.ai.resolveDirectorRecovery({userId:'gm',commandId:f.commands[0].commandId}),/disk locked/);assert.equal(store.get().commandId,f.commands[0].commandId);assert.equal((await f.ai.getDirectorRecovery({userId:'gm'})).status,'pending');await f.notify();assert.equal(f.commands.length,1);}finally{await f.close();}});
const result=()=>({text:JSON.stringify({approved:true,text:'You hear the rain outside. No mechanical effects are applied.'}),sources:[],trace:[{destination:'local'}]});

test('production narrative can survive unrelated revisions only with identical private context and ownership',async()=>{
 for(const change of ['unrelated','scene','owner','pause','held']){
  let release,settled=false;const inference=new Promise(resolve=>{release=resolve;});
  const f=await fixture({runtimeOptions:{productionMode:true,companionsEnabled:false},generate:async()=>{try{return await inference;}finally{settled=true;}}});
  try{
   Object.assign(f.view,{productionVersion:1,runRequested:true,characters:[{characterId:'lantern-fighter',ownerId:'human',sceneId:'briefing'}]});
   let held=false;f.engine.recovery=async()=>({held});await f.emit();await waitFor(()=>f.requests.length===1);
   f.view.revision++;
   if(change==='scene')f.view.currentSceneId='harbor-shop';
   if(change==='owner')f.view.characters[0].ownerId='different';
   if(change==='pause')f.view.runRequested=false;
   if(change==='held')held=true;
   release(result());await waitFor(()=>settled);
   if(change==='unrelated'){await waitFor(directorStatus(f,'committed'));assert.equal(f.commands[0].expectedRevision,5);assert.equal(f.requests.length,1);}
   else{await new Promise(resolve=>setTimeout(resolve,40));assert.equal(f.commands.length,0);}
  }finally{release(result());await f.close();}
 }
});

test('production never starts inference while paused by a human or held for recovery',async()=>{
 for(const paused of [true,false]){
  const f=await fixture({runtimeOptions:{productionMode:true,companionsEnabled:false}});
  try{Object.assign(f.view,{productionVersion:1,runRequested:!paused});f.engine.recovery=async()=>({held:!paused});await f.emit();await new Promise(resolve=>setTimeout(resolve,40));assert.equal(f.requests.length,0);assert.equal(f.commands.length,0);}finally{await f.close();}
 }
});

test('a production human pause aborts active inference as soon as the committed event is observed',async()=>{
 let aborted=false;
 const f=await fixture({runtimeOptions:{productionMode:true,companionsEnabled:false},generate:input=>new Promise((resolve,reject)=>{input.signal.addEventListener('abort',()=>{aborted=true;reject(Error('aborted'));},{once:true});})});
 try{
  Object.assign(f.view,{productionVersion:1,runRequested:true,characters:[{characterId:'lantern-fighter',ownerId:'human',sceneId:'briefing'}]});f.engine.recovery=async()=>({held:false});
  await f.emit();await waitFor(()=>f.requests.length===1);f.view.runRequested=false;f.view.decisionOpen=false;f.view.authorityEpoch++;await f.notify();await waitFor(()=>aborted);assert.equal(f.commands.length,0);
 }finally{await f.close();}
});
async function fixture({mode='ai_dm',generate=result,ambiguous=false,unresolved=false,pendingCount=1,onRefresh=()=>{},directory:providedDirectory,directorStore,recoveredCommand,beforeCommand=()=>{},recoveryFile,omitRecovery=false,runtimeOptions={},resolveCommand}={}){
 const directory=providedDirectory??await mkdtemp(join(tmpdir(),'director-runtime-')),requests=[],commands=[],recoveries=[],leases=new Map();let observer,member=true;
 const view={campaignId:'fixture',revision:4,currentSceneId:'briefing',directorMode:mode,authorityEpoch:1,aiDirectorId:'ai-director:fixture',decisionOpen:true,characters:[],pendingActions:[],rollPending:false};
 const empty=()=>({bootEpoch:'11111111-1111-4111-8111-111111111111',generation:null,sessionPolicyRevision:0,leaseExpiresAtMs:null});
 const control={getRuntime:async({session})=>leases.get(session)??empty(),register:async x=>{const s={...empty(),generation:x.generation,leaseExpiresAtMs:Date.now()+30000};leases.set(x.session,s);return s;},configure:async x=>{const s={...leases.get(x.session),sessionPolicyRevision:1};leases.set(x.session,s);return s;},renew:async x=>leases.get(x.session),revoke:async()=>{},release:async()=>{}};
 const receipts=new Map();
 const confirm=command=>{view.revision++;view.pendingActions=view.pendingActions.filter(p=>p.id!==command.payload.pendingId);const receipt={success:true,commandId:command.commandId,revision:view.revision,replayed:false};receipts.set(command.commandId,receipt);return receipt;};
 if(recoveredCommand)confirm(recoveredCommand);
 const engine={project:async({audience,actorId})=>audience==='gm'?{...structuredClone(view),audience,gmNotes:'DO NOT SEND GM NOTES'}:{campaignId:view.campaignId,audience,revision:view.revision,currentSceneId:view.currentSceneId,...(audience==='private'?{characterId:actorId}:{}),directorMode:view.directorMode,authorityEpoch:view.authorityEpoch},command:async command=>{await beforeCommand(command);commands.push(structuredClone(command));const receipt=unresolved?null:confirm(command);if(ambiguous||unresolved)throw Object.assign(new Error('lost response'),{code:'ENGINE_UNAVAILABLE'});return receipt;},receipt:async input=>{recoveries.push(structuredClone(input));const receipt=receipts.get(input.commandId);if(receipt)return {...receipt,replayed:true};throw Object.assign(new Error('not found'),{code:'RECEIPT_NOT_FOUND',status:404});}};
 const resolutions=[];
 engine.resolveUncertain=async input=>{resolutions.push(structuredClone(input));if(resolveCommand)return resolveCommand(input,view);view.revision++;return directorResolution(input,view.revision);};
 const host={engine,authorize:async()=>member,onCommitted:fn=>{observer=fn;return()=>{};},refreshPublic:async()=>{onRefresh(view);return true;}};
 const ai=await createCampaignAI({host,campaignId:'fixture',gmUserId:'gm',baseUrl:'http://127.0.0.1:38175',serviceToken:'a'.repeat(64),hostControlToken:'b'.repeat(64),artDirectory:join(directory,'art'),directorRecoveryFile:omitRecovery?undefined:recoveryFile??join(directory,'recovery','fixture.sqlite'),directorStore,control,transport:{generate:async input=>{requests.push(input);return generate(input);},runtime:async()=>({contract:'raph-obus-game-runtime-v1',...empty()})},partyFactory:()=>({start(){},close(){},getPrivateIntents:()=>[],onDecisionOpened:async()=>({status:'complete',committed:[]})}),imageFactory:()=>({request:async()=>({status:'retained'})}),...runtimeOptions});
 const notify=async()=>{await observer({scope:{campaignId:'fixture',userId:'player',actorId:'lantern-fighter',audience:'private',action:'describe'},receipt:{success:true,revision:view.revision,commandId:'intent-4',replayed:false}});};
 return {ai,directory,view,requests,commands,recoveries,resolutions,engine,confirm:()=>{unresolved=false;return confirm(commands[0]);},notify,revoke:()=>{member=false;},emit:async()=>{view.pendingActions=Array.from({length:pendingCount},(_,i)=>({id:`intent-${4+i}`,kind:'describe',actorId:'lantern-fighter',text:'I listen at the door.'}));await notify();},close:async({keep=false}={})=>{await ai.close();if(!keep)await rm(directory,{recursive:true,force:true});}};
}
test('persisted AI mode runs a private narrative ruling through the delegated engine principal',async()=>{const f=await fixture();try{await f.emit();await waitFor(directorStatus(f,'committed'));assert.equal(f.requests.length,1);assert.equal(f.commands.length,1);assert.equal(f.commands[0].ownerId,'ai-director:fixture');assert.equal(f.commands[0].authorityEpoch,1);assert.equal(f.commands[0].expectedRevision,4);assert.equal(f.commands[0].type,'gm_resolve');assert.equal(f.commands[0].payload.pendingId,'intent-4');assert.deepEqual(f.requests[0].policy,{enabled:true,mode:'local',exportable:false,codex:false});assert(!JSON.stringify(f.requests[0].evidence).includes('DO NOT SEND GM NOTES'));assert.equal(f.requests[0].scope.role,'host');assert(!Object.hasOwn(f.requests[0].evidence,'question'));assert(!Object.hasOwn(f.requests[0].evidence,'contract'));}finally{await f.close();}});
test('human GM mode does not invoke a director model',async()=>{const f=await fixture({mode:'human_gm'});try{await f.emit();await f.ai.close();assert.equal(f.requests.length,0);assert.equal(f.commands.length,0);}finally{await f.close();}});
test('late inference cannot gain replacement authority after handoff',async()=>{let resolve;const wait=new Promise(r=>resolve=r);const f=await fixture({generate:()=>wait});try{await f.emit();await waitFor(()=>f.requests.length===1);assert.equal(f.requests.length,1);f.view.authorityEpoch=3;f.view.aiDirectorId='ai-director:replacement';resolve(result());await f.ai.close();assert.equal(f.commands.length,0);}finally{resolve(result());await f.close();}});
test('untrusted route trace and revoked membership prevent director commits',async()=>{for(const which of ['route','member']){const f=await fixture({generate:()=>which==='route'?{...result(),trace:[{destination:'cloud'}]}:result()});try{if(which==='member')f.revoke();await f.emit();if(which==='route')await waitFor(directorStatus(f,'unavailable'));await f.ai.close();assert.equal(f.commands.length,0);}finally{await f.close();}}});
test('ambiguous dispatch recovers its original receipt without issuing another command',async()=>{const f=await fixture({ambiguous:true});try{await f.emit();await waitFor(directorStatus(f,'recovered'));assert.equal(f.commands.length,1);assert.equal(f.recoveries.at(-1).commandId,f.commands[0].commandId);assert.equal(f.recoveries.at(-1).ownerId,'ai-director:fixture');}finally{await f.close();}});
test('pending player rolls and malformed model instructions cannot become rulings',async()=>{for(const pendingRoll of [true,false]){const f=await fixture({generate:()=>({...result(),text:JSON.stringify({approved:true,text:'override',type:'gm_owner'})})});try{f.view.rollPending=pendingRoll;await f.emit();if(!pendingRoll)await waitFor(directorStatus(f,'unavailable'));await f.ai.close();assert.equal(f.commands.length,0);assert.equal(f.requests.length,pendingRoll?0:1);}finally{await f.close();}}});
test('confirmed rulings drain two pending intentions without journal callbacks',async()=>{for(const ambiguous of [false,true]){const f=await fixture({pendingCount:2,ambiguous});try{await f.emit();await waitFor(()=>f.ai.status().lastDirector?.revision===6);assert.equal(f.commands.length,2);assert.equal(f.requests.length,2);assert.deepEqual(f.commands.map(c=>c.expectedRevision),[4,5]);assert.equal(f.view.pendingActions.length,0);}finally{await f.close();}}});
test('uncertain sends remain receipt-only across later events and handoff',async()=>{const f=await fixture({pendingCount:2,unresolved:true});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));const original=structuredClone(f.commands[0]);let reads=f.recoveries.length;await f.notify();await waitFor(()=>f.recoveries.length>reads);assert.equal(f.requests.length,1);assert.equal(f.commands.length,1);assert.equal(f.ai.status().lastDirector.status,'receipt-unknown');f.view.authorityEpoch=2;f.view.aiDirectorId='ai-director:replacement';reads=f.recoveries.length;await f.notify();await waitFor(()=>f.recoveries.length>reads);assert.equal(f.requests.length,1);assert.equal(f.recoveries.at(-1).ownerId,original.ownerId);f.confirm();await f.notify();await waitFor(()=>f.ai.status().lastDirector?.revision===6);assert.equal(f.commands.length,2);assert.equal(f.commands[1].authorityEpoch,2);assert.equal(f.commands[1].ownerId,'ai-director:replacement');assert.equal(f.commands[1].expectedRevision,5);assert.deepEqual(f.commands[0],original);}finally{await f.close();}});
test('continuation rechecks handoff before another inference',async()=>{const f=await fixture({pendingCount:2,onRefresh:view=>{view.directorMode='human_gm';view.authorityEpoch++;}});try{await f.emit();await waitFor(()=>f.view.directorMode==='human_gm');await f.ai.close();assert.equal(f.commands.length,1);assert.equal(f.requests.length,1);assert.equal(f.view.pendingActions.length,1);}finally{await f.close();}});
test('automatic director continuation is bounded to three rulings per event',async()=>{const f=await fixture({pendingCount:5});try{await f.emit();await waitFor(()=>f.ai.status().lastDirector?.revision===7);assert.equal(f.commands.length,3);assert.equal(f.view.pendingActions.length,2);await f.notify();await waitFor(()=>f.ai.status().lastDirector?.revision===9);assert.equal(f.commands.length,5);}finally{await f.close();}});
test('journal is durable before dispatch and restart missing receipts remain receipt-only',async()=>{let file;const first=await fixture({unresolved:true,beforeCommand:async command=>{assert.deepEqual((await openDirectorRecoveryStore({file,campaignId:'fixture'})).get(),command);}});file=join(first.directory,'recovery','fixture.sqlite');await first.emit();await waitFor(directorStatus(first,'receipt-unknown'));const original=structuredClone(first.commands[0]);assert(original);await first.close({keep:true});const restarted=await fixture({directory:first.directory,mode:'human_gm'});try{await waitFor(directorStatus(restarted,'receipt-unknown'));const reads=restarted.recoveries.length;await restarted.notify();await waitFor(()=>restarted.recoveries.length>reads);assert.equal(restarted.requests.length,0);assert.equal(restarted.commands.length,0);assert.equal(restarted.recoveries.at(-1).ownerId,original.ownerId);assert.deepEqual((await openDirectorRecoveryStore({file,campaignId:'fixture'})).get(),original);}finally{await restarted.close();}});
test('restart confirms a lost response using the saved principal after handoff',async()=>{const first=await fixture({unresolved:true});await first.emit();await waitFor(directorStatus(first,'receipt-unknown'));const original=structuredClone(first.commands[0]);await first.close({keep:true});const restarted=await fixture({directory:first.directory,mode:'human_gm',recoveredCommand:original});try{await waitFor(directorStatus(restarted,'recovered'));assert.equal(restarted.requests.length,0);assert.equal(restarted.commands.length,0);assert.equal(restarted.recoveries[0].ownerId,original.ownerId);assert.equal((await openDirectorRecoveryStore({file:join(first.directory,'recovery','fixture.sqlite'),campaignId:'fixture'})).get(),null);}finally{await restarted.close();}});
test('journal write failure prevents engine dispatch',async()=>{const f=await fixture({directorStore:{get:()=>null,save:async()=>{throw Error('disk full');},clear:async()=>{throw Error('must not clear');}}});try{await f.emit();await waitFor(directorStatus(f,'receipt-unknown'));assert.equal(f.requests.length,1);assert.equal(f.commands.length,0);const reads=f.recoveries.length;await f.notify();await waitFor(()=>f.recoveries.length>reads);await f.ai.close();assert.equal(f.requests.length,1);assert.equal(f.commands.length,0);}finally{await f.close();}});
test('failed journal clear remains recoverable after restart',async()=>{const directory=await mkdtemp(join(tmpdir(),'director-clear-')),file=join(directory,'recovery','fixture.sqlite');const store=await openDirectorRecoveryStore({file,campaignId:'fixture'});const first=await fixture({directory,directorStore:{get:store.get,save:store.save,clear:async()=>{throw Error('disk locked');}}});await first.emit();await waitFor(directorStatus(first,'receipt-unknown'));const original=structuredClone(first.commands[0]);assert.deepEqual(store.get(),original);await first.close({keep:true});const restarted=await fixture({directory,mode:'human_gm',recoveredCommand:original});try{await waitFor(directorStatus(restarted,'recovered'));assert.equal(restarted.requests.length,0);assert.equal((await openDirectorRecoveryStore({file,campaignId:'fixture'})).get(),null);}finally{await restarted.close();}});
test('director without a configured recovery file fails closed before inference',async()=>{const f=await fixture({omitRecovery:true});try{await f.emit();await waitFor(directorStatus(f,'recovery-configuration-required'));assert.equal(f.requests.length,0);assert.equal(f.commands.length,0);assert.equal(f.ai.status().lastDirector.status,'recovery-configuration-required');}finally{await f.close();}});
test('runtime rejects corrupt journals and journals within generated art',async()=>{const directory=await mkdtemp(join(tmpdir(),'director-placement-'));try{await assert.rejects(fixture({directory,recoveryFile:join(directory,'art','journal.sqlite')}),/outside public and art/);await mkdir(join(directory,'recovery'),{recursive:true});await writeFile(join(directory,'recovery','fixture.sqlite'),'corrupt');await assert.rejects(fixture({directory}));}finally{await rm(directory,{recursive:true,force:true});}});
test('production recovery placement rejects approved-art containment before credential reads',async()=>{const directory=await mkdtemp(join(tmpdir(),'director-production-'));try{await assert.rejects(createLocalCampaignAI({host:{},config:{campaignId:'fixture'},env:{RAPHAEL_OBUS_TOKEN_FILE:join(directory,'absent-service'),RAPHAEL_OBUS_HOST_CONTROL_TOKEN_FILE:join(directory,'absent-host'),HOLLOW_LANTERN_ART_ROOT:fileURLToPath(new URL('../../private-data/',import.meta.url)),HOLLOW_LANTERN_GENERATED_ART_DIR:join(directory,'art')}}),/outside public and art/);}finally{await rm(directory,{recursive:true,force:true});}});
test('text-only director accepts a human roster and retains private scene-art fencing',async()=>{const directory=await mkdtemp(join(tmpdir(),'director-text-only-')),artRequests=[];let visionCalls=0,browserCalls=0;let f;try{f=await fixture({directory,runtimeOptions:{companionsEnabled:false,partyFactory:undefined,visionTransport:{available:async()=>{visionCalls++;throw Error('vision unavailable');}},browserFactory:()=>{browserCalls++;throw Error('no companion browser');},imageFactory:()=>({request:async input=>{artRequests.push(input);return {status:'retained'};}})}});f.view.characters=[{characterId:'human-bard',ownerId:'player'}];f.view.pendingActions=[{id:'human-intent',actorId:'human-bard',kind:'describe',text:'I listen at the door.'}];await f.notify();await waitFor(directorStatus(f,'committed'));assert.equal(f.commands[0].payload.pendingId,'human-intent');assert.equal(f.commands[0].ownerId,'ai-director:fixture');assert.equal(f.requests.length,1);assert.equal(visionCalls,0);assert.equal(browserCalls,0);assert.deepEqual(f.ai.privateIntents(),[]);assert.equal(f.ai.status().companionsEnabled,false);await waitFor(async()=>{await f.ai.requestSceneArt();return artRequests.length===1;},'scene art request after director completion');assert.equal(artRequests[0].scope.owner,'gm');assert.equal(artRequests[0].scope.audience,'public');assert.equal(artRequests[0].scope.characterId,'');assert.equal(artRequests[0].scope.revision,5);assert.equal(artRequests[0].runtime.contract,'raph-obus-game-runtime-v1');f.revoke();await assert.rejects(f.ai.requestSceneArt(),/membership/);}finally{if(f)await f.close();else await rm(directory,{recursive:true,force:true});}});
test('companions setting requires explicit booleans',async()=>{const directory=await mkdtemp(join(tmpdir(),'director-setting-'));try{await assert.rejects(fixture({directory,runtimeOptions:{companionsEnabled:'false'}}),/companionsEnabled must be a boolean/);for(const value of ['0','FALSE','',false])await assert.rejects(createLocalCampaignAI({host:{},config:{campaignId:'fixture'},env:{HOLLOW_LANTERN_AI_COMPANIONS_ENABLED:value}}),/HOLLOW_LANTERN_AI_COMPANIONS_ENABLED must be true or false/);}finally{await rm(directory,{recursive:true,force:true});}});
test('engine wire preserves explicit epoch and omits it from legacy requests',async()=>{const sent=[];const client=createEngineClient({campaignId:'fixture',channelId:'channel',secret:'x'.repeat(32),fetchImpl:async(_url,options)=>{const b=JSON.parse(options.body);sent.push(b);return new Response(JSON.stringify({contract:CONTRACT,campaignId:'fixture',commandId:b.commandId,revision:1,success:true}),{headers:{'content-type':'application/json'}});}});const command={ownerId:'gm',commandId:'legacy',expectedRevision:0,type:'checkpoint'};await client.command(command);await client.command({...command,ownerId:'ai-director:fixture',commandId:'delegated',authorityEpoch:2});assert(!Object.hasOwn(sent[0],'authorityEpoch'));assert.equal(sent[1].authorityEpoch,2);await assert.rejects(client.command({...command,authorityEpoch:-1}));assert.equal(sent.length,2);});


test('split-party director uses only the acting character context and whitelisted continuity',async()=>{
 const f=await fixture();try{
  const project=f.engine.project,scopes=[];
  f.view.characters=[{characterId:'lantern-fighter',sceneId:'harbor-shop'},{characterId:'other-player',sceneId:'signal-dungeon',secret:'OTHER PARTY SECRET'}];
  f.engine.project=async scope=>{scopes.push(scope);if(scope.audience!=='private')return project(scope);return {campaignId:'fixture',revision:4,audience:'private',characterId:'lantern-fighter',currentSceneId:'harbor-shop',gmNotes:'GM SECRET',characters:[{characterId:'lantern-fighter',displayName:'Mara',sceneId:'harbor-shop',privateBackstory:'SECRET BACKSTORY'}],discoveries:['harbor-sign'],travelOptions:[{destinationId:'coastal-road',minutes:10,hiddenRoute:'SECRET ROUTE'}],npcs:[{characterId:'mira',name:'Mira Voss',role:'shopkeeper',relationships:{other:'SECRET RELATION'},memories:[{text:'Mira promised rope.',revision:3,gmNotes:'SECRET MEMORY'}]}],continuity:{version:1,prepared:true,preparedRevision:2,sceneId:'harbor-shop',strategies:[{kind:'bargain',approach:'Ask about rope',gmNotes:'SECRET STRATEGY'}],recentDecisions:[{revision:3,sceneId:'harbor-shop',kind:'talk',intention:'Ask directions',response:'Road leads east',approved:true,ownerId:'SECRET OWNER'}],groups:['SECRET GROUP']}};};
  await f.emit();await waitFor(directorStatus(f,'committed'));
  assert(scopes.some(s=>s.ownerId==='gm'&&s.actorId==='lantern-fighter'&&s.audience==='private'&&s.mapLevel==='regional'));
  const e=f.requests[0].evidence;assert.equal(e.scene.id,'harbor-shop');assert.equal(e.npcs[0].memories[0].text,'Mira promised rope.');assert.equal(e.knownRoutes[0].destinationId,'coastal-road');assert.equal(e.continuity.recentDecisions[0].response,'Road leads east');assert(!JSON.stringify(e).includes('SECRET'));assert(!JSON.stringify(e).includes('other-player'));
 }finally{await f.close();}
});

test('director refuses mismatched private character, campaign, revision, audience or acting scene',async()=>{
 for(const change of [{characterId:'other'},{campaignId:'other'},{revision:3},{audience:'gm'},{currentSceneId:'other'}]){
  const f=await fixture();try{f.view.characters=[{characterId:'lantern-fighter',sceneId:'briefing'}];const project=f.engine.project;f.engine.project=async scope=>({...await project(scope),...(scope.audience==='private'?change:{})});await f.emit();await waitFor(directorStatus(f,'unavailable'));assert.equal(f.requests.length,0);assert.equal(f.commands.length,0);}finally{await f.close();}
 }
});

test('NPC dialogue is eligible but its reply cannot exceed 700 characters',async()=>{
 for(const length of [700,701]){const f=await fixture({generate:()=>({...result(),text:JSON.stringify({approved:true,text:'x'.repeat(length)})})});try{const project=f.engine.project;f.engine.project=async scope=>({...await project(scope),...(scope.audience==='private'?{npcs:[{characterId:'mira',name:'Mira',role:'shopkeeper',memories:[]}]}:{})});f.view.pendingActions=[{id:'npc-intent',actorId:'lantern-fighter',targetId:'mira',kind:'npc-conversation',text:'Can we barter?'}];await f.notify();await waitFor(directorStatus(f,length===700?'committed':'unavailable'));assert.equal(f.commands.length,length===700?1:0);assert.equal(f.requests[0].evidence.intention.targetId,'mira');}finally{await f.close();}}
});

test('pending actor, target or scene changes invalidate an in-flight director ruling before persistence',async()=>{
 for(const key of ['actorId','targetId','sceneId']){
  let finish,saves=0,checked=false,changed=false;
  const held=new Promise(resolve=>finish=resolve),f=await fixture({generate:()=>held,directorStore:{get:()=>null,save:async()=>{saves++;},clear:async()=>{}}});
  try{const project=f.engine.project;f.engine.project=async scope=>{const p=await project(scope);if(changed&&scope.audience==='gm')checked=true;return p;};await f.emit();await waitFor(()=>f.requests.length===1);f.view.pendingActions[0][key]='replacement';changed=true;finish(result());await waitFor(()=>checked);await new Promise(resolve=>setImmediate(resolve));assert.equal(saves,0);assert.equal(f.commands.length,0);}finally{finish(result());await f.close();}
 }
});

test('a pending intention from a previous scene is held before inference',async()=>{
 const f=await fixture();try{f.view.pendingActions=[{id:'old-scene',actorId:'lantern-fighter',sceneId:'harbor-shop',kind:'describe',text:'I inspect the shop.'}];await f.notify();await waitFor(directorStatus(f,'unavailable'));assert.equal(f.requests.length,0);assert.equal(f.commands.length,0);}finally{await f.close();}
});

test('director evidence bounds actor-visible memory and ignores mismatched continuity',async()=>{
 const f=await fixture();try{const project=f.engine.project;f.engine.project=async scope=>({...await project(scope),...(scope.audience==='private'?{npcs:Array.from({length:200},(_,i)=>({characterId:'npc-'+i,memories:Array.from({length:500},()=>({text:'x'.repeat(1500)}))})),continuity:{version:1,sceneId:'different',recentDecisions:[{response:'PRIVATE OTHER SCENE'}]}}:{})});await f.emit();await waitFor(directorStatus(f,'committed'));const e=f.requests[0].evidence;assert.equal(e.npcs.length,8);assert.equal(e.npcs[0].memories.length,3);assert.equal(e.npcs[0].memories[0].text.length,500);assert(!Object.hasOwn(e,'continuity'));assert(JSON.stringify(e).length<16000);}finally{await f.close();}
});

test('NPC relationship evidence retains only bounded character-specific signed integers',async()=>{
 for(const outside of [false,true]){
  for(const relationship of [100,-100,25,-25,0,101,-101,1.5,'25',null,{other:10}]){
   const f=await fixture();try{
    const project=f.engine.project,target={characterId:'mira',name:'Mira',role:'shopkeeper',relationship,relationships:{other:'PRIVATE GM MAP'},memories:[]};
    f.engine.project=async scope=>({...await project(scope),...(scope.audience==='private'?{npcs:[...(outside?Array.from({length:8},(_,i)=>({characterId:'bystander-'+i,memories:[]})):[]),target]}:{})});
    f.view.pendingActions=[{id:'relationship-intent',actorId:'lantern-fighter',targetId:'mira',kind:'npc-conversation',text:'Do you trust me?'}];
    await f.notify();await waitFor(directorStatus(f,'committed'));
    const npcs=f.requests[0].evidence.npcs,npc=npcs.find(n=>n.characterId==='mira');assert(npc);assert(npcs.length<=8);
    if(Number.isInteger(relationship)&&Math.abs(relationship)<=100)assert.equal(npc.relationship,relationship);
    else assert(!Object.hasOwn(npc,'relationship'));
    assert(!Object.hasOwn(npc,'relationships'));assert(!JSON.stringify(npcs).includes('PRIVATE GM MAP'));
   }finally{await f.close();}
  }
 }
});

async function rememberedEvidence({text,memories,outside=false}){
 const f=await fixture();try{
  const project=f.engine.project,npc={characterId:'mira',name:'Mira',role:'shopkeeper',memories,relationships:{other:'GM PRIVATE RELATIONSHIP'},gmNotes:'GM PRIVATE NOTES'};
  f.engine.project=async scope=>({...await project(scope),...(scope.audience==='private'?{npcs:[...(outside?Array.from({length:8},(_,i)=>({characterId:'bystander-'+i,memories:[]})):[]),npc]}:{})});
  f.view.pendingActions=[{id:'remembered-intent',actorId:'lantern-fighter',targetId:'mira',kind:'npc-conversation',text}];await f.notify();await waitFor(directorStatus(f,'committed'));return f.requests[0].evidence;
 }finally{await f.close();}
}
const history=()=>[{text:'You returned my ledger; I promised rope.',revision:1},{text:'The lantern was repaired.',revision:2},{text:'Rain delayed the ferry.',revision:3},{text:'Bread arrived this morning.',revision:4},{text:'The shop closes at dusk.',revision:5}];

test('NPC recall finds an older ledger promise while preserving recent context, including a crowded target',async()=>{
 for(const outside of [false,true]){const e=await rememberedEvidence({text:'What about the ledger and promised rope?',memories:history(),outside}),memories=e.npcs.find(n=>n.characterId==='mira').memories;assert.equal(memories.length,3);assert(memories.some(m=>m.revision===1));assert(memories.some(m=>m.revision===5));assert(!memories.some(m=>m.revision===2));assert(!JSON.stringify(e).includes('GM PRIVATE'));}
});

test('NPC recall falls back to the latest three when meaningful keywords do not match',async()=>{
 const e=await rememberedEvidence({text:'Could you please tell me about dragons?',memories:history()});assert.deepEqual(e.npcs[0].memories.map(m=>m.revision),[3,4,5]);
});

test('equal keyword matches choose newer memories deterministically and retain the latest context',async()=>{
 const memories=[1,2,3].map(revision=>({text:'Ledger account noted.',revision}));memories.push({text:'Earlier unrelated context.',revision:4},{text:'Current unrelated context.',revision:5});
 const e=await rememberedEvidence({text:'Ledger?',memories});assert.deepEqual(e.npcs[0].memories.map(m=>m.revision),[2,3,5]);
});

test('long intentions and memories retain the three-entry 500-character evidence bound',async()=>{
 const memories=Array.from({length:500},(_,i)=>({text:(i===0?'ledger promise ':'unrelated detail ')+ 'x'.repeat(1480),revision:i,gmNotes:'PRIVATE OVERRIDE'}));
 const e=await rememberedEvidence({text:('ledger '.repeat(214)).slice(0,1498),memories});const selected=e.npcs[0].memories;assert.equal(selected.length,3);assert(selected.some(m=>m.revision===0));assert(selected.every(m=>m.text.length<=500));assert(!JSON.stringify(e).includes('PRIVATE OVERRIDE'));
});
