import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,symlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createCampaignCatalog,createCampaignRegistry} from './campaign-registry.mjs';
import {activityHttp,createActivityRuntime} from './activity-runtime.mjs';
test('HTTP selection authenticates before runtime creation and isolates control tokens',async()=>{const f=await fixture();try{const catalog=createCampaignCatalog(f.entries,{defaultCampaignId:'alpha'}),built=[],sent=[];let revoked=false;const registry=createCampaignRegistry({catalog,createPlatform:config=>({auth:{config:{publicOrigin:'https://game.test'},authenticate:async request=>request.headers.get('cookie')===config.campaignId?{campaign:config.campaignId,owner:'gm',role:'host'}:null,member:async()=>revoked?null:{campaign:config.campaignId,role:'host'}}}),createRuntime:(config,{auth})=>{built.push(config.campaignId);return createActivityRuntime({auth,gmUserId:'gm',client:{campaignId:config.campaignId,project:async()=>({projectionVersion:2,audience:'gm',campaignId:config.campaignId,revision:1,currentSceneId:'briefing',characters:[],pendingActions:[],decisionOpen:true}),receipt:async()=>{throw Object.assign(Error('none'),{code:'RECEIPT_NOT_FOUND'});},command:async input=>{sent.push(input);return {success:true,revision:2};}}});}});const request=(id,cookie=id,method='GET',body)=>new Request(`https://game.test/api/hollow-lantern/${method==='GET'?'view':'action'}?campaignId=${id}`,{method,headers:{cookie,origin:'https://game.test','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const view=activityHttp('view',{registry});assert.equal((await view(request('alpha','beta'))).status,401);assert.deepEqual(built,[]);assert.equal((await view(request('missing','alpha'))).status,404);const a=await view(request('alpha')),b=await view(request('beta'));assert.equal(a.status,200);assert.equal(b.status,200);const av=await a.json(),bv=await b.json();assert.notEqual(av.viewToken,bv.viewToken);assert.deepEqual(built,['alpha','beta']);const cross=await activityHttp('action',{registry})(request('beta','beta','POST',{viewToken:av.viewToken,revision:1,commandId:'12345678-1234-4234-8234-123456789abc',action:'checkpoint',payload:{}}));assert.equal(cross.status,409);assert.deepEqual(sent,[]);revoked=true;assert.equal((await view(request('alpha'))).status,403);}finally{await f.close();}});
test('catalog accepts paired isolated draft RPC bindings and rejects partial or unsafe endpoints',async()=>{
 const f=await fixture();try{
  const secret=join(f.root,'rpc.secret');await writeFile(secret,'b'.repeat(64));
  const configured={...f.entries[0],draftRpcUrl:'http://127.0.0.1:41201/',draftRpcSecretFile:secret};
  const catalog=createCampaignCatalog([configured,f.entries[1]],{defaultCampaignId:'alpha'});assert.equal(catalog.get('alpha').draftRpcUrl,'http://127.0.0.1:41201');assert.equal(catalog.get('alpha').draftRpcSecretFile,secret);assert.equal(catalog.get('beta').draftRpcUrl,undefined);
  assert.equal(createCampaignCatalog([{...configured,engineUrl:'http://[::1]:41101'}],{defaultCampaignId:'alpha'}).get('alpha').engineUrl,'http://[::1]:41101');
  const built=[];const registry=createCampaignRegistry({catalog,createPlatform:()=>({}),createRuntime:config=>{built.push(config);return {};}});registry.runtime('alpha');assert.equal(built[0],catalog.get('alpha'));
  for(const missing of ['draftRpcUrl','draftRpcSecretFile']){const entry={...configured};delete entry[missing];assert.throws(()=>createCampaignCatalog([entry],{defaultCampaignId:'alpha'}),/draft|RPC/i);}
  for(const draftRpcUrl of ['http://[::1]:41201','https://127.0.0.1:41201','http://localhost:41201','http://2130706433:41201','http://127.0.0.1:41201/private','http://127.0.0.1:41201?token=x','http://user@127.0.0.1:41201','http://remote.example:41201'])assert.throws(()=>createCampaignCatalog([{...configured,draftRpcUrl}],{defaultCampaignId:'alpha'}),/draft|RPC/i);
  for(const draftRpcSecretFile of ['relative.secret',join(f.root,'OneDrive','rpc.secret'),join(f.root,'missing.secret'),f.root])assert.throws(()=>createCampaignCatalog([{...configured,draftRpcSecretFile}],{defaultCampaignId:'alpha'}));
 }finally{await f.close();}
});
test('catalog prevents cross-campaign draft endpoint and credential aliases',async()=>{
 const f=await fixture();try{
  const first=join(f.root,'first.secret'),second=join(f.root,'second.secret');await writeFile(first,'b'.repeat(64));await writeFile(second,'c'.repeat(64));
  const entries=f.entries.map((e,i)=>({...e,draftRpcUrl:`http://127.0.0.1:${41201+i}`,draftRpcSecretFile:i?second:first}));
  for(const draftRpcUrl of [entries[0].draftRpcUrl,entries[0].draftRpcUrl+'/'])assert.throws(()=>createCampaignCatalog([entries[0],{...entries[1],draftRpcUrl}],{defaultCampaignId:'alpha'}),/alias/i);
  assert.throws(()=>createCampaignCatalog([entries[0],{...entries[1],draftRpcSecretFile:first}],{defaultCampaignId:'alpha'}),/alias/i);
  await mkdir(join(f.root,'actual'));await writeFile(join(f.root,'actual','secret'),'d'.repeat(64));await symlink(join(f.root,'actual'),join(f.root,'alias'),'junction');
  assert.throws(()=>createCampaignCatalog([{...entries[0],draftRpcSecretFile:join(f.root,'actual','secret')},{...entries[1],draftRpcSecretFile:join(f.root,'alias','secret')}],{defaultCampaignId:'alpha'}),/alias/i);
 }finally{await f.close();}
});
const entry=(root,id,port)=>({campaignId:id,guildId:'guild-'+id,channelId:'channel-'+id,gmUserId:'gm-'+id,storeFile:join(root,id,'engine.json'),activityDataDir:join(root,id,'activity'),engineUrl:`http://127.0.0.1:${port}`,secretFile:join(root,id,'engine.secret'),artRoot:join(root,id,'art')});
async function fixture(){const root=await mkdtemp(join(tmpdir(),'campaign-registry-'));return {root,entries:[entry(root,'alpha',41101),entry(root,'beta',41102)],close:()=>rm(root,{recursive:true,force:true})};}
test('catalog freezes independent configuration and rejects ambiguous bindings',async()=>{const f=await fixture();try{const catalog=createCampaignCatalog(f.entries,{defaultCampaignId:'alpha'});f.entries[0].channelId='mutated';assert.equal(catalog.get('alpha').channelId,'channel-alpha');assert.throws(()=>{catalog.get('alpha').channelId='changed';},TypeError);assert.throws(()=>catalog.get('missing'),/Unknown campaign/);for(const key of ['campaignId','storeFile','activityDataDir','engineUrl','secretFile']){const entries=[entry(f.root,'alpha',41101),entry(f.root,'beta',41102)];entries[1][key]=entries[0][key];assert.throws(()=>createCampaignCatalog(entries,{defaultCampaignId:'alpha'}),/duplicate|alias/i);}assert.throws(()=>createCampaignCatalog([entry(f.root,'alpha',41101)],{defaultCampaignId:'missing'}),/default/i);}finally{await f.close();}});
test('membership precedes construction and sessions never select another campaign',async()=>{const f=await fixture();try{const catalog=createCampaignCatalog(f.entries,{defaultCampaignId:'alpha'}),built=[],platforms=[];let revoked=false;const make=()=>createCampaignRegistry({catalog,createPlatform:config=>{platforms.push(config.campaignId);return {auth:{authenticate:async request=>request.headers.get('cookie')===config.campaignId?{campaign:config.campaignId,owner:'player',role:'player'}:null,member:async()=>revoked?null:{campaign:config.campaignId,role:'player'}}};},createRuntime:(config)=>{built.push(config.campaignId);return {campaignId:config.campaignId,controls:new Map()};}});const registry=make(),request=id=>new Request('https://game.test/view',{headers:{cookie:id}});await assert.rejects(registry.authenticatedRuntime('alpha',request('beta')),/Sign in/);assert.deepEqual(built,[]);await assert.rejects(registry.authenticatedRuntime('missing',request('alpha')),/Unknown campaign/);assert.deepEqual(platforms,['alpha']);const alpha=await registry.authenticatedRuntime('alpha',request('alpha'));const beta=await registry.authenticatedRuntime('beta',request('beta'));assert.notEqual(alpha,beta);alpha.controls.set('token','alpha');assert.equal(beta.controls.has('token'),false);assert.equal(await registry.authenticatedRuntime('alpha',request('alpha')),alpha);revoked=true;await assert.rejects(registry.authenticatedRuntime('alpha',request('alpha')),/membership/);assert.deepEqual(built,['alpha','beta']);revoked=false;const restarted=make();assert.notEqual(await restarted.authenticatedRuntime('alpha',request('alpha')),alpha);assert.deepEqual(built,['alpha','beta','alpha']);}finally{await f.close();}});
test('catalog rejects relative, cloud and physical aliases',async()=>{const f=await fixture();try{for(const path of ['relative.json',join(f.root,'OneDrive - Business','state.json')]){const entries=structuredClone(f.entries);entries[0].storeFile=path;assert.throws(()=>createCampaignCatalog(entries,{defaultCampaignId:'alpha'}),/local/i);}await mkdir(join(f.root,'shared'));await symlink(join(f.root,'shared'),join(f.root,'alias'),'junction');const entries=structuredClone(f.entries);entries[0].activityDataDir=join(f.root,'shared');entries[1].activityDataDir=join(f.root,'alias');assert.throws(()=>createCampaignCatalog(entries,{defaultCampaignId:'alpha'}),/alias/i);}finally{await f.close();}});
