import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createCommitFollower} from './commit-events.mjs';
const marker=n=>({revision:n,commandId:`cancel${n}`,ownerId:'player',actorId:'fighter',type:'command_cancelled',receipt:null,control:{contract:'rpg-core-runtime-bridge-v1',code:'COMMAND_CANCELLED',terminal:true,campaignId:'campaign',commandId:`cancel${n}`,ownerId:'player',actorId:'fighter',originalExpectedRevision:n-1,revision:n},publicProjection:{revision:n,campaignId:'campaign',audience:'public'}});
test('cancellation metadata advances durable cursor without gameplay dispatch',async t=>{const config=await fixture(t),seen=[];config.client.project=async()=>({campaignId:'campaign',audience:'gm',revision:3,committedEvents:{version:1,latestRevision:3,retainedFromRevision:1,entries:[entry(1),marker(2),entry(3)]}});const f=await createCommitFollower({...config,onEvent:async e=>seen.push(e.revision)});try{const result=await f.poll();assert.equal(result.revision,3);assert.deepEqual(seen,[1,3]);assert.equal(f.status().pending,null);}finally{await f.close();}const reopened=await createCommitFollower({...config,onEvent:async()=>assert.fail('replayed gameplay')});try{await reopened.poll();assert.equal(reopened.status().revision,3);}finally{await reopened.close();}});
test('malformed or foreign cancellation metadata never advances cursor or dispatches',async t=>{const cases=[e=>e.type='unknown_control',e=>e.control.contract='other',e=>e.control.terminal=false,e=>e.control.campaignId='other',e=>e.control.ownerId='peer',e=>e.control.actorId='peer',e=>e.control.commandId='peer',e=>e.control.revision=2,e=>e.control.originalExpectedRevision=1,e=>e.control.originalExpectedRevision=-1,e=>e.control.extra='unsupported',e=>e.receipt={revision:1,commandId:e.commandId,replayed:false},e=>e.publicProjection.gmNotes='private',e=>delete e.control];for(const change of cases){const config=await fixture(t),value=marker(1);change(value);config.client.project=async()=>({campaignId:'campaign',audience:'gm',revision:1,committedEvents:{version:1,latestRevision:1,retainedFromRevision:1,entries:[value]}});const f=await createCommitFollower({...config,onEvent:async()=>assert.fail('metadata dispatched')});try{await assert.rejects(f.poll(),error=>['COMMIT_ENTRY_INVALID','COMMIT_PUBLIC_PRIVACY'].includes(error.code));assert.equal(f.status().revision,0);assert.equal(f.status().pending,null);}finally{await f.close();}}});
test('membership is rechecked before committing a metadata cursor',async t=>{const config=await fixture(t);let checks=0;config.client.project=async()=>({campaignId:'campaign',audience:'gm',revision:1,committedEvents:{version:1,latestRevision:1,retainedFromRevision:1,entries:[marker(1)]}});const f=await createCommitFollower({...config,authorize:async()=>++checks===1,onEvent:async()=>assert.fail('metadata dispatched')});try{await assert.rejects(f.poll(),{code:'COMMIT_OBSERVER_REVOKED'});assert.equal(f.status().revision,0);}finally{await f.close();}});
const entry=n=>({revision:n,commandId:`c${n}`,ownerId:'gm',actorId:'',type:'checkpoint',receipt:{revision:n,commandId:`c${n}`,replayed:false},publicProjection:{revision:n,campaignId:'campaign',audience:'public'}});
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'hollow-follow-'));t.after(()=>rm(dir,{recursive:true,force:true}));return {cursorFile:join(dir,'cursor.json'),gmUserId:'gm',authorize:async()=>true,client:{campaignId:'campaign',project:async()=>({campaignId:'campaign',audience:'gm',revision:2,committedEvents:{version:1,latestRevision:2,retainedFromRevision:1,entries:[entry(1),entry(2)]}})}};}
test('ordered events persist cursor and are not replayed after restart',async t=>{const config=await fixture(t),seen=[];const f=await createCommitFollower({...config,onEvent:async e=>seen.push(e.revision)});await Promise.all([f.poll(),f.poll()]);await f.close();const reopened=await createCommitFollower({...config,onEvent:async()=>assert.fail('replayed')});await reopened.poll();assert.deepEqual(seen,[1,2]);await reopened.close();});
test('ambiguous observer failure is durable and never automatically redelivered',async t=>{const config=await fixture(t);let count=0;const f=await createCommitFollower({...config,onEvent:async()=>{count++;throw Error('uncertain');}});await assert.rejects(f.poll());await f.close();const reopened=await createCommitFollower({...config,onEvent:async()=>count++});await assert.rejects(reopened.poll(),{code:'COMMIT_DELIVERY_UNCERTAIN'});assert.equal(count,1);await reopened.acknowledgeDelivered({revision:1,commandId:'c1'});await reopened.poll();assert.equal(count,2);await reopened.close();});
test('missing retention interval is reported without inventing earlier snapshots',async t=>{const config=await fixture(t);config.client.project=async()=>({campaignId:'campaign',audience:'gm',revision:80,committedEvents:{version:1,latestRevision:80,retainedFromRevision:17,entries:[]}});let gap;const f=await createCommitFollower({...config,onEvent:async()=>assert.fail('gap delivered'),onGap:g=>gap=g});assert.equal((await f.poll()).status,'history-gap');assert.deepEqual(gap,{from:1,to:16});await f.close();});
test('revoked observer and mutated public snapshot cannot be delivered',async t=>{const config=await fixture(t);const f=await createCommitFollower({...config,authorize:async()=>false,onEvent:async()=>assert.fail('revoked')});await assert.rejects(f.poll(),{code:'COMMIT_OBSERVER_REVOKED'});await f.close();config.client.project=async()=>({campaignId:'campaign',audience:'gm',revision:1,committedEvents:{version:1,latestRevision:1,retainedFromRevision:1,entries:[{...entry(1),publicProjection:{audience:'gm',revision:1,campaignId:'campaign'}}]}});const bad=await createCommitFollower({...config,onEvent:async()=>assert.fail('bad snapshot')});await assert.rejects(bad.poll(),{code:'COMMIT_ENTRY_INVALID'});await bad.close();});
test('exclusive cursor lock refuses a second follower and releases on clean close',async t=>{const config=await fixture(t);const f=await createCommitFollower({...config,onEvent:async()=>{}});await assert.rejects(createCommitFollower({...config,onEvent:async()=>{}}),{code:'COMMIT_FOLLOWER_LOCKED'});await f.close();const next=await createCommitFollower({...config,onEvent:async()=>{}});await next.poll();assert.equal(next.status().revision,2);await next.close();});
test('failed observer status exposes sanitized error without callback secrets',async t=>{const config=await fixture(t);const f=await createCommitFollower({...config,onEvent:async()=>{throw Error('private callback detail');}});await assert.rejects(f.poll());assert.equal(f.status().lastError,'COMMIT_OBSERVER_FAILED');assert.doesNotMatch(JSON.stringify(f.status()),/private callback detail/);await f.close();});
