import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import {spawnSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openDirectorRecoveryStore} from './director-recovery-store.mjs';
const command=()=>({ownerId:'ai-director:test',actorId:'',commandId:'director:'+'a'.repeat(48),expectedRevision:4,authorityEpoch:2,type:'gm_resolve',payload:{pendingId:'intent-4',approved:true,text:'Synthetic ruling.'}});
async function fixture(run){const dir=await fs.mkdtemp(join(tmpdir(),'director-journal-'));try{await run(join(dir,'journal.sqlite'));}finally{await fs.rm(dir,{recursive:true,force:true});}}
test('journal survives restart with exact envelope and clears atomically',()=>fixture(async file=>{const store=await openDirectorRecoveryStore({file,campaignId:'test'});await store.save(command());const reopened=await openDirectorRecoveryStore({file,campaignId:'test'});assert.deepEqual(reopened.get(),command());await assert.rejects(reopened.clear('wrong'));await reopened.clear(command().commandId);assert.equal((await openDirectorRecoveryStore({file,campaignId:'test'})).get(),null);}));
test('journal rejects corruption, wrong campaign, tampering and backup-only recovery',()=>fixture(async file=>{const store=await openDirectorRecoveryStore({file,campaignId:'test'});await store.save(command());await assert.rejects(openDirectorRecoveryStore({file,campaignId:'other'}));const db=new DatabaseSync(file);db.prepare('UPDATE director_journal SET record=replace(record,?,?)').run('Synthetic ruling.','Altered ruling.');db.close();await assert.rejects(openDirectorRecoveryStore({file,campaignId:'test'}));await fs.rename(file,file+'.bak');await assert.rejects(openDirectorRecoveryStore({file,campaignId:'test'}));await fs.writeFile(file,'not a database');await assert.rejects(openDirectorRecoveryStore({file,campaignId:'test'}));}));
test('process crash during a clear rolls back and releases the database lock',()=>fixture(async file=>{const store=await openDirectorRecoveryStore({file,campaignId:'test'});await store.save(command());const child=spawnSync(process.execPath,['--input-type=module','-e',"import {DatabaseSync} from 'node:sqlite';const db=new DatabaseSync(process.argv[1]);db.exec('BEGIN IMMEDIATE');db.exec('DELETE FROM director_journal');process.exit(7);",file],{encoding:'utf8'});assert.equal(child.status,7,child.stderr);const recovered=await openDirectorRecoveryStore({file,campaignId:'test'});assert.deepEqual(recovered.get(),command());await recovered.clear(command().commandId);assert.equal((await openDirectorRecoveryStore({file,campaignId:'test'})).get(),null);}));
test('stale and concurrent writers cannot overwrite an unresolved journal',()=>fixture(async file=>{const first=await openDirectorRecoveryStore({file,campaignId:'test'}),second=await openDirectorRecoveryStore({file,campaignId:'test'});const outcomes=await Promise.allSettled([first.save(command()),second.save({...command(),authorityEpoch:3})]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);const saved=(await openDirectorRecoveryStore({file,campaignId:'test'})).get();assert.equal(saved.authorityEpoch,2);await assert.rejects(second.clear(saved.commandId));}));
test('journal rejects OneDrive, relative paths and invalid command envelopes',()=>fixture(async file=>{for(const badFile of ['relative.sqlite',join(tmpdir(),'OneDrive - Business','journal.sqlite')])await assert.rejects(openDirectorRecoveryStore({file:badFile,campaignId:'test'}));const store=await openDirectorRecoveryStore({file,campaignId:'test'});for(const bad of [{...command(),actorId:'player'},{...command(),type:'gm_owner'},{...command(),authorityEpoch:-1},{...command(),extra:true},{...command(),payload:{...command().payload,secret:true}},{...command(),payload:{...command().payload,text:'x'.repeat(1501)}}])await assert.rejects(store.save(bad));assert.equal(store.get(),null);}));
