import {randomUUID,createHash} from 'node:crypto';
import {CharacterStore} from '../characters/store.mjs';
import {issues} from '../characters/model.mjs';
import {EngineError} from './engine-client.mjs';
export const BLUEPRINTS=Object.freeze({fighter:'fighter-champion-human-soldier-v1',rogue:'rogue-thief-high-elf-criminal-v1',cleric:'cleric-life-human-acolyte-v1'});
const fail=(code,message)=>{throw new EngineError(code,message,409);};
const digest=snapshot=>createHash('sha256').update(JSON.stringify(snapshot)).digest('hex');
const clean=value=>String(value??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const sameField=(actual,expected)=>typeof expected==='number'
 ? (typeof actual==='number'&&Number.isFinite(actual)||typeof actual==='string'&&/^[+-]?\d+(?:\.\d+)?$/.test(actual.trim()))&&Number(actual)===expected
 : clean(actual)===clean(expected);
/** Expected import fields are strict, explicit supported-build facts, never mechanical inputs. */
export function expectedImportFields(actor,inventory){const sheet=actor.sheet;return {classes:`${actor.classId} 3`,level:3,background:sheet.background,species:sheet.ancestry,subclass:sheet.subclass,...actor.scores,armorClass:actor.armorClass,maxHp:actor.primaryHealthMaximum,proficiencyBonus:2,speed:30,equipment:inventory.items.map(i=>`${i.itemId}:${i.quantity}`).sort().join(';'),features:actor.abilities.slice().sort().join(';'),spells:sheet.spellcasting?[...(sheet.spellcasting.cantrips??[]),...(sheet.spellcasting.originCantrips??[]),...(sheet.spellcasting.prepared??[]),...(sheet.spellcasting.domainPrepared??[]),...(sheet.spellcasting.originSpell?[sheet.spellcasting.originSpell]:[]),...(sheet.spellcasting.innateSpell?[sheet.spellcasting.innateSpell]:[])].sort().join(';'):'none'};}
export function compareImport(snapshot,expected){const mismatches=issues(snapshot);if(snapshot.edition!=='2024')mismatches.push('Confirm 2024 rules.');for(const [key,value] of Object.entries(expected)){const field=snapshot.fields?.[key];if(!field||field.conflict||field.uncertain&&!field.corrected||!sameField(field.value,value))mismatches.push(`${key}: supported blueprint requires ${value}; source reports ${field?.value??'not supplied'}.`);}for(const [key,field] of Object.entries(snapshot.fields??{})){if(field?.value==null||Object.hasOwn(expected,key)||['name','notes','currentHp','tempHp'].includes(key))continue;mismatches.push(`${key}: this additional source assertion requires review; it is not supported by the selected blueprint import mapping.`);}return [...new Set(mismatches)];}
/** Server-owned candidates. Caller credentials come from the authenticated transport, never form ownerId. */
export function createEnrollmentService({engine,characterStore,characterStorePath,importCampaign,gmUserId,authorize,now=Date.now}){
 if(!engine?.project||!engine?.command||!gmUserId||typeof authorize!=='function')throw new Error('Authenticated engine enrollment configuration required.');
 const owned=!characterStore,store=characterStore??new CharacterStore(characterStorePath),candidates=new Map();
 async function auth(scope,gm=false){if(!scope||scope.campaignId!==engine.campaignId||!await authorize(scope)||gm&&scope.userId!==gmUserId)fail('ACCESS_DENIED','Current campaign access is required.');}
 async function blueprint(classId){if(!BLUEPRINTS[classId])fail('UNSUPPORTED_BLUEPRINT','Choose fighter, rogue or cleric.');const p=await engine.project({ownerId:gmUserId,actorId:`lantern-${classId}`,audience:'private'});const actor=p.enrollmentPreview?.actor;if(!actor?.sheet||p.decisionOpen||p.currentSceneId!=='briefing'||p.mission?.briefed)fail('ENROLLMENT_CLOSED','Guided enrollment requires a paused, unstarted briefing.');return {actor,inventory:p.enrollmentPreview.inventory,revision:p.revision};}
 async function preview(scope,input){await auth(scope);if(Object.keys(input??{}).some(k=>!['classId','name','narrative','edition','sourceKind','expectedImportRevision'].includes(k)))fail('INVALID_INPUT','Only guided character choices are accepted.');if(input.edition!=='2024')fail('EDITION_REQUIRED','Explicitly confirm 2024.');const b=await blueprint(input.classId),expected=expectedImportFields(b.actor,b.inventory);let source={kind:'guided'},mismatches=[],name=input.name,record;
  if(input.sourceKind==='approved-import'){record=store.character({campaign:importCampaign,owner:scope.userId});if(!record||record.revision!==input.expectedImportRevision)fail('STALE_IMPORT','Review the current approved import revision.');source={kind:'approved-import',recordRevision:record.revision,snapshotSha256:digest(record.snapshot)};const optional={...(b.actor.skills??{})};for(const [ability,score] of Object.entries(b.actor.scores??{})){optional[`${ability}Modifier`]=Math.floor((score-10)/2);optional[`${ability}Save`]=Math.floor((score-10)/2)+(b.actor.saveProficiencies?.includes(ability)?2:0);}optional.passivePerception=b.actor.sheet.passivePerception;optional.slots1=b.actor.resources?.spellSlots1??0;optional.slots2=b.actor.resources?.spellSlots2??0;if(b.actor.sheet.spellcasting){optional.spellAbility=b.actor.sheet.spellcasting.ability;optional.spellSaveDc=b.actor.sheet.spellcasting.saveDc;optional.spellAttack=b.actor.sheet.spellcasting.attackBonus;optional.spellModifier=Math.floor(((b.actor.scores??{})[optional.spellAbility]-10)/2);}const declared=Object.fromEntries(Object.entries(optional).filter(([key,value])=>value!==undefined&&Object.hasOwn(record.snapshot.fields,key.replace(/ /g,''))).map(([key,value])=>[key.replace(/ /g,''),value]));mismatches=compareImport(record.snapshot,{...expected,...declared});name=record.snapshot.fields.name?.value;}
  else if(input.sourceKind!=='guided')fail('INVALID_INPUT','Choose guided creation or an approved import.');
  if(typeof name!=='string'||!name.trim()||name.length>80||/[\x00-\x1f]/.test(name)||typeof(input.narrative??'')!=='string'||(input.narrative??'').length>1500)fail('INVALID_INPUT','Supply a name up to 80 characters and a narrative up to 1500.');
  const id=randomUUID(),payload={seatId:b.actor.characterId,blueprintId:BLUEPRINTS[input.classId],ownerId:scope.userId,name:name.trim(),narrative:input.narrative??'',edition:'2024',source};
  const candidate={id,createdBy:scope.userId,classId:input.classId,payload,expiresAt:now()+900000,revision:b.revision,mismatches,preview:{...structuredClone(b),expectedImportFields:expected,name:payload.name,narrative:payload.narrative,resourcePolicy:'Existing campaign health, resources and belongings are preserved. Imported current HP and spent resources are not applied.'}};
  for(const [key,value] of candidates)if(value.expiresAt<=now())candidates.delete(key);if(candidates.size>=100)fail('BUSY','The enrollment desk is full. Complete an existing review.');candidates.set(id,candidate);return {candidateId:id,expiresAt:candidate.expiresAt,eligible:!mismatches.length,mismatches,preview:structuredClone(candidate.preview)};
 }
 async function list(scope){await auth(scope,true);return [...candidates.values()].filter(c=>c.expiresAt>now()).map(c=>({candidateId:c.id,ownerId:c.createdBy,name:c.payload.name,blueprintId:c.payload.blueprintId,eligible:!c.mismatches.length,mismatches:[...c.mismatches],preview:structuredClone(c.preview)}));}
 async function approve(scope,{candidateId,commandId,expectedRevision}){await auth(scope,true);const c=candidates.get(candidateId);if(!c||c.expiresAt<=now())fail('STALE_CANDIDATE','Reopen the guided character preview.');await auth({campaignId:engine.campaignId,userId:c.createdBy});if(c.mismatches.length)fail('IMPORT_MISMATCH','Correct the listed source differences before enrollment.');if(c.payload.source.kind==='approved-import'){const saved=store.character({campaign:importCampaign,owner:c.createdBy});if(!saved||saved.revision!==c.payload.source.recordRevision||digest(saved.snapshot)!==c.payload.source.snapshotSha256)fail('STALE_IMPORT','The approved import changed; create a fresh preview.');}
  if(c.intent&&(c.intent.commandId!==commandId||c.intent.expectedRevision!==expectedRevision))fail('COMMAND_COLLISION','Retry the original enrollment identity or create a new preview.');
  c.intent??={ownerId:gmUserId,actorId:'',commandId,expectedRevision,type:'gm_enroll_character',payload:structuredClone(c.payload)};
  return engine.command(structuredClone(c.intent));
 }
 async function approvedImport(scope){await auth(scope);const record=store.character({campaign:importCampaign,owner:scope.userId});return record?{revision:record.revision,name:record.snapshot.fields.name?.value??'Approved character'}:null;}
 async function currentRevision(scope){await auth(scope,true);return (await engine.project({ownerId:gmUserId,audience:'gm'})).revision;}
 return Object.freeze({preview,list,approve,approvedImport,currentRevision,close(){if(owned)store.close();}});
}
