import test from 'node:test';
import assert from 'node:assert/strict';
import {CharacterStore} from '../characters/store.mjs';
import {emptyDraft,addEvidence} from '../characters/model.mjs';
import {createEnrollmentService,expectedImportFields,compareImport} from './enrollment.mjs';
const owner={campaignId:'lantern',userId:'123'},gm={campaignId:'lantern',userId:'999'};
const actor={characterId:'lantern-fighter',classId:'fighter',primaryHealthMaximum:31,armorClass:19,scores:{strength:16,dexterity:12,constitution:16,intelligence:10,wisdom:13,charisma:8},abilities:['second-wind'],sheet:{background:'soldier',ancestry:'human',subclass:'champion'}},inventory={items:[{itemId:'longsword',quantity:1}]};
function setup(){const store=new CharacterStore(':memory:'),sent=[];let allowed=true;const engine={campaignId:'lantern',project:async()=>({enrollmentPreview:{actor,inventory},currentSceneId:'briefing',decisionOpen:false,revision:0}),command:async c=>{sent.push(c);return {revision:1};}};const service=createEnrollmentService({engine,characterStore:store,importCampaign:'imports',gmUserId:'999',authorize:async()=>allowed});return {store,service,sent,revoke(){allowed=false;}};}
function save(store,overrides={}){const scope={campaign:'imports',owner:'123'},draft=emptyDraft();draft.edition='2024';for(const [key,value] of Object.entries({...expectedImportFields(actor,inventory),name:'Imported Mara',...overrides}))addEvidence(draft,key,value,{method:'manual'});const j=store.createJob(scope,String(Math.random()));store.ready(j.id,scope,draft,'fixture');return store.approve(j.id,scope,store.job(j.id,scope).revision);}
const guided={classId:'fighter',name:'Mara',narrative:'A lighthouse veteran',edition:'2024',sourceKind:'guided'};
test('numeric import assertions preserve signs and reject decorated or empty values',()=>{
 for(const value of ['+1','1','','-1 bonus']){const draft=emptyDraft();draft.edition='2024';addEvidence(draft,'charismaModifier',value,{method:'manual'});assert.ok(compareImport(draft,{charismaModifier:-1}).some(x=>x.startsWith('charismaModifier:')));}
 for(const value of [-1,'-1']){const draft=emptyDraft();draft.edition='2024';addEvidence(draft,'charismaModifier',value,{method:'manual'});assert.ok(!compareImport(draft,{charismaModifier:-1}).some(x=>x.startsWith('charismaModifier:')));}
});
test('guided preview derives full supported sheet and GM submits only server-owned intent',async()=>{const f=setup();try{const p=await f.service.preview(owner,guided);assert.equal(p.preview.actor.armorClass,19);assert.equal(p.eligible,true);await assert.rejects(f.service.approve(owner,{candidateId:p.candidateId,commandId:'x',expectedRevision:0}),{code:'ACCESS_DENIED'});await f.service.approve(gm,{candidateId:p.candidateId,commandId:'x',expectedRevision:0});assert.equal(f.sent[0].payload.ownerId,'123');assert.equal(f.sent[0].payload.name,'Mara');assert.ok(!('armorClass' in f.sent[0].payload));await f.service.approve(gm,{candidateId:p.candidateId,commandId:'x',expectedRevision:0});assert.deepEqual(f.sent[0],f.sent[1]);}finally{f.store.close();}});
test('manual creation requires explicit edition and rejects arbitrary statistics',async()=>{const f=setup();try{await assert.rejects(f.service.preview(owner,{...guided,edition:null}),{code:'EDITION_REQUIRED'});await assert.rejects(f.service.preview(owner,{...guided,maxHp:999}),{code:'INVALID_INPUT'});}finally{f.store.close();}});
test('approved import uses actual CharacterStore approved revision and rejects changed source',async()=>{const f=setup();try{save(f.store);const p=await f.service.preview(owner,{...guided,sourceKind:'approved-import',expectedImportRevision:1});assert.equal(p.eligible,true);assert.equal(p.preview.name,'Imported Mara');save(f.store,{armorClass:99});await assert.rejects(f.service.approve(gm,{candidateId:p.candidateId,commandId:'x',expectedRevision:0}),{code:'STALE_IMPORT'});assert.equal(f.sent.length,0);const changed=await f.service.preview(owner,{...guided,sourceKind:'approved-import',expectedImportRevision:2});assert.equal(changed.eligible,false);assert.ok(changed.mismatches.some(m=>m.startsWith('armorClass')));await assert.rejects(f.service.approve(gm,{candidateId:changed.candidateId,commandId:'y',expectedRevision:0}),{code:'IMPORT_MISMATCH'});}finally{f.store.close();}});
test('source ownership and current membership cannot be supplied by a form',async()=>{const f=setup();try{save(f.store);await assert.rejects(f.service.preview({...owner,userId:'124'},{...guided,sourceKind:'approved-import',expectedImportRevision:1}),{code:'STALE_IMPORT'});const p=await f.service.preview(owner,guided);f.revoke();await assert.rejects(f.service.approve(gm,{candidateId:p.candidateId,commandId:'x',expectedRevision:0}),{code:'ACCESS_DENIED'});assert.equal(f.sent.length,0);}finally{f.store.close();}});
