import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,mkdir,symlink,readdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createOAuthRecovery,DAVY_CLIENT_ID} from './oauth-secret-recovery.mjs';
const secret='new_private_fixture_secret_12345';
async function setup(t,fetchImpl){const root=await mkdtemp(join(tmpdir(),'oauth-recovery-'));t.after(()=>rm(root,{recursive:true,force:true}));const target=join(root,'.env.native-gateway'),backupRoot=join(root,'backups'),secretFile=join(root,'input.secret');const before=`# retain\r\nDISCORD_CLIENT_ID=${DAVY_CLIENT_ID}\r\nDISCORD_TOKEN=fixture_bot_unchanged\r\nOTHER="keep this"\r\nDISCORD_CLIENT_SECRET=old_fixture_secret_12345\r\n`;await writeFile(target,before);await writeFile(secretFile,secret+'\n');const protectedPaths=[];const recovery=createOAuthRecovery({target,backupRoot,fetchImpl,protectImpl:async p=>{protectedPaths.push(p);}});return {root,target,backupRoot,secretFile,before,recovery,protectedPaths};}
test('verified Basic grant changes only secret, private backup restores exact bytes',async t=>{let requests=0;const f=await setup(t,async(url,init)=>{requests++;assert.equal(url,'https://discord.com/api/v10/oauth2/token');assert.equal(init.headers.Authorization,'Basic '+Buffer.from(`${DAVY_CLIENT_ID}:${secret}`).toString('base64'));assert.equal(init.body.get('grant_type'),'client_credentials');assert.equal(init.body.get('scope'),'applications.commands.update');assert.equal(init.redirect,'error');return Response.json({access_token:'never_saved'});});const r=await f.recovery.replace({secretFile:f.secretFile});assert.equal(requests,1);assert.equal(await readFile(f.target,'utf8'),f.before.replace('old_fixture_secret_12345',secret));assert.equal(await readFile(join(f.backupRoot,r.id,'before.env'),'utf8'),f.before);const receipt=await readFile(join(f.backupRoot,r.id,'receipt.json'),'utf8');assert.doesNotMatch(receipt,/secret|never_saved|hash/i);assert.ok(f.protectedPaths.length>=6);assert.equal((await f.recovery.rollback({id:r.id})).status,'restored');assert.equal(await readFile(f.target,'utf8'),f.before);assert.equal((await f.recovery.rollback({id:r.id})).status,'already-restored');});
test('rejected and thrown verification never change file or reflect secrets',async t=>{for(const provider of [async()=>Response.json({error:'invalid_client',error_description:secret},{status:401}),async()=>{throw new Error(secret);}]){const f=await setup(t,provider);await assert.rejects(f.recovery.replace({secretFile:f.secretFile}),e=>{assert.doesNotMatch(e.message,/new_private|invalid_client/);return true;});assert.equal(await readFile(f.target,'utf8'),f.before);assert.deepEqual(await readdir(f.backupRoot),[]);}});
test('concurrent configuration edit prevents write and rollback refuses later edits',async t=>{let f;f=await setup(t,async()=>{await writeFile(f.target,f.before+'CONCURRENT=yes\r\n');return Response.json({access_token:'unused'});});await assert.rejects(f.recovery.replace({secretFile:f.secretFile}));assert.match(await readFile(f.target,'utf8'),/CONCURRENT/);const g=await setup(t,async()=>new Response('',{status:200}));const r=await g.recovery.replace({secretFile:g.secretFile});await writeFile(g.target,'changed by another task');await assert.rejects(g.recovery.rollback({id:r.id}));assert.equal(await readFile(g.target,'utf8'),'changed by another task');});
test('wrong client, injection and duplicate override are rejected before network',async t=>{for(const kind of ['client','injection','duplicate']){const f=await setup(t,async()=>{assert.fail('must not call network');});if(kind==='client')await writeFile(f.target,f.before.replace(DAVY_CLIENT_ID,'100000000000000001'));if(kind==='injection')await writeFile(f.secretFile,secret+'\nDISCORD_TOKEN=bad');if(kind==='duplicate')await writeFile(f.target,f.before+'DISCORD_CLIENT_SECRET=second\n');await assert.rejects(f.recovery.replace({secretFile:f.secretFile}));}});
test('backup directory junction and existing recovery lock fail closed',async t=>{const f=await setup(t,async()=>{assert.fail('no network');});await mkdir(f.backupRoot);await writeFile(join(f.backupRoot,'replacement.lock'),'owned');await assert.rejects(f.recovery.replace({secretFile:f.secretFile}));assert.equal(await readFile(join(f.backupRoot,'replacement.lock'),'utf8'),'owned');const g=await setup(t,async()=>{assert.fail('no network');});const outside=join(g.root,'outside');await mkdir(outside);try{await symlink(outside,g.backupRoot,'junction');}catch(e){if(['EPERM','EACCES'].includes(e.code)){t.skip('junction denied by OS');return;}throw e;}await assert.rejects(g.recovery.replace({secretFile:g.secretFile}));});
test('production permission protection succeeds on disposable files',async t=>{const f=await setup(t);const recovery=createOAuthRecovery({target:f.target,backupRoot:f.backupRoot,fetchImpl:async()=>new Response('',{status:200})});const r=await recovery.replace({secretFile:f.secretFile});assert.equal(r.status,'replaced');assert.equal((await recovery.rollback({id:r.id})).status,'restored');});
