import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createPublicFeed} from './public-feed.mjs';
const png=Buffer.from([137,80,78,71,13,10,26,10,1]);
const config={campaignId:'campaign',guildId:'guild',channelId:'channel',applicationId:'application'};
const record=n=>({receipt:{contract:'rpg-core-runtime-bridge-v1',success:true,campaignId:'campaign',revision:n,commandId:`command-${n}`,result:{message:'PRIVATE ROLL',damage:999}},projection:{projectionVersion:2,campaignId:'campaign',audience:'public',characterId:'',revision:n,currentSceneId:'briefing',phase:'exploration',characters:[{characterId:'mara',displayName:'Mara',factionId:'party'}],publicEvents:[{revision:n,text:`Public event ${n}`} ]}});
async function fixture(){const directory=await mkdtemp(join(tmpdir(),'public-feed-'));return {directory,path:join(directory,'feed.json')};}
function channel(){const sent=[],messages=new Map();return {id:'channel',guildId:'guild',client:{application:{id:'application'},user:{id:'bot'}},sent,messages:{async fetch(){return messages;}},async send(payload){sent.push(payload);const m={id:String(sent.length),nonce:payload.nonce,author:{id:'bot'},channelId:'channel',components:payload.components,attachments:new Map([['image',{name:payload.files[0].name}]])};messages.set(m.id,m);return m;},records:messages};}
test('records are durable before render, ordered by revision, duplicate-safe across restart',async()=>{const f=await fixture();let feed;try{feed=await createPublicFeed({...config,path:f.path});const c=channel();await feed.record(record(2));await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,0);assert.equal((await feed.status()).missingRevision,1);await feed.record(record(1));await feed.flush({channel:c,render:async p=>{const file=await readFile(f.path,'utf8');assert.doesNotMatch(file,/PRIVATE ROLL|999/);assert.ok(file.includes('Public event'));return png;}});assert.equal(c.sent.length,2);assert.match(JSON.stringify(c.sent[0].components),/Revision 1/);assert.match(JSON.stringify(c.sent[1].components),/Revision 2/);await feed.close();feed=await createPublicFeed({...config,path:f.path});assert.equal((await feed.record(record(1))).duplicate,true);await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,2);}finally{await feed?.close();await rm(f.directory,{recursive:true,force:true});}});
test('wrong audience, revision and private character fields fail before persistence or sending',async()=>{const f=await fixture();const feed=await createPublicFeed({...config,path:f.path});try{for(const patch of [{audience:'private'},{revision:2},{inventory:{items:[]}}, {characters:[{characterId:'mara',primaryHealth:3}]}]){const r=record(1);Object.assign(r.projection,patch);await assert.rejects(feed.record(r));}assert.equal((await feed.status()).entries.length,0);await assert.rejects(feed.flush({channel:{...channel(),id:'other'},render:async()=>png}),{code:'WRONG_CHANNEL'});}finally{await feed.close();await rm(f.directory,{recursive:true,force:true});}});
test('uncertain POST persists its marker, blocks later sends and requires exact nonce recovery',async()=>{const f=await fixture();let feed=await createPublicFeed({...config,path:f.path});const c=channel(),send=c.send.bind(c);try{await feed.record(record(1));await feed.record(record(2));c.send=async p=>{const s=JSON.parse(JSON.parse(await readFile(f.path,'utf8')).payload);assert.equal(s.entries[0].status,'sending');await send(p);throw new Error('connection lost after Discord accepted');};await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,1);await feed.close();feed=await createPublicFeed({...config,path:f.path});await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,1);const m=c.records.get('1'),nonce=m.nonce;delete m.nonce;assert.equal((await feed.recover({channel:c,revision:1})).recovered,false);assert.equal(c.sent.length,1);m.nonce=nonce;m.author.id='impostor';assert.equal((await feed.recover({channel:c,revision:1})).recovered,false);m.author.id='bot';assert.equal((await feed.recover({channel:c,revision:1})).recovered,true);c.send=send;await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,2);assert.equal((await feed.status()).cursor,2);}finally{await feed.close();await rm(f.directory,{recursive:true,force:true});}});
test('scope binding, concurrent-open lock, collision and explicit gap acknowledgment are enforced',async()=>{const f=await fixture();let feed=await createPublicFeed({...config,path:f.path});try{await assert.rejects(createPublicFeed({...config,path:f.path}),{code:'FEED_LOCKED'});await feed.record(record(3));const changed=record(3);changed.projection.publicEvents[0].text='Changed';await assert.rejects(feed.record(changed),{code:'REVISION_COLLISION'});await assert.rejects(feed.acknowledgeGap({throughRevision:3,reason:'missing'}),{code:'INVALID_GAP'});await feed.acknowledgeGap({throughRevision:2,reason:'Operator confirms revisions 1–2 were never captured.'});const c=channel();await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,1);await feed.close();feed=null;await assert.rejects(createPublicFeed({...config,path:f.path,channelId:'wrong'}),{code:'WRONG_FEED_SCOPE'});}finally{await feed?.close();await rm(f.directory,{recursive:true,force:true});}});
test('renderer failure sends nothing; corrupt-primary recovery never blindly retries backup pending entries',async()=>{const f=await fixture();let feed=await createPublicFeed({...config,path:f.path});try{await feed.record(record(1));const c=channel();await assert.rejects(feed.flush({channel:c,render:async()=>Buffer.from('not an approved PNG')}),{code:'INVALID_ART'});assert.equal(c.sent.length,0);await feed.record(record(2));await feed.close();await writeFile(f.path,'corrupt');feed=await createPublicFeed({...config,path:f.path});assert.equal((await feed.status()).entries[0].status,'uncertain');await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,0);}finally{await feed.close();await rm(f.directory,{recursive:true,force:true});}});

test('actual Unity public empty placeholders are accepted but stripped from durable records',async()=>{const f=await fixture(),feed=await createPublicFeed({...config,path:f.path});try{const r=record(1);Object.assign(r.projection,{pendingActions:[],inventory:null,privateHistory:{},map:null,discoveries:[],mission:{briefed:false}});r.projection.characters=[{characterId:'mara',displayName:'Mara',characterType:'player',classId:'fighter',level:3,raceId:'human',factionId:'party',defeated:false}];await feed.record(r);const bytes=await readFile(f.path,'utf8');assert.doesNotMatch(bytes,/pendingActions|privateHistory|discoveries|mission/);const bad=record(2);bad.projection.pendingActions=[{text:'SECRET'}];await assert.rejects(feed.record(bad),{code:'PRIVATE_DATA'});}finally{await feed.close();await rm(f.directory,{recursive:true,force:true});}});


test('empty public revisions advance durably without cards; following event survives restart',async()=>{
 const f=await fixture();let feed=await createPublicFeed({...config,path:f.path});const c=channel();let renders=0;
 try{const empty=n=>{const r=record(n);r.projection.publicEvents=[];return r;};await feed.record(empty(1));await feed.record(empty(2));await feed.flush({channel:c,render:async()=>{renders++;return png;}});assert.equal(renders,0);assert.equal(c.sent.length,0);assert.equal((await feed.status()).cursor,2);assert.deepEqual((await feed.status()).entries.map(e=>e.status),['suppressed','suppressed']);
 await feed.close();feed=await createPublicFeed({...config,path:f.path});assert.equal((await feed.record(empty(1))).duplicate,true);await feed.record(record(3));await feed.flush({channel:c,render:async()=>{renders++;return png;}});assert.equal(c.sent.length,1);assert.equal(renders,1);assert.match(JSON.stringify(c.sent[0]),/Public event 3/);assert.equal((await feed.status()).cursor,3);
 const transition=empty(4);transition.projection.currentSceneId='coastal-road';await feed.record(transition);await feed.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,2);assert.equal((await feed.status()).cursor,4);
 }finally{await feed.close();await rm(f.directory,{recursive:true,force:true});}
});
test('quiet revisions cannot bypass uncertain delivery or infer a scene across a gap',async()=>{
 const f=await fixture(),feed=await createPublicFeed({...config,path:f.path});const c=channel();try{await feed.record(record(1));c.send=async()=>{throw Error('ambiguous');};await feed.flush({channel:c,render:async()=>png});const quiet=record(2);quiet.projection.publicEvents=[];await feed.record(quiet);await feed.flush({channel:c,render:async()=>assert.fail('Blocked on uncertain send')});assert.equal((await feed.status()).cursor,0);assert.equal((await feed.status()).entries[1].status,'pending');}finally{await feed.close();await rm(f.directory,{recursive:true,force:true});}
 const g=await fixture(),next=await createPublicFeed({...config,path:g.path,afterRevision:5});try{const quiet=record(6);quiet.projection.publicEvents=[];await next.record(quiet);const c=channel();await next.flush({channel:c,render:async()=>png});assert.equal(c.sent.length,1);}finally{await next.close();await rm(g.directory,{recursive:true,force:true});}
});
