import {open,readFile,rename,unlink,mkdir} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
const hash=v=>createHash('sha256').update(v).digest('hex'),safe=(v,n=1200)=>String(v??'').replace(/@/g,'@\u200b').slice(0,n);
const fail=(code,message)=>{const e=new Error(message);e.code=code;throw e;};
const privateKeys=['inventory','inventoryByCharacter','pendingActions','privateEvents','privateHistory','gmNotes','enrollmentPreview'];
function sanitize(p,scope,revision){if(p?.audience!=='public'||p.projectionVersion!==2||p.campaignId!==scope.campaignId||p.revision!==revision||p.characterId)fail('WRONG_PUBLIC_VIEW','A public projection at the exact receipt revision is required.');if(privateKeys.some(k=>Object.hasOwn(p,k)&&p[k]!=null&&!(Array.isArray(p[k])&&p[k].length===0)&&!(typeof p[k]==='object'&&!Array.isArray(p[k])&&Object.keys(p[k]).length===0))||p.map?.cells?.length||p.map?.tokens?.length)fail('PRIVATE_DATA','Private projection fields cannot enter the public feed.');
 const characters=(p.characters??[]).map(c=>{if(['ownerId','primaryHealth','primaryHealthMaximum','resources','scores','skills','sheet','position','conditions','currency'].some(k=>Object.hasOwn(c,k)))fail('PRIVATE_DATA','Private character fields cannot enter the public feed.');return {characterId:safe(c.characterId,100),displayName:safe(c.displayName,100),factionId:safe(c.factionId,40),classId:safe(c.classId,40)};}).slice(0,30);
 return {projectionVersion:2,campaignId:scope.campaignId,revision,audience:'public',characterId:'',currentSceneId:safe(p.currentSceneId,100),phase:safe(p.phase,40),characters,publicEvents:(p.publicEvents??[]).filter(e=>e.revision===revision).slice(-5).map(e=>({revision,text:safe(e.text),kind:safe(e.kind,40)}))};}
function messageTexts(components){return (components??[]).flatMap(c=>{const v=c.toJSON?.()??c;return v.type===10?[v.content]:messageTexts(v.components);});}
function expectedTexts(entry){return [`## Operation Hollow Lantern · ${entry.projection.phase==='combat'?'Combat':'Adventure'}`,safe(entry.projection.publicEvents.map(e=>e.text).join('\n')||'The public scene has been updated.',2600),`Revision ${entry.revision} · Record ${entry.fingerprint.slice(0,16)}`];}
/** Discord nonce is optional on fetched messages. Recovery requires it AND author/channel/content/attachment evidence.
 * Missing history is never reconstructed: a later public projection cannot stand in for an earlier revision.
 * afterRevision is an explicit installation baseline. acknowledgeGap is an explicit operator decision, not automatic catch-up.
 */
export async function createPublicFeed({path,campaignId,guildId,channelId,applicationId,afterRevision=0}={}){
 const scope={campaignId,guildId,channelId,applicationId};if(!path||Object.values(scope).some(v=>typeof v!=='string'||!v)||!Number.isSafeInteger(afterRevision)||afterRevision<0)throw new Error('Durable scoped public feed configuration required.');path=resolve(path);await mkdir(dirname(path),{recursive:true});const lockPath=path+'.lock',lockId=randomUUID();let lock;
 try{lock=await open(lockPath,'wx',0o600);}catch(e){if(e.code!=='EEXIST')throw e;let prior;try{prior=JSON.parse(await readFile(lockPath,'utf8'));process.kill(prior.pid,0);}catch(check){if(check.code!=='ESRCH')fail('FEED_LOCKED','The public feed is already open or its lock needs inspection.');if(await readFile(lockPath,'utf8')!==JSON.stringify(prior))fail('FEED_LOCKED','The feed lock changed.');await unlink(lockPath);lock=await open(lockPath,'wx',0o600);}if(!lock)fail('FEED_LOCKED','The public feed is already open.');}
 await lock.writeFile(JSON.stringify({pid:process.pid,id:lockId}));await lock.sync();
 let state={version:1,scope,cursor:afterRevision,entries:[],gaps:[]},lastBytes,failed=false,closed=false,tail=Promise.resolve();
 const encode=s=>{const payload=JSON.stringify(s);return JSON.stringify({checksum:hash(payload),payload});};
 function decode(raw){const e=JSON.parse(raw);if(hash(e.payload)!==e.checksum)throw new Error('checksum');const s=JSON.parse(e.payload);if(s.version!==1||JSON.stringify(s.scope)!==JSON.stringify(scope))fail('WRONG_FEED_SCOPE','Feed file belongs to another destination.');return s;}
 async function atomic(file,bytes){const temp=file+'.'+randomUUID()+'.tmp';const f=await open(temp,'wx',0o600);try{await f.writeFile(bytes);await f.sync();}finally{await f.close();}await rename(temp,file);}
 async function save(){try{const bytes=encode(state);if(lastBytes)await atomic(path+'.bak',lastBytes);await atomic(path,bytes);lastBytes=bytes;}catch(e){failed=true;throw e;}}
 try{try{const raw=await readFile(path,'utf8');state=decode(raw);lastBytes=raw;}catch(e){if(e.code==='WRONG_FEED_SCOPE')throw e;if(e.code!=='ENOENT'){const raw=await readFile(path+'.bak','utf8');state=decode(raw);lastBytes=raw;for(const item of state.entries)if(!['sent','suppressed'].includes(item.status))item.status='uncertain';state.recoveredBackup=true;await save();}}
  let changed=false;for(const item of state.entries)if(item.status==='sending'){item.status='uncertain';changed=true;}if(changed)await save();
 }catch(e){await lock.close();await unlink(lockPath);throw e;}
 function serial(fn){const operation=tail.then(()=>{if(closed||failed)fail('FEED_CLOSED','The feed is closed or a durable write failed. Reopen before continuing.');return fn();});tail=operation.catch(()=>{});return operation;}
 function inspect(){return {scope:{...scope},cursor:state.cursor,gaps:structuredClone(state.gaps),entries:state.entries.map(e=>({revision:e.revision,status:e.status,messageId:e.messageId??null,nonce:e.nonce})),missingRevision:state.entries.some(e=>e.revision>state.cursor+1)&&!state.entries.some(e=>e.revision===state.cursor+1)?state.cursor+1:null};}
 function bind(channel){if(channel?.id!==scope.channelId||(channel.guildId??channel.guild?.id)!==scope.guildId||channel.client?.application?.id!==scope.applicationId||!channel.client?.user?.id||typeof channel.send!=='function')fail('WRONG_CHANNEL','The Discord client and channel must match the persisted feed scope.');return channel.client.user.id;}
 async function record({receipt,projection}){return serial(async()=>{if(receipt?.contract!=='rpg-core-runtime-bridge-v1'||receipt.success!==true||receipt.campaignId!==scope.campaignId||!Number.isSafeInteger(receipt.revision)||receipt.revision<=0||typeof receipt.commandId!=='string')fail('INVALID_RECEIPT','A successful authoritative campaign receipt is required.');const p=sanitize(projection,scope,receipt.revision),fingerprint=hash(JSON.stringify(p)),commandHash=hash(receipt.commandId),existing=state.entries.find(e=>e.revision===receipt.revision);if(existing){if(existing.fingerprint!==fingerprint||existing.commandHash!==commandHash)fail('REVISION_COLLISION','A different public record already occupies this revision.');return {duplicate:true,status:existing.status};}if(receipt.revision<=state.cursor)fail('PAST_REVISION','This revision precedes the feed baseline or acknowledged gap.');state.entries.push({revision:receipt.revision,projection:p,fingerprint,commandHash,nonce:hash(JSON.stringify(scope)+receipt.commandId+receipt.revision).slice(0,24),status:'pending'});state.entries.sort((a,b)=>a.revision-b.revision);await save();return {duplicate:false,status:'pending'};});}
 async function flush({channel,render}){return serial(async()=>{const authorId=bind(channel);if(typeof render!=='function')throw new Error('Approved public image renderer required.');for(;;){const e=state.entries.find(x=>x.revision===state.cursor+1);if(!e||e.status!=='pending')break;
 const previous=state.entries.find(x=>x.revision===state.cursor);
 // Suppression still consumes the exact durable revision. It never skips an
 // uncertain send or infers a scene across an acknowledged missing interval.
 if(e.projection.publicEvents.length===0&&(state.cursor===0||previous?.projection.currentSceneId===e.projection.currentSceneId)){
  e.status='suppressed';e.suppressionReason='no-public-event-or-scene-change';state.cursor=e.revision;await save();continue;
 }
 const image=await render(structuredClone(e.projection));if(!Buffer.isBuffer(image)||image.length>8*1024*1024||image.length<8||!image.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))fail('INVALID_ART','Renderer must return a bounded approved public PNG.');e.attachmentName=`public-r${e.revision}-${hash(image).slice(0,16)}.png`;e.authorId=authorId;e.status='sending';await save();const texts=expectedTexts(e),payload={flags:32768,allowedMentions:{parse:[]},nonce:e.nonce,enforceNonce:true,components:[{type:17,accent_color:0xd8ac55,components:[{type:10,content:texts[0]},{type:12,items:[{media:{url:`attachment://${e.attachmentName}`},description:'Public adventure illustration'}]},{type:10,content:texts[1]},{type:14,divider:true,spacing:1},{type:10,content:texts[2]}]}],files:[{attachment:image,name:e.attachmentName}]};let message;try{message=await channel.send(payload);}catch(error){e.status='uncertain';await save();return {...inspect(),blocked:'uncertain-send'};}if(!message?.id){e.status='uncertain';await save();return {...inspect(),blocked:'uncertain-send'};}e.messageId=message.id;e.status='sent';state.cursor=e.revision;await save();}return inspect();});}
 async function recover({channel,revision}){return serial(async()=>{const authorId=bind(channel),e=state.entries.find(x=>x.revision===revision);if(!e||e.status!=='uncertain')fail('NOT_UNCERTAIN','Choose an uncertain public record.');if(e.authorId!==authorId)fail('WRONG_AUTHOR','Recovery requires the original bot identity.');const recent=await channel.messages.fetch({limit:100});const matches=[...recent.values()].filter(m=>String(m.nonce??'')===e.nonce&&m.author?.id===authorId&&(m.channelId??m.channel_id)===scope.channelId&&!m.webhookId&&!m.webhook_id&&JSON.stringify(messageTexts(m.components))===JSON.stringify(expectedTexts(e))&&[...(m.attachments?.values?.()??m.attachments??[])].some(a=>(a.name??a.filename)===e.attachmentName));if(matches.length!==1)return {...inspect(),recovered:false,reason:'No unique message with matching nonce, author, channel, content and attachment was returned. No send was retried.'};e.messageId=matches[0].id;e.status='sent';if(e.revision===state.cursor+1)state.cursor=e.revision;await save();return {...inspect(),recovered:true};});}
 async function acknowledgeGap({throughRevision,reason}){return serial(async()=>{if(!Number.isSafeInteger(throughRevision)||throughRevision<=state.cursor||typeof reason!=='string'||!reason.trim()||state.entries.some(e=>e.revision>state.cursor&&e.revision<=throughRevision))fail('INVALID_GAP','Only an absent revision interval can be explicitly acknowledged.');state.gaps.push({from:state.cursor+1,to:throughRevision,reason:safe(reason,500)});state.cursor=throughRevision;await save();return inspect();});}
 return Object.freeze({record,flush,recover,acknowledgeGap,status:()=>serial(async()=>inspect()),async close(){await tail;closed=true;await lock.close();const current=JSON.parse(await readFile(lockPath,'utf8'));if(current.id===lockId)await unlink(lockPath);}});
}
