import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm,mkdir,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash,createHmac} from 'node:crypto';
import {inspectStartup} from './startup-status.mjs';

async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'hollow startup '));t.after(()=>rm(dir,{recursive:true,force:true}));
 const env={HOLLOW_LANTERN_CAMPAIGN_ID:'fixture',HOLLOW_LANTERN_CHANNEL_ID:'1546676505780944979',HOLLOW_LANTERN_GUILD_ID:'1463393482306486387',HOLLOW_LANTERN_GM_ID:'1230264975533281312',HOLLOW_LANTERN_STORE_FILE:join(dir,'campaign.json'),HOLLOW_LANTERN_SECRET_FILE:join(dir,'bridge.secret'),HOLLOW_LANTERN_ACTIVITY_DATA_DIR:join(dir,'new-auth-dir'),HOLLOW_LANTERN_ENGINE_URL:'http://127.0.0.1:18810',DISCORD_CLIENT_ID:'1540006061099188274',DISCORD_CLIENT_SECRET:'fixture-oauth-secret',DISCORD_TOKEN:'fixture-bot-token'};
 const state={version:2,campaignId:'fixture',channelId:env.HOLLOW_LANTERN_CHANNEL_ID,gmId:env.HOLLOW_LANTERN_GM_ID,revision:7,actors:[]};
 const save=async s=>{const body=JSON.stringify(s);await writeFile(env.HOLLOW_LANTERN_STORE_FILE,JSON.stringify({body,sha256:createHash('sha256').update(body).digest('hex')}));};
 await save(state);await writeFile(env.HOLLOW_LANTERN_SECRET_FILE,'a'.repeat(64));
 const calls=[];const fetchImpl=async(url,options)=>{calls.push({url,options});const body=JSON.parse(options.body);assert.equal(body.audience,'public');assert.equal(body.mapLevel,'regional');assert.equal(body.ownerId,env.HOLLOW_LANTERN_GM_ID);assert.equal(body.characterId,'');assert.equal(options.headers['x-rpg-core-signature'],createHmac('sha256','a'.repeat(64)).update(`${options.headers['x-rpg-core-timestamp']}.${options.body}`).digest('hex'));return Response.json({contract:'rpg-core-runtime-bridge-v1',campaignId:'fixture',revision:8,projection:{projectionVersion:2,campaignId:'fixture',revision:8,audience:'public',map:{privateFixture:'must-not-leave-helper'}}});};
 return {dir,env,state,save,calls,fetchImpl};
}
test('signed public read succeeds across concurrent revision change and outputs only status',async t=>{const f=await fixture(t),before=await readFile(f.env.HOLLOW_LANTERN_STORE_FILE);const r=await inspectStartup(f);assert.equal(r.status,'ready');assert.equal(r.revision,8);assert.equal(f.calls.length,1);assert.ok(f.calls[0].url.endsWith('/api/rpg/projection'));assert.deepEqual(await readFile(f.env.HOLLOW_LANTERN_STORE_FILE),before);const text=JSON.stringify(r);for(const value of [f.dir,'fixture-oauth-secret','fixture-bot-token','a'.repeat(64),'privateFixture'])assert.ok(!text.includes(value));});
test('credential files use the same whitespace handling as the actual Activity runtime',async t=>{const f=await fixture(t);await writeFile(f.env.HOLLOW_LANTERN_SECRET_FILE,'a'.repeat(64)+'\r\n');assert.equal((await inspectStartup(f)).status,'ready');});
test('a save without a membership roster cannot make the app ready',async t=>{const f=await fixture(t);const state={...f.state};delete state.actors;await f.save(state);assert.equal((await inspectStartup(f)).status,'blocked');assert.equal(f.calls.length,0);});
test('corrupt, wrong version and wrong campaign saves block before engine read',async t=>{const f=await fixture(t);for(const changes of [{version:1},{campaignId:'wrong'},{channelId:'wrong'},{gmId:'wrong'},{revision:-1}]){await f.save({...f.state,...changes});assert.equal((await inspectStartup(f)).status,'blocked');}await writeFile(f.env.HOLLOW_LANTERN_STORE_FILE,'{"body":"{}","sha256":"wrong"}');assert.equal((await inspectStartup(f)).status,'blocked');await rm(f.env.HOLLOW_LANTERN_STORE_FILE);assert.equal((await inspectStartup(f)).status,'blocked');assert.equal(f.calls.length,0);});
test('engine failure and private responses fail closed and redact errors',async t=>{const f=await fixture(t);for(const fetchImpl of [async()=>{throw Error('private-provider-path');},async()=>Response.json({error:'private'}, {status:503}),async()=>Response.json({contract:'rpg-core-runtime-bridge-v1',campaignId:'fixture',revision:8,projection:{projectionVersion:2,campaignId:'fixture',revision:8,audience:'private'}})]){const r=await inspectStartup({...f,fetchImpl});assert.equal(r.status,'blocked');assert.ok(!JSON.stringify(r).includes('private-provider-path'));}});
test('invalid secrets and localhost/path URLs cannot reach engine',async t=>{const f=await fixture(t);for(const url of ['http://localhost:18810','http://127.0.0.1:18810/path','https://127.0.0.1:18810','http://127.0.0.1:18810/?x=1'])assert.equal((await inspectStartup({...f,env:{...f.env,HOLLOW_LANTERN_ENGINE_URL:url}})).status,'blocked');await writeFile(f.env.HOLLOW_LANTERN_SECRET_FILE,'NOT-A-SECRET');assert.equal((await inspectStartup(f)).status,'blocked');assert.equal(f.calls.length,0);});
test('auth configuration is not claimed as OAuth validation; malformed origin blocks',async t=>{const f=await fixture(t);let r=await inspectStartup(f);assert.match(r.checks.find(c=>c.id==='auth').message,/not verified/);r=await inspectStartup({...f,env:{...f.env,RAPHAEL_PUBLIC_ORIGIN:'https://user:password@example.test'}});assert.equal(r.status,'blocked');assert.ok(!JSON.stringify(r).includes('password'));});
test('OneDrive and linked protected files are rejected',async t=>{const f=await fixture(t);assert.equal((await inspectStartup({...f,env:{...f.env,HOLLOW_LANTERN_ACTIVITY_DATA_DIR:join(f.dir,'OneDrive','auth')}})).status,'blocked');const outside=join(f.dir,'other');await mkdir(outside);const link=join(f.dir,'linked');try{await symlink(outside,link,'junction');}catch(error){if(['EPERM','EACCES'].includes(error.code)){t.skip('Link creation unavailable');return;}throw error;}assert.equal((await inspectStartup({...f,env:{...f.env,HOLLOW_LANTERN_ACTIVITY_DATA_DIR:link}})).status,'blocked');});
