import test from 'node:test';import assert from 'node:assert/strict';
import {pendingKey,persistBeforeSend,clearConfirmed,clearRejected} from './action-session.mjs';
import * as sessions from './action-session.mjs';
const resolution=(kind='cancelled')=>({contract:'rpg-core-runtime-bridge-v1',campaignId:p.campaignId,commandId:p.commandId,ownerId:'player',actorId:p.actor,originalExpectedRevision:p.expectedRevision,revision:4,success:true,replayed:kind==='committed',resolution:kind,...(kind==='committed'?{receipt:{...receipt,replayed:true,result:{message:'Original result'}}}:{rejection:{contract:'rpg-core-runtime-bridge-v1',campaignId:p.campaignId,commandId:p.commandId,ownerId:'player',actorId:p.actor,originalExpectedRevision:p.expectedRevision,revision:4,code:'COMMAND_CANCELLED',terminal:true}})});
test('explicit terminal resolution clears only matching committed or cancelled recovery',()=>{for(const kind of ['committed','cancelled']){const s=storage();persistBeforeSend(s,p);assert.deepEqual(sessions.clearResolved(s,p,resolution(kind)),resolution(kind));assert.equal(s.getItem(pendingKey),null);}});
test('uncertain and mismatched resolution proofs retain the saved action',()=>{
 const common=[v=>v.campaignId='other',v=>v.commandId='other',v=>v.actorId='other',v=>v.ownerId='',v=>v.originalExpectedRevision=2,v=>v.success=false,v=>delete v.replayed,v=>v.revision=Number.MAX_SAFE_INTEGER+1,v=>v.resolution='missing',v=>v.extra=true];
 for(const kind of ['committed','cancelled'])for(const mutate of common){const s=storage();persistBeforeSend(s,p);const value=resolution(kind);mutate(value);assert.throws(()=>sessions.clearResolved(s,p,value));assert.deepEqual(JSON.parse(s.getItem(pendingKey)),p);}
 for(const mutate of [v=>v.rejection.ownerId='other',v=>v.rejection.actorId='other',v=>v.rejection.campaignId='other',v=>v.rejection.commandId='other',v=>v.rejection.originalExpectedRevision=2,v=>v.rejection.revision=5,v=>v.rejection.terminal=false,v=>v.rejection.code='RECEIPT_NOT_FOUND',v=>v.rejection.extra=true,v=>v.receipt={},v=>v.revision=3]){const s=storage();persistBeforeSend(s,p);const value=resolution();mutate(value);assert.throws(()=>sessions.clearResolved(s,p,value));assert.notEqual(s.getItem(pendingKey),null);}
 for(const mutate of [v=>v.receipt.success=false,v=>v.receipt.replayed=false,v=>v.receipt.campaignId='other',v=>v.receipt.commandId='other',v=>v.receipt.revision=5,v=>v.receipt.result=null,v=>v.rejection={}]){const s=storage();persistBeforeSend(s,p);const value=resolution('committed');mutate(value);assert.throws(()=>sessions.clearResolved(s,p,value));assert.notEqual(s.getItem(pendingKey),null);}
 for(const value of [null,{},undefined]){const s=storage();persistBeforeSend(s,p);assert.throws(()=>sessions.clearResolved(s,p,value));assert.notEqual(s.getItem(pendingKey),null);}
});
test('terminal response cannot clear a replacement record or hide a storage failure',()=>{const s=storage(),other={...p,campaignId:'other-campaign'};persistBeforeSend(s,other);assert.throws(()=>sessions.clearResolved(s,p,resolution()));assert.deepEqual(JSON.parse(s.getItem(pendingKey)),other);persistBeforeSend(s,p);assert.throws(()=>sessions.clearResolved({...s,removeItem(){throw Error('storage unavailable');}},p,resolution()),/storage unavailable/);assert.notEqual(s.getItem(pendingKey),null);});
const p={commandId:'12345678-1234-1234-1234-123456789abc',campaignId:'operation-hollow-lantern',actor:'lantern-fighter',level:'tactical',expectedRevision:3};
const receipt={contract:'rpg-core-runtime-bridge-v1',campaignId:p.campaignId,commandId:p.commandId,success:true,revision:4};
function storage(){const values=new Map();return {setItem:(k,v)=>values.set(k,v),getItem:k=>values.get(k)??null,removeItem:k=>values.delete(k)};}
test('durable pending identity is stored before a request can be sent',()=>{const s=storage();persistBeforeSend(s,p);assert.deepEqual(JSON.parse(s.getItem(pendingKey)),p);assert.throws(()=>persistBeforeSend({setItem(){throw Error('quota');}},p),/quota/);});
test('wrong, malformed and unsuccessful receipts never clear recovery',()=>{const s=storage();persistBeforeSend(s,p);for(const r of [null,{}, {...receipt,success:false},{...receipt,revision:3},{...receipt,commandId:'other'},{...receipt,campaignId:'other'}]){assert.throws(()=>clearConfirmed(s,p,r));assert.notEqual(s.getItem(pendingKey),null);}clearConfirmed(s,p,receipt);assert.equal(s.getItem(pendingKey),null);});
test('a replaced recovery record is never removed by an older response',()=>{const s=storage();persistBeforeSend(s,p);const other={...p,actor:'lantern-rogue'};persistBeforeSend(s,other);assert.throws(()=>clearConfirmed(s,p,receipt));assert.deepEqual(JSON.parse(s.getItem(pendingKey)),other);});

test('only exact matching attested rejection clears pending; uncertainty and copied identities remain',()=>{
 const s=storage(),r={contract:'hollow-action-rejection-v1',campaignId:p.campaignId,commandId:p.commandId,actorId:p.actor,expectedRevision:p.expectedRevision,submitted:false};persistBeforeSend(s,p);
 for(const bad of [undefined,{}, {...r,submitted:true},{...r,commandId:'other'},{...r,actorId:'other'},{...r,campaignId:'other'},{...r,expectedRevision:0}]){assert.throws(()=>clearRejected(s,p,bad));assert.notEqual(s.getItem(pendingKey),null);}
 clearRejected(s,p,r);assert.equal(s.getItem(pendingKey),null);persistBeforeSend(s,{...p,actor:'other'});assert.throws(()=>clearRejected(s,p,r));assert.notEqual(s.getItem(pendingKey),null);
});
