import test from 'node:test';
import assert from 'node:assert/strict';
import { curate } from './curate.mjs';
const record = (id, group = id) => ({ id, campaignGroup: group, review: { approved: true, privacyChecked: true, reviewerId: 'fixture-reviewer' }, rights: { kind: 'original', evidence: 'Authored test fixture' }, visibility: 'player_safe', purpose: 'narration', containsHiddenState: false, sourceEventIds: ['event-1'], messages: [{ role: 'user', content: 'Describe the visible bridge.' }, { role: 'assistant', content: `A lantern illuminates the worn bridge. Scene ${id}.` }] });
test('campaigns cannot leak across splits and output strips review metadata', () => { const data = [record('a', 'party-a'), record('b', 'party-a'), record('c', 'party-b')]; const result = curate(data); const groupSplits = new Map(); for (const p of result.manifest.provenance) { if (groupSplits.has(p.group)) assert.equal(groupSplits.get(p.group), p.split); groupSplits.set(p.group, p.split); } assert.ok(result.train.length); assert.ok(result.evaluation.length); assert.deepEqual(Object.keys(result.train[0]), ['messages']); assert.deepEqual(curate(data), result); });
test('reject unreviewed, secret, mechanics and unlicensed records', () => { for (const patch of [{ review: { approved: false } }, { visibility: 'gm_only' }, { containsHiddenState: true }, { purpose: 'dice_resolution' }, { rights: { kind: 'unknown' } }]) assert.throws(() => curate([{ ...record('a'), ...patch }, record('b')])); });
test('obvious credentials are rejected without echoing content', () => { const r = record('a'); r.messages[1].content = 'api_key=do-not-print-this'; assert.throws(() => curate([r, record('b')]), error => !error.message.includes('do-not-print-this') && error.message.includes('credential')); });
test('duplicates and one-campaign splits fail', () => { const a = record('a'), b = record('b'); b.messages = a.messages; assert.throws(() => curate([a, b]), /duplicate training/); assert.throws(() => curate([record('a', 'one'), record('b', 'one')]), /independent campaign/); });
test('DPO maintains prompt/completion shape and rejects identical preferences', () => { const pref = id => ({ ...record(id), prompt: [{ role: 'user', content: `What is visible ${id}?` }], chosen: [{ role: 'assistant', content: 'A lit bridge.' }], rejected: [{ role: 'assistant', content: 'The bridge is visible. The bridge is visible.' }] }); const a = pref('a'), b = pref('b'); const result = curate([a, b], { method: 'dpo' }); assert.deepEqual(Object.keys(result.train[0]), ['prompt', 'chosen', 'rejected']); a.rejected = a.chosen; assert.throws(() => curate([a, b], { method: 'dpo' }), /must differ/); });
