"""Measured R01 illustration: local SD materials, deterministic architectural geometry.
Run with portable Blender --background --python this_file. Units below are feet.
The door/prop placements are authored illustration coordinates, not campaign discoveries.
"""
import bpy, math, json, random, bmesh
from pathlib import Path
from mathutils import Vector, Matrix
from bpy_extras.object_utils import world_to_camera_view
random.seed(419031)
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'art'/'architecture'
OUT.mkdir(parents=True,exist_ok=True)
F=.3048
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
scene=bpy.context.scene
scene.render.engine='CYCLES';scene.cycles.samples=48;scene.cycles.use_denoising=True
try:
 prefs=bpy.context.preferences.addons['cycles'].preferences;prefs.compute_device_type='CUDA';prefs.get_devices()
 gpu=[d for d in prefs.devices if d.type=='CUDA']
 if gpu:
  for d in prefs.devices:d.use=d.type=='CUDA'
  scene.cycles.device='GPU'
 print('RENDER_DEVICE',scene.cycles.device)
except Exception as error:print('RENDER_DEVICE CPU',type(error).__name__)
scene.render.resolution_x=1600;scene.render.resolution_y=1200;scene.render.resolution_percentage=100
scene.render.image_settings.file_format='PNG'
scene.world.color=(.14,.18,.2)
scene.view_settings.view_transform='AgX'

# Shared material images are generated by the neighboring local-SD script.
def material(name,color,metal=0,rough=.7,image=None):
 m=bpy.data.materials.new(name);m.use_nodes=True
 n=m.node_tree.nodes;bs=n.get('Principled BSDF');bs.inputs['Base Color'].default_value=(*color,1);bs.inputs['Metallic'].default_value=metal;bs.inputs['Roughness'].default_value=rough
 if image:
  tex=n.new('ShaderNodeTexImage');tex.image=bpy.data.images.load(str(OUT/image),check_existing=True);tex.projection='BOX';tex.projection_blend=.2
  coord=n.new('ShaderNodeTexCoord');m.node_tree.links.new(coord.outputs['Generated'],tex.inputs['Vector'])
  if metal:
   mix=n.new('ShaderNodeMixRGB');mix.blend_type='MULTIPLY';mix.inputs[0].default_value=.28;mix.inputs[1].default_value=(*color,1)
   m.node_tree.links.new(tex.outputs['Color'],mix.inputs[2]);m.node_tree.links.new(mix.outputs[0],bs.inputs['Base Color'])
  else:m.node_tree.links.new(tex.outputs['Color'],bs.inputs['Base Color'])
 noise=n.new('ShaderNodeTexNoise');noise.inputs['Scale'].default_value=85;noise.inputs['Detail'].default_value=3
 bump=n.new('ShaderNodeBump');bump.inputs['Strength'].default_value=.17;bump.inputs['Distance'].default_value=.018
 m.node_tree.links.new(noise.outputs['Fac'],bump.inputs['Height']);m.node_tree.links.new(bump.outputs['Normal'],bs.inputs['Normal'])
 return m
stone=material('Salt-weathered limestone · local Stable Diffusion',(.48,.48,.4),image='harbor-limestone.png')
brass=material('Tidal brass · local Stable Diffusion',(.45,.28,.09),.72,.44,image='tidal-brass.png')
slate=material('Deep tidal slate',(.055,.095,.10),0,.85)
wood=material('Old oak',(.12,.07,.035),0,.76)
paper=material('Unlettered service sheets',(.63,.58,.40),0,.93)
cloth=material('Oiled umbrella canvas',(.025,.065,.055),0,.86)
iron=material('Dark iron',(.045,.057,.055),.65,.4)
water=material('Damp worn stone',(.07,.11,.105),.05,.26)

def finish(obj,name,mat):
 obj.name=name;obj.data.materials.append(mat);return obj

def box(name,pos,size,mat=stone,bevel=.035):
 bpy.ops.mesh.primitive_cube_add(size=1,location=tuple(v*F for v in pos));o=bpy.context.object;o.dimensions=tuple(v*F for v in size)
 bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
 finish(o,name,mat)
 if bevel:
  mod=o.modifiers.new('Soft worn edges','BEVEL');mod.width=bevel*F;mod.segments=3
  o.modifiers.new('Weighted normals','WEIGHTED_NORMAL')
 return o

def cylinder(name,pos,radius,depth,mat=brass,rot=(0,0,0),vertices=32):
 bpy.ops.mesh.primitive_cylinder_add(vertices=vertices,radius=radius*F,depth=depth*F,location=tuple(v*F for v in pos),rotation=rot)
 o=finish(bpy.context.object,name,mat);mod=o.modifiers.new('Machined edge','BEVEL');mod.width=.025*F;mod.segments=3
 for p in o.data.polygons:p.use_smooth=True
 return o

def tube(name,points,radius=.055,mat=brass):
 curve=bpy.data.curves.new(name,'CURVE');curve.dimensions='3D';curve.resolution_u=12;curve.bevel_depth=radius*F;curve.bevel_resolution=3
 spline=curve.splines.new('POLY');spline.points.add(len(points)-1)
 for p,v in zip(spline.points,points):p.co=(*(c*F for c in v),1)
 obj=bpy.data.objects.new(name,curve);scene.collection.objects.link(obj);obj.data.materials.append(mat);return obj

def sphere(name,pos,scale,mat):
 bpy.ops.mesh.primitive_uv_sphere_add(segments=24,ring_count=12,location=tuple(v*F for v in pos));o=finish(bpy.context.object,name,mat);o.scale=tuple(v*F for v in scale)
 for p in o.data.polygons:p.use_smooth=True
 return o

box('Foundation',(9,6,-.35),(18.5,12.5,.65),slate,.12)
# 1.5-foot flags; the internal footprint is exactly 18 by 12 feet.
for x in range(12):
 for y in range(8):
  box('Individual limestone flag',(.75+x*1.5,.75+y*1.5,-.03),(1.46,1.46,.17),stone,.045)
  if (x*13+y*7)%17==0:tube('Fine worn joint',[(x*1.5+.2,y*1.5+.4,.065),(x*1.5+.65,y*1.5+.65,.066),(x*1.5+1.1,y*1.5+.55,.067)],.009,slate)
# Full north and west walls. The east and south walls are removed above the sill for the cutaway.
for course in range(10):
 z=.5+course
 for k in range(9):
  box('North ashlar', (1+k*2,12.28,z),(1.97,.55,.96),stone,.055)
 for k in range(6):
  y=1+k*2
  if 4<y<8 and z<8:continue
  box('West ashlar',(-.28,y,z),(.55,1.97,.96),stone,.055)
for x in [0,6,12,18]:
 box('North pilaster',(x,11.92,5),(.48,.46,10),stone,.04)
 box('North capital',(x,11.86,9.65),(.8,.7,.35),stone,.04)
box('North coping',(9,12.25,10.06),(18.6,.72,.25),stone,.04)
box('West coping',(-.28,6,10.06),(.72,12.6,.25),stone,.04)
box('East cutaway sill',(18.2,6,.2),(.4,12,.4),stone,.04)
for x,w in [(1.4,2.8),(12.1,11.8)]:box('South cutaway sill',(x,-.2,.2),(w,.4,.4),stone,.04)
# Main door towards the machinery: visible brass, chair-shaped dent and hand wheel.
box('Brass main door',(-.05,6,3.85),(.20,3.6,7.7),brass,.045)
for y in [4.25,7.75]:box('Door jamb',(.12,y,4),(.35,.25,8),brass,.035)
box('Door lintel',(.12,6,8.1),(.35,3.8,.35),brass,.035)
for y in [4.45,7.55]:
 for z in [1,2,3,4,5,6,7]:cylinder('Door rivet',(.09,y,z),.055,.07,iron,(0,math.pi/2,0),16)
for z in [1.3,6.5]:cylinder('Door hinge',(.3,4.5,z),.12,.55,brass)
tube('Chair-shaped dent',[(.071,5.4,1),(.072,5.4,3),(.074,6.45,3),(.072,6.45,1)],.028,slate)
tube('Chair seat dent',[(.075,5.4,2),(.075,6.45,2)],.03,slate)
cylinder('Door wheel hub',(.25,7,4),.16,.3,iron,(0,math.pi/2,0))
bpy.ops.mesh.primitive_torus_add(major_radius=.40*F,minor_radius=.045*F,location=(.43*F,7*F,4*F),rotation=(0,math.pi/2,0));finish(bpy.context.object,'Brass hand wheel',brass)
for angle in [0,math.pi/2,math.pi,math.pi*1.5]:tube('Wheel spoke',[(.43,7,4),(.43,7+math.cos(angle)*.4,4+math.sin(angle)*.4)],.027,brass)
# Visible low service hatch along the east wall.
box('Service hatch frame',(18.02,9,1.3),(.16,2.2,2.6),brass,.035)
box('Service hatch face',(17.9,9,1.3),(.12,1.85,2.25),iron,.035)
for y in [8.35,8.65,8.95,9.25,9.55]:box('Service ventilation slat',(17.8,y,1.5),(.08,.08,1.4),brass,.018)
# Public roster. The generated architecture contains no secret text or check answers.
box('Roster oak frame',(8.4,11.74,5.5),(3.2,.18,3.8),wood,.04)
for x in [7.5,8.45,9.35]:
 for z in [4.7,6.25]:
  box('Public service sheet',(x,11.625,z),(.8,.025,1.3),paper,.005)
  cylinder('Roster pin',(x,11.59,z+.5),.03,.03,brass,(math.pi/2,0,0),12)
  for line in range(5):box('Roster unlettered line',(x,11.606,z+.25-line*.15),(.5,.006,.012),slate,0)
# Speaking tube and conduit: mouthpiece visibly faces the room.
tube('Speaking tube rising conduit',[(3,11.7,4.8),(3,11.7,8.8),(3.5,11.7,9.2),(10.7,11.7,9.2),(11.3,11.7,8.6),(11.3,11.7,1)],.09,brass)
for z in [2,4,6,8]:box('Conduit bracket',(11.3,11.83,z),(.45,.23,.1),iron,.012)
bpy.ops.mesh.primitive_cone_add(vertices=40,radius1=.3*F,radius2=.1*F,depth=.45*F,location=(3*F,11.43*F,4.8*F),rotation=(math.pi/2,0,0));finish(bpy.context.object,'Speaking tube mouthpiece',brass)
cylinder('Mouthpiece dark opening',(3,11.20,4.8),.25,.018,slate,(math.pi/2,0,0))
# Umbrella stand near the offset entrance, four furled umbrellas, worn mat.
cylinder('Umbrella stand',(1.3,2, .78),.46,1.55,brass)
cylinder('Umbrella stand dark interior',(1.3,2,1.56),.4,.025,slate)
for k in range(4):
 x=1.3+math.cos(k*1.7)*.21;y=2+math.sin(k*1.7)*.21
 cylinder('Furled umbrella',(x,y,2.02),.11,2.3,cloth)
 tube('Umbrella hooked handle',[(x,y,3.12),(x,y,3.4),(x+.08,y,3.52),(x+.22,y,3.52),(x+.3,y,3.42),(x+.3,y,3.29)],.045,wood)
box('Boot wiping mat',(4.65,1,.1),(3.1,1.65,.06),cloth,.035)
for i in range(15):tube('Woven mat stitch',[(3.2+i*.2,.28,.138),(3.2+i*.2,1.72,.138)],.008,wood)
for x,y in [(3.1,2.2),(4.4,3.1),(5.2,2.4)]:sphere('Subtle damp boot mark',(x,y,.059),(.13,.27,.004),water)
# Lighting is real scene illumination, with warm glass in the wall sconces.
glass=material('Warm lantern glass',(.65,.25,.05),.1,.3)
bs=glass.node_tree.nodes.get('Principled BSDF');bs.inputs['Emission Color'].default_value=(1,.43,.12,1);bs.inputs['Emission Strength'].default_value=2
for x in [1,14.7]:
 box('Sconce bracket',(x,11.5,6.2),(.22,.65,.16),iron,.025)
 cylinder('Lantern base',(x,11.22,6.4),.25,.16,brass)
 cylinder('Lantern glass',(x,11.22,6.85),.20,.78,glass)
 cylinder('Lantern cap',(x,11.22,7.3),.27,.17,brass)
 for a in [0,math.pi/2,math.pi,3*math.pi/2]:cylinder('Lantern cage',(x+math.cos(a)*.21,11.22+math.sin(a)*.21,6.85),.025,.85,iron,vertices=12)
 light=bpy.data.lights.new('Warm maintenance lamp','POINT');light.energy=48;light.color=(1,.62,.27);light.shadow_soft_size=.3
 obj=bpy.data.objects.new(light.name,light);scene.collection.objects.link(obj);obj.location=(x*F,10.9*F,6.85*F)
def area(name,pos,energy,color,size):
 l=bpy.data.lights.new(name,'AREA');l.energy=energy;l.color=color;l.shape='DISK';l.size=size
 o=bpy.data.objects.new(name,l);scene.collection.objects.link(o);o.location=tuple(v*F for v in pos);o.rotation_euler=(Vector((9*F,6*F,1*F))-o.location).to_track_quat('-Z','Y').to_euler()
area('Cool coastal fill',(10,-8,20),750,(.67,.82,1),7)
area('Soft ceiling bounce',(7,7,20),420,(1,.84,.62),5)
# Neutral studio ground deliberately does not invent adjacent undiscovered rooms.
box('Presentation ground',(9,6,-.82),(200,200,.2),slate,0)
camdata=bpy.data.cameras.new('Architectural camera');cam=bpy.data.objects.new('Architectural camera',camdata);scene.collection.objects.link(cam);scene.camera=cam;camdata.type='ORTHO';camdata.lens=50
views={}
def render(name,pos,target,scale):
 cam.location=tuple(v*F for v in pos);cam.rotation_euler=(Vector(tuple(v*F for v in target))-cam.location).to_track_quat('-Z','Y').to_euler();camdata.ortho_scale=scale*F
 scene.render.filepath=str(OUT/(name+'.png'))
 def project(x,y,z):
  p=world_to_camera_view(scene,cam,Vector((x*F,y*F,z*F)));return [round(p.x*1600,4),round((1-p.y)*1200,4)]
 bpy.context.view_layer.update()
 views[name]={'width':1600,'height':1200,'origin':project(0,0,0),'xAxis':project(18,0,0),'yAxis':project(0,12,0),'zAxis':project(0,0,10)}
 bpy.ops.render.render(write_still=True)
render('r01-cutaway',(29,-30,28),(8,6,3),33)
# Preserve the complete shared geometry before creating the horizontal section.
model_dir=Path.home()/'Projects'/'Unwritten-Coast-Data'/'architecture';model_dir.mkdir(parents=True,exist_ok=True)
bpy.ops.wm.save_as_mainfile(filepath=str(model_dir/'r01-brass-vestibule.blend'))
bpy.ops.object.select_all(action='DESELECT')
# Exact four-foot section through the same geometry; no independent AI floor plan.
for obj in list(scene.objects):
 if obj.type not in {'MESH','CURVE'} or obj.name=='Presentation ground':continue
 bpy.context.view_layer.objects.active=obj;obj.select_set(True)
 if obj.type=='CURVE':bpy.ops.object.convert(target='MESH')
 deps=bpy.context.evaluated_depsgraph_get();mesh=bpy.data.meshes.new_from_object(obj.evaluated_get(deps))
 mesh.transform(obj.matrix_world);obj.modifiers.clear();obj.data=mesh;obj.matrix_world=Matrix.Identity(4)
 bm=bmesh.new();bm.from_mesh(mesh)
 result=bmesh.ops.bisect_plane(bm,geom=list(bm.verts)+list(bm.edges)+list(bm.faces),dist=.00001,plane_co=(0,0,4*F),plane_no=(0,0,1),clear_outer=True)
 edges=[e for e in result['geom_cut'] if isinstance(e,bmesh.types.BMEdge)]
 if edges:bmesh.ops.holes_fill(bm,edges=edges,sides=0)
 bm.to_mesh(mesh);bm.free();obj.select_set(False)
render('r01-floor-slice',(9,6,40),(9,6,0),27)
render('r01-low-cutaway',(29,-30,28),(8,6,1),30)
metadata={'roomId':'R01','name':'Brass Vestibule','dimensionsFeet':{'width':18,'depth':12,'height':10},'horizontalSectionFeet':4,'views':views,'features':[{'id':'umbrella-stand','name':'Umbrella stand','x':1.3/18,'y':2/12,'z':0},{'id':'R01-a','name':'Public service roster','x':8.4/18,'y':11.7/12,'z':5.5/10},{'id':'R01-b','name':'Speaking tube','x':3/18,'y':11.3/12,'z':4.8/10}], 'limits':['Door and furnishing placements are authored illustration coordinates, pending merge with the tactical catalog.','No player discoveries, secret mechanisms or check results are asserted.','Full room is one occupied floor; the four-foot slice is an architectural cut, not a second story.'],'generator':'Blender 4.5.9 Cycles; local Stable Diffusion surface images; deterministic measured geometry'}
(OUT/'r01-projection.json').write_text(json.dumps(metadata,indent=2),encoding='utf8')
print('R01_ARCHITECTURE_COMPLETE')
