import{esc,roomMap,roomScene,atlasMap,roomIndex,worldMap,sceneOverlay}from'/render.mjs';
const $=id=>document.getElementById(id);let snapshot=null,playerSnapshot=null,roomId=null,areaId=null,view='scene',floor='all',busy=false,zoom=1;
const current=()=>snapshot?.catalog.rooms.find(r=>r.id===roomId);
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
async function json(url,options){const response=await fetch(url,options);let data;try{data=await response.json();}catch{throw new Error('The atlas returned an unreadable response. Refresh to reconnect.');}if(!response.ok)throw new Error(data.error||data.message||'The atlas could not complete that action.');return data;}
async function refresh(silent=false){if(busy)return;try{const next=await json('/api/state');if(silent&&snapshot&&next.state.revision===snapshot.state.revision)return;snapshot=next;playerSnapshot=next.audience==='gm'?await json('/api/player-state'):next;roomId=snapshot.catalog.rooms.some(r=>r.id===roomId)?roomId:snapshot.state.currentRoomId||snapshot.catalog.rooms[0]?.id;areaId=current()?.areaId||snapshot.catalog.areas[0]?.id;render();if(!silent)status('Atlas loaded. Discovery changes are saved on this table.');}catch(e){status(e.message,true);}}
async function act(action){if(snapshot?.audience!=='gm'||busy)return;busy=true;status('Recording the discovery…');try{snapshot=await json('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Capability':snapshot.capability},body:JSON.stringify(action)});playerSnapshot=await json('/api/player-state');render();const last=snapshot.state.history?.at(-1);status(last?.summary||last?.publicText||last?.text||'Recorded. The player atlas now reflects this decision.');}catch(e){status(e.message,true);}finally{busy=false;}}
function fillSelect(id,items,value){$(id).replaceChildren(...items.map(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;return o;}));if(items.some(p=>String(p[0])===String(value)))$(id).value=value;}
function roomLabel(r){return `${r.id} · ${r.name}`;}
function render(){
 const gm=snapshot.audience==='gm',r=current(),catalog=snapshot.catalog,state=snapshot.state;
 $('audience').textContent=gm?'GM atlas · complete record':'Player atlas · discoveries only';$('boundary').textContent=gm?'The complete atlas stays at this table. Reveal discoveries deliberately.':'Every place and object here has been seen or learned about.';
 $('gmPanel').hidden=!gm;$('travelPanel').hidden=!gm||view!=='world';$('playerLink').hidden=!gm;$('playerLink').href=`http://${location.hostname}:51941/`;
 $('downloadMap').textContent=gm?'Download GM map PNG':'Download map PNG';
 fillSelect('area',catalog.areas.map(a=>[a.id,a.name]),areaId);renderRoomList();
 if(!r){$('roomTitle').textContent='The atlas is still unwritten';$('view').innerHTML='<div class="emptyMap"><h3>A first discovery awaits</h3><p>The GM can record a place when the company sees it or learns about it.</p></div>';return;}
 $('roomTitle').textContent=view==='world'?'The known coast':view==='dungeon'||view==='diagram'||(view==='town'||view==='towntactical')?catalog.areas.find(a=>a.id===areaId)?.name||r.name:r.name;
 $('roomMeta').textContent=view==='world'?`${catalog.places.length} places in this atlas`:view==='dungeon'||view==='diagram'||(view==='town'||view==='towntactical')?`${catalog.rooms.filter(x=>x.areaId===areaId).length} mapped spaces · ${gm?'complete GM view':'known locations only'}`:`${r.id} · ${r.floor} · ${r.width} × ${r.depth} ft · ${gm&&r.hidden?'concealed until discovered':state.roomIds[r.id]?.visited?'visited':state.roomIds[r.id]?'learned or revealed':'GM preparation'}`;
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
 const floors=[...new Set(catalog.rooms.filter(x=>x.areaId===areaId).map(x=>x.floor))];fillSelect('floor',[['all','All layers'],...floors.map(f=>[f,f])],floor);if(!floors.map(String).includes(String(floor)))floor='all';
 $('floorControl').hidden=!['dungeon','diagram','town','towntactical'].includes(view);$('angleControl').hidden=!['dungeon','town'].includes(view);$('gridControl').hidden=view!=='tactical';$('fit').hidden=view==='scene';
 renderMap();$('flavor').textContent=r.flavor;$('visibleFeatures').replaceChildren(...(r.visibleFeatures||[]).map(s=>{const li=document.createElement('li');li.textContent=s;return li;}));
 $('poiList').innerHTML=(r.pois||[]).map((p,i)=>`<div class="poi"><button data-poi="${esc(p.id)}" aria-label="Inspect ${esc(p.name)}">${i+1}</button><div><strong>${esc(p.name)}${gm&&p.hidden?' · hidden':''}</strong><p>${esc(p.description)}</p><small>${esc(p.interaction||'Describe how you examine it to the GM.')}</small></div></div>`).join('')||'<p class="quiet">No points of interest have been recorded here yet. Describe what you examine to the GM.</p>';
 const exits=catalog.links.filter(e=>e.from===r.id||e.to===r.id).map(e=>({...e,room:catalog.rooms.find(a=>a.id===(e.from===r.id?e.to:e.from))})).filter(e=>e.room);
 $('exits').innerHTML=`<h3>Connected spaces</h3><div class="exits">${exits.map(e=>`<button data-room="${esc(e.room.id)}">${esc(e.room.name)}${gm&&e.hidden?' · concealed':''}</button>`).join('')||'<span class="quiet">No connecting room has been recorded.</span>'}</div>`;
 $('partyList').innerHTML=state.party.map((p,i)=>`<p><span class="dot" style="background:${esc(p.color)}">${i+1}</span><span><b>${esc(p.name)}</b><br>${esc(catalog.rooms.find(x=>x.id===p.roomId)?.name||'Position not disclosed')}</span></p>`).join('');
 $('journal').innerHTML=(state.history||[]).slice(-15).reverse().map(e=>`<li>${esc(e.summary||e.publicText||e.text||e.description||e.type||'Discovery recorded')}</li>`).join('')||'<li>No new discoveries have been recorded at this table.</li>';
 if(gm){fillSelect('checkPoi',(r.pois||[]).map(p=>[p.id,p.name]),$('checkPoi').value);fillSelect('marker',state.party.map(p=>[p.id,p.name]),$('marker').value);fillSelect('learnPlace',catalog.places.map(p=>[p.id,p.name]),$('learnPlace').value);fillSelect('road',catalog.roads.map(p=>[p.id,p.name||p.description||p.id]),$('road').value);$('gmNotes').textContent=r.gmNotes||'';renderCheck();renderRoad();}
 renderEmbed();
}
function renderRoomList(){if(!snapshot)return;const query=$('roomSearch').value.toLowerCase();const rooms=snapshot.catalog.rooms.filter(r=>r.areaId===areaId&&`${r.id} ${r.name}`.toLowerCase().includes(query));$('roomList').innerHTML=rooms.map(r=>`<button data-room="${esc(r.id)}" aria-pressed="${r.id===roomId}">${esc(r.name)}<small>${esc(r.id)} · ${esc(r.floor)}</small></button>`).join('')||'<p class="quiet">No visible rooms match that search.</p>';}
function svgFor(r=current(),data=snapshot){if(view==='world')return worldMap(data.catalog,data.state);if(view==='tactical')return roomMap(r,data.state.party,{grid:$('grid').checked});if(view==='scene')return roomScene(r,data.state.party);if(view==='diagram')return roomIndex(data.catalog,data.state.party,{areaId,floor});return atlasMap(data.catalog,data.state.party,{areaId,iso:!['diagram','towntactical'].includes(view),grid:view==='towntactical',floor,angle:Number($('angle').value)});}
function renderMap(){const r=current();if(!r)return;zoom=1;$('view').dataset.layout=view;$('sceneText').hidden=!['scene','tactical'].includes(view);if(view==='scene'){
 $('view').innerHTML=`<img class="sceneArt" src="/art/room/${encodeURIComponent(r.id)}.png" alt="${esc(r.name)} — visible room atmosphere"><div class="fallbackPlan" hidden>${roomScene(r,snapshot.state.party)}</div>${sceneOverlay(r)}<span class="mapLegend">${snapshot.audience==='gm'?'GM scene · includes concealed POI markers':'Discovered points of interest'} · numbered locations are approximate</span>`;
 const image=$('view').querySelector('img');image.addEventListener('error',()=>{image.hidden=true;$('view').querySelector('.fallbackPlan').hidden=false;$('view').querySelector('.artOverlay').hidden=true;});
 }else $('view').innerHTML=svgFor();}
function renderCheck(){const p=current()?.pois.find(p=>p.id===$('checkPoi').value);$('checkHint').textContent=p?`${p.skill||'Interaction'}${Number.isFinite(p.dc)?` · DC ${p.dc}`:''}. ${p.interaction||''}`:'Select a point of interest.';}
function renderRoad(){const road=snapshot.catalog.roads.find(r=>r.id===$('road').value);const known=Boolean(road&&snapshot.state.roadIds[road.id]);const base=Math.max(0,Math.min(100,Number($('baseChance').value)||0));$('roadHint').textContent=road?`${known?'Known road':'Unknown road'} · ${known?'1×':'2×'} base chance = ${Math.min(100,base*(known?1:2))}% per journey leg. ${road.description||''}`:'No roads are available.';}
function playerRoom(){return playerSnapshot?.catalog.rooms.find(r=>r.id===roomId);}
function compact(r){return `## ${r.name}\n> ${r.flavor}\n\n**You can see**\n${(r.visibleFeatures||[]).slice(0,3).map(x=>`• ${x}`).join('\n')}\n\n**What do you do?**\n${(r.pois||[]).slice(0,2).map(p=>`• ${p.interaction||`Examine ${p.name}.`}`).join('\n')||'Describe where you go or what you examine.'}\n\n-# Only recorded discoveries are shown. Maps and numbered pins accompany this scene.`;}
function renderEmbed(){const r=playerRoom();$('discordSendPanel').hidden=snapshot.audience!=='gm';$('webhookSetup').hidden=Boolean(snapshot.discord?.configured);$('discordConnection').textContent=snapshot.discord?.configured?'Channel connected. Posting uses only this room’s revealed player information.':'Connect this channel’s webhook to send real embeds with the scene image.';$('sendDiscord').disabled=!r||!snapshot.discord?.configured;for(const id of['downloadCard','downloadEmbed','copyPost'])$(id).disabled=!r;$('embedPreview').innerHTML=r?`<h3>${esc(r.name)}</h3><p><em>${esc(r.flavor)}</em></p><h4>You can see</h4>${(r.visibleFeatures||[]).slice(0,3).map(x=>`<p>• ${esc(x)}</p>`).join('')}<h4>What do you do?</h4>${(r.pois||[]).slice(0,2).map(p=>`<p>• ${esc(p.interaction||`Examine ${p.name}.`)}</p>`).join('')||'<p>Describe where you go or what you examine.</p>'}<img class="embedImage" alt="${esc(r.name)} scene artwork" src="/art/room/${encodeURIComponent(r.id)}.png"><small>Player view · revealed information only</small>`:'<p>This room is not in the player atlas. Record its discovery before making a Discord card.</p>';const img=$('embedPreview').querySelector('img');if(img)img.addEventListener('error',()=>img.hidden=true);}
function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src;});}
async function svgImage(svg){const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{return await loadImage(url);}finally{URL.revokeObjectURL(url);}}
function wrap(ctx,value,x,y,width,lineHeight){const words=String(value).split(/\s+/);let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>width&&line){ctx.fillText(line,x,y);line=word;y+=lineHeight;}else line=test;}if(line)ctx.fillText(line,x,y);return y+lineHeight;}
async function saveMap(){const r=current();if(!r)return;const data=snapshot,mode=view,title=$('roomTitle').textContent,chosenArea=areaId,chosenFloor=floor;try{let svg=svgFor(r,data);if(mode==='diagram'){const artData={};const rooms=data.catalog.rooms.filter(x=>x.areaId===chosenArea&&(chosenFloor==='all'||String(x.floor)===String(chosenFloor)));await Promise.all(rooms.map(async room=>{const img=await loadImage(`/art/room/${encodeURIComponent(room.id)}.png`),small=document.createElement('canvas');small.width=400;small.height=260;small.getContext('2d').drawImage(img,0,0,400,260);artData[room.id]=small.toDataURL('image/png');}));svg=roomIndex(data.catalog,data.state.party,{areaId:chosenArea,floor:chosenFloor,artData});}const box=svg.match(/viewBox="[^\"]*?([\d.]+) ([\d.]+)"/)?.slice(1).map(Number)||[1000,650];const mapHeight=Math.round(1600*box[1]/box[0]),image=await svgImage(svg),c=document.createElement('canvas');c.width=1600;c.height=mapHeight+95;const ctx=c.getContext('2d');ctx.fillStyle='#182b30';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(image,0,55,1600,mapHeight);ctx.fillStyle='#efe3c3';ctx.font='24px Georgia';ctx.fillText(`${data.audience==='gm'?'PRIVATE GM MAP':'PLAYER MAP'} · ${title}`,34,36);ctx.font='18px Segoe UI';ctx.fillText(data.state.party.map((p,i)=>`${i+1} ${p.name}`).join('  ·  '),34,c.height-16);c.toBlob(blob=>download(blob,`${data.audience}-${r.id}-${mode}.png`));status('Map exported with its artwork and audience label.');}catch(error){console.error('Map export failed',error);status('The map image could not be exported. Refresh the atlas and try again.',true);}}
async function saveCard(){const r=playerRoom();if(!r)return;try{let image;try{image=await loadImage(`/art/room/${encodeURIComponent(r.id)}.png`);}catch{image=await svgImage(roomScene(r,playerSnapshot.state.party));}const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=1350;const c=canvas.getContext('2d');c.fillStyle='#2b2d31';c.fillRect(0,0,1400,1350);c.drawImage(image,0,0,1400,790);const overlay=await svgImage(sceneOverlay(r).replace('class="artOverlay"','').replace('viewBox="0 0 1000 650"','width="1000" height="650" viewBox="0 0 1000 650"'));c.drawImage(overlay,0,0,1400,790);c.fillStyle='#e6c990';c.font='46px Georgia';c.fillText(r.name,58,866);c.fillStyle='#ededed';c.font='italic 27px Georgia';let y=wrap(c,r.flavor,58,918,1280,38)+15;c.fillStyle='#ffffff';c.font='bold 23px Segoe UI';c.fillText('YOU CAN SEE',58,y);y+=35;c.font='24px Segoe UI';for(const f of(r.visibleFeatures||[]).slice(0,3))y=wrap(c,`• ${f}`,58,y,1260,32)+7;c.fillStyle='#c3cbce';c.font='19px Segoe UI';c.fillText('The Unwritten Coast · Player discoveries · Numbered pins are approximate',58,1310);canvas.toBlob(blob=>download(blob,`${r.id}-scene.png`));status('Player scene card downloaded, ready to attach to its Discord embed.');}catch{status('The scene card could not be exported. Try refreshing the room artwork.',true);}}
$('area').addEventListener('change',()=>{areaId=$('area').value;roomId=snapshot.catalog.rooms.find(r=>r.areaId===areaId)?.id;floor='all';render();});$('roomSearch').addEventListener('input',renderRoomList);
document.addEventListener('click',event=>{const room=event.target.closest('[data-room]');if(room){roomId=room.dataset.room;areaId=current().areaId;if(['dungeon','diagram','town','towntactical','world'].includes(view))view='scene';render();return;}const tab=event.target.closest('[data-view]');if(tab){view=tab.dataset.view;if((view==='town'||view==='towntactical')){const a=snapshot.catalog.areas.find(a=>a.kind==='town');if(a){areaId=a.id;roomId=snapshot.catalog.rooms.find(r=>r.areaId===areaId)?.id;}}render();return;}const poi=event.target.closest('[data-poi]');if(poi){const p=current()?.pois.find(p=>p.id===poi.dataset.poi);if(p){status(`${p.name}: ${p.interaction||p.description}`);if(snapshot.audience==='gm'){$('checkPoi').value=p.id;renderCheck();}}return;}const place=event.target.closest('[data-place]');if(place){const p=snapshot.catalog.places.find(p=>p.id===place.dataset.place);status(p?.description||'Place recorded.');if(p?.roomId&&snapshot.catalog.rooms.some(r=>r.id===p.roomId)){roomId=p.roomId;areaId=current().areaId;view='scene';render();}}});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('svg [tabindex]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
$('floor').addEventListener('change',()=>{floor=$('floor').value;renderMap();});$('angle').addEventListener('input',renderMap);$('grid').addEventListener('change',renderMap);$('refresh').addEventListener('click',()=>refresh());$('fit').addEventListener('click',renderMap);
$('view').addEventListener('wheel',event=>{if(['scene','diagram'].includes(view))return;event.preventDefault();zoom=Math.max(1,Math.min(4,zoom+(event.deltaY<0?.15:-.15)));const svg=$('view').querySelector('svg');if(svg){const x=500-500/zoom,y=325-325/zoom;svg.setAttribute('viewBox',`${x} ${y} ${1000/zoom} ${650/zoom}`);}},{passive:false});
$('visit').addEventListener('click',()=>act({type:'visitRoom',roomId}));$('reveal').addEventListener('click',()=>act({type:'revealRoom',roomId,reason:$('revealReason').value}));$('learn').addEventListener('click',()=>act({type:'learnPlace',placeId:$('learnPlace').value,reason:$('revealReason').value}));$('checkPoi').addEventListener('change',renderCheck);$('resolve').addEventListener('click',()=>act({type:'discoverPoi',roomId,poiId:$('checkPoi').value,interaction:$('interaction').value,checkTotal:Number($('checkTotal').value)}));$('move').addEventListener('click',()=>act({type:'moveMarker',markerId:$('marker').value,roomId,x:Number($('markerX').value)/100,y:Number($('markerY').value)/100}));$('learnRoad').addEventListener('click',()=>act({type:'learnRoad',roadId:$('road').value,reason:$('roadSource').value}));$('road').addEventListener('change',renderRoad);$('baseChance').addEventListener('input',renderRoad);$('travel').addEventListener('click',()=>act({type:'travelRoad',roadId:$('road').value,baseChance:Number($('baseChance').value)}));
$('downloadMap').addEventListener('click',saveMap);$('downloadCard').addEventListener('click',saveCard);$('downloadEmbed').addEventListener('click',async()=>{try{const payload=await json(`/api/discord?room=${encodeURIComponent(roomId)}`);download(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`${roomId}-discord-embed.json`);status('Player-safe embed payload downloaded. Attach its matching scene PNG when sending.');}catch(e){status(e.message,true);}});$('copyPost').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(compact(playerRoom()));status('Compact player post copied.');}catch{status('Clipboard access was unavailable. Use the scene card or embed download.',true);}});
const deliveryKeys=new Map();
$('connectDiscord').addEventListener('click',async()=>{const secret=$('webhookUrl').value.trim();if(!secret){status('Paste the channel webhook address first.',true);return;}$('connectDiscord').disabled=true;try{await json('/api/discord/connect',{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Capability':snapshot.capability},body:JSON.stringify({webhookUrl:secret})});$('webhookUrl').value='';await refresh();status('Discord channel connected. Review the player card before posting.');}catch(e){$('webhookUrl').value='';status(e.message,true);}finally{$('connectDiscord').disabled=false;}});
$('sendDiscord').addEventListener('click',async()=>{if(!playerRoom()||!snapshot.discord?.configured)return;const threadId=$('discordThread').value,key=`${threadId}:${roomId}`;if(!deliveryKeys.has(key))deliveryKeys.set(key,crypto.randomUUID());$('sendDiscord').disabled=true;$('deliveryResult').textContent='Sending the player scene card…';try{const result=await json('/api/discord/send',{method:'POST',headers:{'Content-Type':'application/json','X-Atlas-Capability':snapshot.capability},body:JSON.stringify({roomId,threadId,idempotencyKey:deliveryKeys.get(key)})});$('deliveryResult').replaceChildren();const a=document.createElement('a');a.href=result.link;a.target='_blank';a.rel='noopener';a.textContent='View the scene embed in Discord';$('deliveryResult').append('Posted. ',a);status('Player scene embed posted to Discord.');}catch(e){$('deliveryResult').textContent=e.message+' Check the Discord thread before retrying; this operation keeps the same request key.';status('Discord delivery needs review.',true);}finally{$('sendDiscord').disabled=false;}});
await refresh();setInterval(()=>{if(!document.hidden)refresh(true);},5000);
