import caretakerGeometry from './art/architecture/r05-projection.json' with {type:'json'};
// Authored starting content. No actual campaign discoveries or outcomes are asserted.
const p=(id,name,description,interaction,skill='Investigation',dc=11,revealsRoomId)=>({id,name,x:.3,y:.4,description,interaction,skill,dc,hidden:false,...(revealsRoomId?{revealsRoomId}:{})});
const rows=[
['R01','Brass Vestibule',0,'workshop',300,0,18,12,10,'A sign asks visitors to wipe their boots before entering the storm machinery. The brass door bears a chair-shaped dent.','An offset doorway admits visitors to a public maintenance lobby.',['Umbrella stand','Public service roster','Speaking tube'],'Compare roster annotations to identify the next staffed shift; normal reading is automatic.','Listen through the tube to identify the direction of the caretaker’s bell.','Valid permit, Wren credential or agreed escort works. Main R04 route and service hatch are visible; forgery scrutiny only on actual inspection.'],
['R02','Valve Throat',0,'workshop',340,0,4,6,5,'Warm pipes press close beneath a low stone ceiling. A worn inspection plate catches the lantern light; beyond it, a small hatch and its red-handled lever wait in the narrow space.','Optional cramped service shortcut.',['Immense pipes','Maintenance inscription','Reachable hatch lever'],'Inspect lever travel to hold the hatch for a tool; ordinary operation is automatic.','Trace the visible cable to identify which mechanism powers the lift.','Apply actual squeezing rules. No required clue, key or unique treasure.'],
['R03','Counterweight Well',-1,'shaft',0,0,12,12,160,'A brass platform hangs above a square darkness. Its counterweight rises without a sound.','A 160-foot vertical service shaft with intact lift and protected stair.',['Railed lift platform','Load plate','Protected stair'],'Read the plate to plan a balanced equipment load.','Trace the insulated cable to identify the feed shared with R08.','Normal lift use automatic, two minutes; stair alternative. State fall risk before climbing outside rails. Main R01–R04 route remains. Height means depth.'],
['R04','Choir of Pipes',-1,'workshop',50,0,240,90,60,'Footsteps return as a chord from pipes larger than cottages. A low whistle seems to answer between the columns.','Long nave with staggered columns and labeled isolation controls.',['Pipe columns','Three labeled valves','Printed control diagram'],'Compare vibration before and after operation to diagnose the feed; reading labels and using valves are automatic.','Listen from two positions to separate air resonance from the R05 maintenance bell.','Valves isolate observation loop, catwalk feed and dock pumps. Catwalk isolation removes hazard; observation control stops press moving lanes. Whistle is resonance, not secret NPC.'],
['R05','Caretaker’s Flat',-1,'home',50,130,11,17,8,'A mended rug barely fits between a bunk and two mugs. The back window looks onto an indoor harbor.','An irregular domestic L within the bounding rectangle.',['Bunk and mended rug','Kettle and two mugs','Visitor directions note'],'Compare the schedule to identify a quiet dock inspection period.','Ask a patient specific question to learn which dock repair should be tackled first.','Jori Hale maintains refuge and feeds dock cat; wants safe way home, no secret authority or complete Rook knowledge. Ordinary directions automatic or supplied by note.'],
['R06','Sleeping Drydock',-1,'dock',0,250,1200,420,160,'Lights outline a hundred-foot rescue vessel beyond the balcony. Then its smallness within the basin becomes clear.','Stepped basin with balcony, scaffold pier, vessel deck and gate controls.',['Mercy of the Tide rescue vessel','Scaffold pier','Marked water-gate controls'],'Survey the hull to assemble its repair list and identify forty-passenger capacity.','Compare gate seals with the safe-tide plan to identify the inspection sequence.','Real vessel. Full day repairs, willing qualified crew, pump activation and gate inspection earn 40 passengers; two boarding lanes use 40-minute loading. Chart/pilot/landing/shelter still required. Separate 80×60 water gate leads R15 basin and surveyed culvert, six hours safe opening including inspection, overlaps repairs. Disclose flood risk; personnel causeway distinct.'],
['R07','Reflection Gallery',-1,'archive',340,0,80,20,12,'Machinery moves in the mirrored ceiling while the floor stays still. Lantern light returns from an unexpectedly distant angle.','Bent optical gallery giving safe views of the presses.',['Adjustable mirrors','Viewpoint diagrams','Linked plate and paper copy'],'Wave a lantern and align its reflection to locate the real viewing angle.','Compare display timing to measure lag; the changing plate and unchanged paper are obvious on inspection.','Reflected worker exists only if technician actually present. Mirror destruction does not remove all evidence.'],
['R08','Insulated Catwalk',-1,'bridge',340,80,180,15,70,'A railed bridge stretches above a humming channel. A bright indicator shines from the closed maintenance hatch.','Intact fifteen-foot deck seventy feet over the channel.',['Continuous railings','Closed maintenance hatch','Labeled local disconnect'],'Compare indicator and hum to confirm isolation; using labeled disconnect is automatic.','After isolation, inspect insulation to locate the worn sleeve.','Height 70 is channel-relative elevation, not ceiling. Normal crossing safe. Touching exposed live feed after warning: DC13 Dexterity save 2d6 lightning/half. Sentinel only same unresolved adventure-7 encounter.'],
['R09','Room of Almost-Rain',-1,'garden',570,0,60,60,40,'Droplets stop six inches above the stone. A boot sends rings of light across their trembling surface.','Circular condenser chamber, sixty feet across.',['Suspended droplets','Ordinary drain handle','Reference gauge'],'Take repeated readings to record a stable calibration reference.','Test a sample to identify ordinary water suspended by a local field.','Safe experiment. Drain turns field off automatically; no effect on people, time or gravity. Gauge can replace one adventure-7 reading.'],
['R10','Giant’s Teacup',-2,'workshop',0,0,140,140,70,'A tiny painted flower decorates the rim of an enormous bowl. Real porcelain cups wait below on a lunch table.','Circular terraced bowl with broad ramp and working platform lift.',['Terraces and ramp','Marked spare-part racks','Porcelain cups on lunch table'],'Inventory sleeves, braces and seals to select one major repair package.','Plan a balanced lift load for the largest brace; normal lift use is automatic.','70 ft bowl depth. One major repair package initially, record ownership and use. Supports Mossmere repair or temporary mast; transport remains required, no infinite refill.'],
['R11','Pocket Refuge',-1,'home',680,0,9,9,7,'The dry room smells of wool and biscuits. After the great bowl, its low ceiling feels companionable.','Small refuge with dry landing outside for overflow.',['Bench and blanket chest','Biscuit tin and water','First-aid box and paper copies'],'Inventory the kit to identify clean dressings for ordinary treatment.','Cross-reference dates to identify the newest maintenance procedure.','Mundane supplies, normal rests/healing, no automatic HP. No secret encounter timer; real time and forecast proceed.'],
['R12','Map-Press Hall',-1,'archive',1300,0,300,180,45,'Presses stamp blue coastlines onto long paper sheets. Wet blank spaces interrupt places where names should be.','Sawtooth factory floor with three broad safe staff lanes.',['Long map presses','Three marked safe lanes','Dated survey register'],'Cross-reference safe records to pinpoint earliest matching command; basic engine/map connection is automatic.','Study run-down timing to estimate safe sheet removal; emergency stop operation is automatic.','Paired copies, queue and diversion register independently connect map changes to engine commands. Active roller rush DC13 Dexterity; failure blocks progress and damages unsecured paper/gear before further voluntary hazard. Press stop not engine shutdown.'],
['R13','Dead-Letter Room',-1,'archive',1650,0,20,25,9,'Returned mail leans against five sloping shelves. A birthday parcel bears the stamp “destination unrecognized.”','Five-sided sorting office beside the plainly visible blue-door corridor.',['Five sloping shelves','Birthday parcel','Labeled service drawer'],'Sort routing marks to group voluntary delivery errands.','Compare filing dates to identify the current service chart; opening and reading are automatic.','Addresses support Bellwether. Use established NPCs or ordinary residents, never unapproved PC secrets/dead relatives. R17 crossing chart here; duplicate Observatory.'],
['R14','Crown Control Gallery',-1,'beacon',1650,100,90,40,25,'Tall glass curves around a crescent of gauges. Five beacon positions occupy the human-sized control table.','Control gallery with isolation, calibration, bypass and evacuation-before-shutdown documents.',['Crescent gauge bank','Five-position control table','Operational sequence documents'],'Compare a recorded condenser reference to identify calibration drift.','Annotate a crew handover plan to catch one timing conflict.','Lights follow actual campaign state. Trained routine operation with time succeeds; adventure uncertainty only when warranted. Credentials, negotiated handover, Wren access or established unauthorized route work. No optional-room key needed.'],
['R15','Storm-Lens Cavern',-2,'cavern',300,0,1600,900,220,'Distant maintenance lights make a district-sized darkness legible. Rain strikes the lens overhead and pours into immense channels.','Kidney-shaped engineered cavern with west causeway, island, spillways and eastern landing.',['Personnel causeway','Maintenance island','Lens-fed spillway channels'],'Compare flow gauges to identify an uneven distribution load.','Test sightlines to establish a reliable crew lantern relay.','Bounding extents, not rectangle. Marked walk 1800 ft, about fifteen careful minutes; urgent movement actual. Boats require established routes. Basins uninhabited, no sacrificed town. Actual prepared crews/lifts/feeds/boats matter; no compulsory distant attacks.'],
['R16','Exit Tower',-2,'shaft',1980,0,24,24,180,'Daylight descends through a hexagonal tower. A bell rope climbs from landing to landing.','Hexagonal shaft, 24 feet across flats, with lift and protected stair.',['Hexagonal landings','Lift and protected stair','Bell rope'],'Use the load plate to plan passenger and equipment relays.','Distinguish the returning signal from harbor noise to establish a clear code.','Three-minute lift to waterfront signal tower, normal use automatic. 180 ft vertical travel. Schematic surface approach grade reconciles proposed overview elevation; not a surveyed profile.'],
['R17','Unmarked Blue Door',-1,'archive',1780,0,8,13,10,'An unmarked blue door opens onto a small balcony chamber. A narrow survey beam crosses the far threshold.','Small maintenance chamber with a visibly unusual threshold.',['Blue-painted door','Small balcony','Posted window notice'],'Compare beam and instrument readings to recognize crossing alignment; GM adjudicates requirements.','Compare posted timing marks with a current service chart.','GM ONLY: balcony overlooks ordinary Bellwether street from impossible direction. Stillwater crossing uses established dawn/dusk one-hour window, route chart and instrument. No unlimited instant travel. Chart R13/Observatory. Six-foot approach and balcony slow bulk evacuation; inspect/agree capacity. Signs state next window and Bellwether schoolhouse refuge. No traversable Stillwater atlas link.'],
['R18','Beacon Heart',-2,'beacon',1980,160,180,180,300,'Suspended rings turn around a column of light. At its base, controls remain deliberately within human reach.','Cylindrical machinery hall with three accessible platform stations.',['Isolation/distribution/return stations','Protected lifts and stairs','Suspended machinery rings'],'Rehearse crew signals to identify a missed acknowledgment.','Compare return and distribution readings to detect a mismatch.','Series-bible finale requirements apply. Actual state determines spectacle and ending; no forced solo lethality, blood sacrifice or character overwrite. R14 and R15 exits.']
];
const rooms=rows.map(([id,name,floor,kind,x,y,width,depth,height,flavor,description,visibleFeatures,a,b,gmNotes])=>({id,name,areaId:'undertow',floor,kind,x,y,z:floor===0?0:floor===-1?-160:-230,width,depth,height,flavor,description,visibleFeatures,pois:[p(id+'-a',visibleFeatures[1],`Examine ${visibleFeatures[1].toLowerCase()}.`,a),{...p(id+'-b',visibleFeatures[2],`Inspect ${visibleFeatures[2].toLowerCase()}.`,b,'Perception',12),x:.73,y:.65}],gmNotes}));
// Floor anchors measured from the saved 18 × 12 ft Blender room (southwest origin).
// Preserve POI identities and discovery state; all map styles share these positions.
rooms.find(r=>r.id==='R05').floorPlan={...caretakerGeometry.dimensionsFeet,polygonFeet:caretakerGeometry.floorPolygonFeet};
const vestibule=rooms.find(r=>r.id==='R01');
Object.assign(vestibule.pois[0],{x:8.4/18,y:11.74/12});
Object.assign(vestibule.pois[1],{x:3/18,y:11.43/12});
// These notes describe the result of the existing optional investigations.
// Player projection releases them only after the corresponding discovery.
const valve=rooms.find(r=>r.id==='R02');
valve.pois[0].interaction='The hatch can be held open with the lever while a tool is passed through. Ordinary operation does not require a check; the confined opening still limits what will fit.';
valve.pois[1].interaction='Tracing the visible cable identifies the feed serving the lift mechanism. It is a practical maintenance connection, not a separate passage.';
const add=(id,name,areaId,floor,kind,x,y,width,depth,height,flavor,description,visibleFeatures,a,b,reveal,hidden=false,entry=false)=>rooms.push({id,name,areaId,floor,kind,x,y,z:floor*10,width,depth,height,flavor,description,visibleFeatures,pois:[p(id+'-a',visibleFeatures[0],`Examine ${visibleFeatures[0].toLowerCase()}.`,a,'Investigation',12,reveal),{...p(id+'-b',visibleFeatures[2],`Inspect ${visibleFeatures[2].toLowerCase()}.`,b,'Perception',10),x:.72,y:.65}],gmNotes:'New authored proposal, not an actual discovery or campaign outcome. Ordinary entry and visible navigation require no check; optional successful checks add information.',...(hidden?{hidden:true}:{}),...(entry?{entry:true}:{})});
add('f-deck','Ferry Arrival Deck','brinewatch',0,'dock',0,0,70,24,12,'Salt gathers on the rail as Brinewatch comes into view. A gangplank settles against the waiting quay.','The party begins aboard a coastal ferry ready to disembark.',['Coiled mooring line','Lowered gangplank','Rope-wrapped rail'],'Inspect abraded fibers to identify a sharp harbor cleat and warn the deckhand.','Read the shoreline to identify the marked public way into town.',undefined,false,true);
add('f-hold','Ferry Cargo Hold','brinewatch',-1,'hold',0,0,50,20,9,'Lantern light rocks over lashed cargo. The timbers answer each small wave with a soft knock.','A working cargo hold beneath the arrival deck.',['Lashed crates','Hanging lantern','Cargo manifest board'],'Inspect a shifting sling to identify which knot needs retying.','Match labels to find an ordinary missing delivery receipt.');
const town=[
['t-tavern','The Salt Lantern','tavern',0,100,48,32,'Amber windows warm a rain-dark quay. Inside, spoons tap against thick bowls of chowder.','A public dockside dining room.',['Hearth-side repaired stone','Long dining tables','Chalk menu'],'Trace wear on the repaired stone and release its latch to reveal an optional cellar.','Compare menu revisions to identify the busiest arrival hour.','t-cellar'],
['t-workshop','Copperwake Repair Shop','workshop',90,100,36,28,'Copper filings shine beside an open toolbox. A half-mended pump ticks whenever the wind shifts.','A marine repair workshop.',['Disassembled pump','Tool bench','Hanging spare sleeves'],'Align the scored impeller sleeve to identify its needed replacement.','Compare tool wear to identify the most frequently repaired fitting.'],
['t-archive','Harbor Records House','archive',170,100,42,30,'Paper smells faintly of sea and dust. Brass weights keep the public ledgers flat.','A public records office.',['Slightly proud ledger shelf','Reading counter','Shelved tide books'],'Trace wear on the shelf runner and release it to reveal an optional survey annex.','Compare tide book dates to identify the latest correction.','t-survey'],
['t-chapel','Chapel of Returning Lights','chapel',260,100,55,35,'Glass lamps glow above worn stone benches. A bell vibrates softly in the sea wind.','A maritime chapel welcoming travelers.',['Glass lamp rack','Stone benches','Offering basin'],'Clean the lamp maker’s marks to identify a shared artisan.','Read scratches on the basin to identify where a missing lamp stand once sat.'],
['t-market','Netmakers’ Exchange','market',0,190,65,42,'Bright floats hang like a second sky. Hemp, apples and rain scent the covered stalls.','A covered local market.',['Public route board','Net-and-float stalls','Produce crates'],'Compare trail notes to identify a recently usable coast road.','Inspect crate stamps to trace an ordinary orchard delivery.'],
['t-home','Lantern Keeper’s House','home',110,190,28,24,'Clean boots wait beside a patched coat. The kitchen window faces the signal tower.','A modest local residence.',['Window-frame tally cuts','Kitchen table','Patched coat on peg'],'Read the tally spacing to infer an old watch rotation.','Compare salt wear on the coat to identify the exposed side of the harbor walk.'],
['t-beacon','Crown Beacon Maintenance House','beacon',200,190,40,30,'A brass lintel reflects the white sky. A sign behind the counter points down toward the Undertow Works.','The public maintenance approach to the existing Crown Beacon.',['Weatherproof equipment rack','Permit counter','Maintenance direction sign'],'Compare equipment wear to identify routine valve-service tools.','Follow the printed diagram to identify the main passenger route; ordinary directions are automatic.'],
['t-signal','Waterfront Signal Tower','beacon',290,190,24,24,'Flags snap above an open harbor window. A lift bell answers from beneath the floor.','A waterfront relay room above the ordinary dungeon exit.',['Numbered signal flags','Lift landing','Harbor-facing window'],'Reconstruct an old practice sequence to confirm crew acknowledgment.','Test a sightline to identify a reliable lantern relay position.']
];
for(const [id,n,k,x,y,w,d,f,de,v,a,b,r]of town)add(id,n,'brinewatch',0,k,x,y,w,d,12,f,de,v,a,b,r);
add('t-cellar','Salt Lantern Old Cellar','brinewatch',-1,'hold',90,100,22,18,8,'Cool air smells of oak and old cider. Empty racks form narrow aisles below the tavern.','Optional cellar revealed by the tavern latch.',['Cider inventory slate','Empty oak racks','Repaired stair stone'],'Compare faded figures to identify a forgotten ordinary cider cask.','Date the stair repair relative to the racks from its tool marks.',undefined,true);
add('t-survey','Private Survey Annex','brinewatch',0,'archive',170,40,20,16,10,'Dust lies beneath a covered drafting table. A narrow skylight falls across rolled survey sheets.','Optional annex behind harbor records shelves.',['Rolled coastal surveys','Covered drafting table','Brass drafting ruler'],'Compare landmarks to identify an optional local land-survey errand.','Align ruler and drafting marks to recover a missing scale; these are ordinary surveys, not Stillwater charts.',undefined,true);
const sites=[
['s-mossmere','Mossmere Road Shelter','home',0,0,32,22,'Reeds brush the shelter’s low eaves. A dry bench faces the road back to the coast.','An authored roadside shelter near Mossmere.',['Road milestone','Dry bench','Reed-thatched roof'],'Compare milestone and drainage to identify the drier return road.','Read weathering to identify the prevailing storm direction.'],
['s-observatory','Observatory Visitor Gallery','archive',100,0,48,28,'A brass horizon ring catches the pale sun. Footsteps soften on a runner between instrument cases.','An authored visitor gallery at the established Observatory.',['Public sky calendar','Instrument cases','Brass horizon ring'],'Compare calendar entries to identify a useful observation period.','Align the horizon ring to identify the coastal bearing.'],
['s-saltfen','Saltfen Boardwalk','garden',200,0,80,15,'Pale reeds bend over a silver pool. The boardwalk creaks above slow water.','An optional authored wetland stop.',['Tide-stained posts','Reed beds','Timber boardwalk'],'Read tide stains to identify the dry return interval.','Inspect board wear to identify the firmest standing position.'],
['s-wreck','Wreckglass Strand','dock',340,0,100,35,'Green glass glints among the shingle. A broken keel makes a dark rib against the surf.','An authored beach stop with a safe land approach.',['Broken wooden keel','Shingle beach','Scattered sea glass'],'Distinguish a maker’s mark from weather damage on the keel.','Compare glass edges to identify the older washed fragments.'],
['s-orchard','Windward Orchard','garden',480,0,70,50,'Low apple trees lean away from the sea. Cloth windbreaks rustle beside a stone path.','An authored inland orchard.',['Bent apple shoots','Cloth windbreaks','Stone path'],'Read bent shoots to identify a sheltered route through the orchard.','Inspect path repairs to identify the ordinary cart route.']
];
for(const[id,n,k,x,y,w,d,f,de,v,a,b]of sites)add(id,n,'coast',0,k,x,y,w,d,15,f,de,v,a,b);
const l=(from,to,kind,description,hidden=false)=>({id:from+'--'+to,from,to,kind,description,hidden});
const links=[l('f-deck','f-hold','stairs','Open cargo stairs.'),l('f-deck','t-tavern','hall','Gangplank and public quay.'),...town.slice(1).map(t=>l('t-tavern',t[0],'hall','Public town lane; authored schematic route.')),l('t-tavern','t-cellar','door','Hearth-side latch reveals cellar.',true),l('t-archive','t-survey','door','Shelf runner reveals survey annex.',true),l('t-beacon','R01','hall','30 ft, 8 ft wide public maintenance entry.'),l('R01','R04','stairs','60 ft corridor, 8 ft wide, plus 160 ft passenger lift/protected stair descent.'),l('R01','R02','door','Visible short service opening; actual size rules.'),l('R02','R03','door','Short service opening with reachable lever.'),l('R03','R04','stairs','160 ft service lift or protected stair.'),l('R04','R05','door','20 ft, 6 ft wide unlocked domestic route.'),l('R04','R07','hall','50 ft, 8 ft wide observation route.'),l('R04','R08','hall','40 ft, 10 ft wide technical route.'),l('R05','R06','hall','90 ft, 6 ft wide service ramp.'),l('R06','R10','stairs','150 ft, 15 ft wide descending ramp.'),l('R06','R15','hall','240 ft, 30 ft wide dry causeway, separate from water gate.'),l('R07','R09','hall','30 ft, 6 ft wide curved passage.'),l('R07','R12','hall','60 ft, 10 ft wide archive access.'),l('R08','R14','hall','40 ft, 10 ft wide control access.'),l('R09','R11','door','20 ft, 6 ft wide dry doorway.'),l('R10','R11','stairs','80 ft, 8 ft wide stair and chair/platform lift.'),l('R10','R15','hall','120 ft, 12 ft wide lower ramp.'),l('R11','R13','hall','50 ft, 6 ft wide sorting-office corridor.'),l('R12','R13','hall','20 ft, 8 ft wide staff passage.'),l('R12','R14','hall','70 ft, 10 ft wide official route.'),l('R13','R17','door','30 ft, 6 ft wide; blue door plainly visible.'),l('R14','R18','stairs','80 ft, 12 ft wide distribution access; schematic grade proposed.'),l('R15','R18','hall','200 ft, 20 ft wide engine-base route.'),l('R15','R16','hall','180 ft, 12 ft wide exit approach.'),l('R16','t-signal','stairs','180 ft vertical protected stair/lift; surface approach grade schematic.')];
for (const r of rooms) r.publicArtKey = r.id;
export const CATALOG={version:1,title:'The Unwritten Coast — Discovery Atlas',areas:[{id:'brinewatch',name:'Brinewatch',kind:'town',description:'Authored town and ferry interiors.'},{id:'undertow',name:'The Undertow Works',kind:'dungeon',description:'Eighteen canonical keyed rooms, dimension-faithful schematic.'},{id:'coast',name:'Coastal Roads',kind:'town',description:'Authored optional destinations.'}],rooms,links,places:[{id:'brinewatch',name:'Brinewatch',x:220,y:320,description:'The party’s harbor arrival.',roomId:'f-deck',knownAtStart:true},{id:'crown',name:'Crown Beacon',x:300,y:270,description:'Public beacon maintenance approach.',roomId:'t-beacon',knownAtStart:false},{id:'mossmere',name:'Mossmere Approach',x:480,y:210,description:'A reed-lined road shelter.',roomId:'s-mossmere',knownAtStart:false},{id:'observatory',name:'Observatory',x:170,y:90,description:'High-road instrument gallery.',roomId:'s-observatory',knownAtStart:false},{id:'saltfen',name:'Saltfen',x:540,y:380,description:'Boardwalk above tidal pools.',roomId:'s-saltfen',knownAtStart:false},{id:'wreckglass',name:'Wreckglass Strand',x:60,y:430,description:'Shingle and weathered timber.',roomId:'s-wreck',knownAtStart:false},{id:'orchard',name:'Windward Orchard',x:410,y:60,description:'Low trees behind cloth screens.',roomId:'s-orchard',knownAtStart:false}],roads:[{id:'road-crown',from:'brinewatch',to:'crown',unknown:false,description:'A signed lane climbs toward the beacon.'},{id:'road-mossmere',from:'brinewatch',to:'mossmere',unknown:false,description:'A signed inland road follows drainage ditches.'},{id:'road-observatory',from:'crown',to:'observatory',unknown:false,description:'A survey road climbs the ridge.'},{id:'road-saltfen',from:'brinewatch',to:'saltfen',unknown:true,description:'An unmarked plank path bends behind reeds; travel reveals its destination.'},{id:'road-wreck',from:'brinewatch',to:'wreckglass',unknown:true,description:'A shingle track vanishes around a headland; destination unknown.'},{id:'road-orchard',from:'mossmere',to:'orchard',unknown:true,description:'An unsigned fork turns behind a hill; destination unknown.'},{id:'road-ridge',from:'observatory',to:'orchard',unknown:true,description:'A narrow lane descends beyond the skyline; destination unknown.'}],party:[{id:'mara',name:'Mara Venn',color:'#df9b69',roomId:'f-deck',x:.35,y:.55},{id:'ivo',name:'Ivo Quill',color:'#84b5cf',roomId:'f-deck',x:.45,y:.4},{id:'sable',name:'Sable Reed',color:'#b69cd5',roomId:'f-deck',x:.58,y:.55},{id:'tern',name:'Brother Tern',color:'#a8c58d',roomId:'f-deck',x:.68,y:.4}]};
export default CATALOG;
