export const episode = { title: 'Behind the Veil', subtitle: 'The shore remembers', id: 'BTV-01', date: 'Episode 01 · Expedition Day 1', mode: 'Human DM', dm: 'Avery', minutes: 10 };
export const art = { shore: 'assets/shore.jpg', abbey: 'assets/abbey.jpg', hearth: 'assets/hearth.jpg', island: 'assets/island.jpg', counsel: 'assets/counsel.jpg', mara: 'assets/mara.jpg' };
export const opening = 'The signal tower goes dark. Your boat scrapes across the black stones of Saltglass Shore, beneath the ruined Abbey. A towline cracks like a whip. The courier falls beneath a broken spar; beyond him, a supply crate drifts toward the causeway. Above the surf, a patrol’s lantern turns toward the sound.\n\n“Abbey,” the courier gasps. “Ask for Mara.”\n\nYou have your packs, your weapons, and each other. What do you do?';
export const alternate = 'Black stones grind beneath the boat. The tower’s light dies. A snapped towline lashes the water, leaving the courier pinned beneath a spar and a supply crate slipping out to sea. On the causeway, a lantern turns.\n\n“Abbey. Ask for Mara.” His voice barely carries over the surf.\n\nThe patrol has not found you. Where do you put your hands first?';
export const abbeyCue = 'The Abbey rises out of the mist, its broken windows dark against the last light. Beneath a sheltered arch, the courier presses one hand to the stone and catches his breath. From beyond a narrow door comes the soft scrape of a chair.\n\nA woman opens it just wide enough to see you. “You brought him back.” Her eyes pass over each of you. “I’m Mara. Come inside.”';
export const secret = 'The patrol will turn toward the old causeway at the next bell if no further noise draws it closer. Keep this timing behind the screen.';
export const summaryText = 'Maren and Rowan freed the courier. The drifting supply crate was lost. The party learned to seek Mara at the Abbey. A patrol investigated the noise, but its knowledge of the party’s location remains uncertain.';
export const entries = [
  { id:'E01', tag:'SCENE', time:'00:02:00', speaker:'Avery · DM', scene:'Saltglass Shore', text:'The company lands beneath the Abbey. A courier is pinned under a spar. An extra supply crate drifts away. A patrol lantern turns toward the sound.', at:7 },
  { id:'E02', tag:'TRANSCRIPT', time:'00:10:42', speaker:'Avery · DM', scene:'Saltglass Shore', text:'“Abbey,” the courier says. “Ask for Morrow.”', original:true, at:9 },
  { id:'E03', tag:'TRANSCRIPT', time:'00:12:08', speaker:'Maren', scene:'Saltglass Shore', text:'I brace the spar so Rowan can pull the courier free.', at:10 },
  { id:'E04', tag:'TRANSCRIPT', time:'00:12:22', speaker:'Rowan', scene:'Saltglass Shore', text:'I pull him toward the boat, keeping his head above the water.', at:11 },
  { id:'E05', tag:'RESULT', time:'00:13:04', speaker:'Avery · DM', scene:'Saltglass Shore', text:'Rowan’s Athletics: advantage, keep 16 over 7; +3 = 19 against DC 14. The courier is freed. The extra supply crate is lost. No character equipment is removed.', at:12 },
  { id:'E06', tag:'RESULT', time:'00:14:10', speaker:'Avery · DM', scene:'Saltglass Shore', text:'Maren moves 15 feet to the rock shelter. The party remains out of the patrol’s sight. This does not establish what the patrol knows.', at:13 },
  { id:'E07', tag:'IMAGE', time:'00:16:30', speaker:'Raphael', scene:'Saltglass Shore', text:'Saltglass Shore · establishing view at 00:02. The illustration depicts the earlier scene, before the rescue.', image:'shore', at:17 },
  { id:'E08', tag:'SUMMARY', time:'00:20:00', speaker:'Raphael', scene:'Saltglass Shore', text:'Maren and Rowan freed the courier; the extra crate was lost. The courier named an Abbey contact, transcribed as “Morrow” (name unverified). A patrol investigated the noise; its knowledge of the party’s location remains uncertain.', refs:['E02','E03','E04','E05','E06'], at:19 },
  { id:'E09', tag:'CORRECTION', time:'00:21:10', speaker:'Avery · DM', scene:'Saltglass Shore', text:'E02 correction: the courier said “Mara,” not “Morrow.” The original speech recognition remains in the audit trail.', refs:['E02'], at:21 },
  { id:'E10', tag:'SUMMARY', time:'00:21:12', speaker:'Raphael', scene:'Saltglass Shore', text:summaryText, refs:['E03','E04','E05','E06','E09'], replaces:'E08', at:21 },
  { id:'E11', tag:'SESSION', time:'00:22:00', speaker:'Avery · DM', scene:'Saltglass Shore', text:'Break started. Voice capture and summary countdown paused. Next summary in 08:48 of active session time.', at:22 },
  { id:'E12', tag:'SESSION', time:'00:27:00', speaker:'Avery · DM', scene:'Saltglass Shore', text:'Both players ready. Capture resumed; summary countdown continues from 08:48. Fictional time did not advance during the break.', at:23 },
  { id:'E13', tag:'SCENE', time:'00:29:00', speaker:'Avery · DM', scene:'The Drowned Abbey', text:'The company reaches the Abbey with the courier. Mara opens a sheltered door and invites them inside.', at:24 },
  { id:'E14', tag:'GAP', time:'00:30:15', speaker:'Raphael', scene:'The Drowned Abbey', text:'Rowan’s transcription connection dropped for 12 seconds. No words were inferred for this gap.', at:25 },
  { id:'E15', tag:'NOTE', time:'00:30:40', speaker:'Rowan', scene:'The Drowned Abbey', text:'I promised the courier we would hear Mara out before deciding our next move.', at:25 },
  { id:'E16', tag:'IMAGE', time:'00:31:00', speaker:'Raphael', scene:'The Drowned Abbey', text:'The Drowned Abbey · current scene illustration. Architectural decoration is not an additional clue.', image:'abbey', at:25 },
  { id:'E17', tag:'SUMMARY', time:'00:35:48', speaker:'Raphael', scene:'The Drowned Abbey', text:'The company reached the Abbey and met Mara. Rowan promised to hear her out before committing to a plan. A 12-second speech gap remains marked; Rowan supplied the missing promise as a written note. The patrol’s knowledge remains uncertain.', refs:['E13','E14','E15'], at:26 },
  { id:'E18', tag:'SESSION', time:'00:38:00', speaker:'Avery · DM', scene:'The Drowned Abbey', text:'Session ended inside the Abbey. No reward or mission commitment was confirmed. Next session starts with Mara’s briefing.', at:27 },
];
// Panel metadata drives the board, the interactive screens and the print edition.
const panel = (id, act, role, type, title, time, scene, dialogue, action, next) => ({ id, act, role, type, title, time, scene, dialogue, action, next });
export const panels = [
  panel(1,1,'Admin','campaign','Choose the episode','Before play','hearth','“Tonight we cross the Veil.”','Select Behind the Veil and create Episode 01.','Assign the table’s roles.'),
  panel(2,1,'Admin','roles','A place at the table','Before play','hearth','“Avery is our DM. Maren and Rowan are playing.”','Assign DM and player seats; preview their access.','Configure the companion.'),
  panel(3,1,'Admin','settings','Set the companion’s rhythm','Before play','island','“Give us a short recap every ten minutes.”','Choose human DM, capture settings, scene art and the shared chronicle.','Open the session lobby.'),
  panel(4,1,'DM','lobby','The curtain is almost up','00:00:00','hearth','“Everyone ready? Capture is your choice.”','Check roster, consent and microphone indicators.','Players join and ready their characters.'),
  panel(5,1,'Player','join','Your hero. Your voice.','00:00:30','hearth','“Maren is ready. Include my voice in the story record.”','Choose Maren, opt into simulated capture, and mark ready.','The DM opens the shore scene.'),
  panel(6,2,'DM','opening','Give the world a voice','00:02:00','shore','“The signal tower goes dark…”','Read the private passage, adjust its size, and mark it read.','Players see only the observable scene.'),
  panel(7,2,'Player','scene','Landfall at Saltglass','00:02:00','shore','“You have your packs, your weapons, and each other.”','Look over the scene and choose how to respond.','Live conversation enters the chronicle.'),
  panel(8,2,'DM','transcript','The scribe listens','00:10:42','shore','“Abbey. Ask for Mara.”','Watch speaker attribution while continuing to run the table.','Players can follow and correct their words.'),
  panel(9,2,'Player','transcript','Nothing important gets lost','00:10:42','shore','“Did the courier say Morrow?”','Read the tagged transcript; an uncertain name remains unverified.','Maren offers a rescue plan.'),
  panel(10,2,'Player','proposal','A choice, not a script','00:12:08','shore','“I brace the spar so Rowan can pull the courier free.”','Submit the proposed action without deciding its outcome.','The DM makes a ruling.'),
  panel(11,2,'DM','ruling','Let the table decide','00:12:22','shore','“Rowan, roll Athletics with advantage. DC 14.”','Review assistance, request the check and confirm the result.','The tactical view reflects the rescue.'),
  panel(12,3,'DM','tactical','Behind the screen','00:13:04','shore','“Nineteen. You get him clear, but the crate is gone.”','Inspect the sample result, visible actors and private encounter notes.','Maren previews a move toward shelter.'),
  panel(13,3,'Player','tactical','Find a little cover','00:14:10','shore','“I move to those rocks. Fifteen feet.”','Preview and confirm the demonstrated movement.','Private guidance stays private.'),
  panel(14,3,'DM','cue','A quieter delivery','00:15:00','shore','“Make the next passage shorter. Leave room for the players.”','Edit or regenerate the read-aloud draft; keep delivery notes separate.','A player asks Raphael for a nudge.'),
  panel(15,3,'Player','counsel','A whisper from Raphael','00:15:20','shore','“You have already chosen a life over a crate. Find shelter for that life.”','Read private counsel; preview the exact text before sharing.','Scene art arrives without stopping play.'),
  panel(16,3,'DM','image','Set the next frame','00:16:00','shore','“Show the shore as they first saw it.”','Follow an automatic scene image job without buying another request.','Players can view or request an image.'),
  panel(17,3,'Player','image','A picture of that moment','00:16:30','shore','“This is the shore before we freed the courier.”','View the completed image, its timestamp, and earlier-scene label.','The first ten-minute story window closes.'),
  panel(18,4,'DM','summary','The story, distilled','00:20:00','shore','“The rescue is clear. That contact’s name needs checking.”','Review a short evidence-linked recap before publishing.','The recap joins the shared chronicle.'),
  panel(19,4,'Player','summary','Catch up without interrupting','00:20:00','shore','“We saved the courier. We still do not know what the patrol knows.”','Filter the same feed to summaries and inspect its sources.','The DM corrects the misheard name.'),
  panel(20,4,'DM','correction','Make the record right','00:21:10','shore','“Mara. The courier said Mara.”','Correct E02 while preserving the original transcript.','The updated summary points to the correction.'),
  panel(21,4,'Player','corrected','One story, with an audit trail','00:21:12','shore','“Mara at the Abbey. Got it.”','See the correction, superseded summary and revised recap together.','The table takes a break.'),
  panel(22,4,'DM','pause','Intermission','00:22:00','shore','“Five-minute break. Stop the scribe.”','Pause capture and freeze the summary countdown at 08:48.','Players can ready themselves without being recorded.'),
  panel(23,4,'Player','resume','Back around the table','00:27:00','shore','“Ready when everyone else is.”','Mark ready; resume after both players are ready.','The company reaches the Abbey.'),
  panel(24,5,'DM','abbey','A door in the dark','00:29:00','abbey','“You brought him back. I’m Mara. Come inside.”','Read the new scene passage and reveal only the public scene.','A temporary transcription failure is surfaced.'),
  panel(25,5,'Player','failure','A gap, honestly marked','00:30:40','abbey','“I promised we would hear Mara out.”','Reconnect the simulated scribe and add a missing detail as a note.','The DM closes the session.'),
  panel(26,5,'DM','end','That is where we leave them','00:38:00','abbey','“We will start next time with Mara’s briefing.”','Stop capture, review chapters and prepare the complete recap.','Players see recap preparation and completion.'),
  panel(27,5,'Player','complete','An episode becomes a keepsake','00:38:00','abbey','“The whole evening, all in one place.”','Watch recap preparation complete and open the illustrated chronicle.','Read or save the final episode.'),
  panel(28,6,'Player','recap','The shore remembers','After play','abbey','“They came ashore with a choice to make.”','Read chronological chapters, smaller images and the expandable source record.','Return with a useful previously-on reminder.'),
  panel(29,6,'Player','previously','Previously, beyond the Veil…','Next session','abbey','“The courier lives. Mara is waiting. Our promises came with us.”','Review party status, open threads and the next opening.','Compare the same experience in arcade mode.'),
  panel(30,6,'Player','arcade','When Raphael takes the chair','Alternate mode','shore','“The signal tower goes dark. What do you do?”','See automated narration, with no human read-aloud controls.','Return to the storyboard or replay the episode.'),
];
export const acts = ['Before the curtain','Landfall','Choices & consequences','The living record','A door in the dark','Credits & next time'];
export function feedFor(id, { tag = 'ALL', query = '', speaker = 'ALL', time = 'ALL' } = {}) {
  return entries.filter(e => e.at <= id && (tag === 'ALL' || e.tag === tag) && (speaker === 'ALL' || e.speaker === speaker) &&
    (time === 'ALL' || (time === 'early' ? e.time < '00:20:00' : e.time >= '00:20:00')) &&
    `${e.text} ${e.id} ${e.speaker} ${e.scene} ${e.time}`.toLowerCase().includes(query.toLowerCase()));
}
