import {randomUUID} from 'node:crypto';
import {EngineError} from '../../hollow-lantern/engine-client.mjs';
const flags=32768|64,text=content=>({type:10,content}),row=components=>({type:1,components});
const card=components=>({flags,allowedMentions:{parse:[]},components:[{type:17,accent_color:0xd8ac55,components}]});
const safe=(v,n=1800)=>String(v??'').replace(/@/g,'@\u200b').slice(0,n);
const names={fighter:'Fighter · Champion · Human · Soldier',rogue:'Rogue · Thief · High Elf · Criminal',cleric:'Cleric · Life · Human · Acolyte'};
export function createEnrollmentAdapter({enrollment,campaignId,gmUserId,guildId,applicationId,authorize,onCommitted=async()=>{},now=Date.now}={}){
 if(!enrollment?.preview||typeof authorize!=='function'||![campaignId,gmUserId,guildId,applicationId].every(x=>typeof x==='string'&&x))throw new Error('Scoped enrollment configuration required.');
 const controls=new Map(),previews=new Map();let closed=false;const scope=userId=>({campaignId,userId});
 async function access(userId){return !closed&&await authorize(scope(userId));}
 function issue(userId,action,extra={}){for(const [id,c]of controls)if(c.expires<=now())controls.delete(id);while(controls.size>=512)controls.delete(controls.keys().next().value);const id=`hl-enroll:${randomUUID()}`;controls.set(id,{userId,action,...extra,expires:now()+600000});return id;}
 const button=(userId,label,action,extra={},style=2)=>({type:2,style,label,custom_id:issue(userId,action,extra)});
 function entry(userId){return card([text('## Create or import a character'),text('Choose a fixed, validated level-three 2024 build. You can personalize its name and story. Mechanics use the shown blueprint; other builds require additional support.'),row([{type:3,custom_id:issue(userId,'blueprint'),placeholder:'Choose your class and origin',options:Object.entries(names).map(([value,label])=>({value,label}))}]),...(userId===gmUserId?[row([button(userId,'Review enrollment queue','queue')])]:[])]);}
 function previewCard(userId,id,page=0,gmCandidate=null){const review=gmCandidate??previews.get(id);if(!review)throw new EngineError('STALE_CANDIDATE','Reopen your character preview.');const p=review.preview,a=p.actor,s=a.sheet,blocks=[`**${safe(p.name,80)}**\n${safe(names[a.classId])}\n2024 · Level 3 · HP ${a.primaryHealthMaximum} · AC ${a.armorClass}\n${Object.entries(a.scores??{}).map(([k,v])=>`${k}: ${v}`).join(' · ')}\n${safe(p.narrative)}\n${safe(p.resourcePolicy)}`,`**Skills and training**\n${Object.entries(a.skills??{}).map(([k,v])=>`${k}: ${v}`).join(' · ')}\nSaves: ${(a.saveProficiencies??[]).join(', ')}\nLanguages: ${(s.languages??[]).join(', ')}\nTools: ${(s.tools??[]).join(', ')}\nArmor: ${s.armorCalculation??''}\nWeapons: ${s.weaponProficiencies??''}`,`**Features and spells**\n${(s.features??[]).map(f=>`${f.id}: ${f.resolution}`).join('\n')}\n${JSON.stringify(s.spellcasting??{})}`,`**Equipment and resources**\n${p.inventory.items.map(i=>`${i.quantity} × ${i.displayName??i.itemId}${i.equipped?' (equipped)':''}`).join('\n')}\n${p.inventory.currency??0} gold\n${JSON.stringify(a.resources??{})}`];
 const out=card([text('## Supported character review'),text(`Page ${page+1}/4 · ${review.eligible?'Eligible for DM enrollment':'Corrections required'}`),text(safe(blocks[page],3900)),...(review.mismatches?.length?[text(safe(review.mismatches.join('\n'),3900))]:[]),row([button(userId,'Previous','preview',{id,page:(page+3)%4,gm:!!gmCandidate}),button(userId,'Next','preview',{id,page:(page+1)%4,gm:!!gmCandidate}),button(userId,'Back','open')])]);
 if(gmCandidate&&review.eligible)out.components[0].components.push(row([button(userId,'Approve enrollment','approve',{candidateId:id,commandId:randomUUID(),expectedRevision:review.currentRevision},3)]));
 else if(!gmCandidate)out.components[0].components.push(text(review.eligible?'Your candidate is in the private DM queue. The DM must accept before enrollment.':'Correct the approved import and create a fresh preview. Unsupported assertions are never silently discarded.'));
 out.files=[{attachment:Buffer.from(JSON.stringify({preview:p,mismatches:review.mismatches??[]},null,2)),name:'character-review.json'}];return out;}
 async function queue(userId,offset=0){if(userId!==gmUserId)throw new EngineError('ACCESS_DENIED','DM access required.');const items=await enrollment.list(scope(userId)),shown=items.slice(offset,offset+25);return card([text('## Enrollment queue'),text(shown.length?'Review a candidate and its source differences before accepting.':'No current candidates.'),...(shown.length?[row([{type:3,custom_id:issue(userId,'candidate',{ids:shown.map(x=>x.candidateId)}),placeholder:'Choose a character to review',options:shown.map(c=>({value:c.candidateId,label:safe(c.name,70),description:c.eligible?'Eligible supported blueprint':'Corrections required'}))}])]:[]),row([button(userId,'Back','open'),...(offset>0?[button(userId,'Previous page','queue',{offset:Math.max(0,offset-25)})]:[]),...(items.length>offset+25?[button(userId,'Next page','queue',{offset:offset+25})]:[])])]);}
 const matches=i=>typeof i?.customId==='string'&&i.customId.startsWith('hl-enroll:');
 async function openEntry(i){const userId=i.user?.id;if(i.guildId!==guildId||i.applicationId!==applicationId||!await access(userId))throw new EngineError('ACCESS_DENIED','Current campaign access required.');if(!i.deferred&&!i.replied)await i.deferReply({flags:64});return i.editReply(entry(userId));}
 async function handleInteraction(i){if(!matches(i))return false;const t=controls.get(i.customId),userId=i.user?.id;
  if(!t||t.expires<=now()||t.userId!==userId||i.guildId!==guildId||i.applicationId!==applicationId||!await access(userId)){await i.reply({content:'This private enrollment control expired or belongs to someone else. Reopen character setup.',flags:64,allowedMentions:{parse:[]}});return true;}
  try{
   if(t.action==='form'){const imported=t.kind==='approved-import';await i.showModal({custom_id:issue(userId,'submit',{classId:t.classId,kind:t.kind}),title:imported?'Review approved import':'Create supported character',components:[...(!imported?[row([{type:4,custom_id:'name',label:'Character name',style:1,required:true,max_length:80}])]:[]),row([{type:4,custom_id:'narrative',label:'Personal story (optional)',style:2,required:false,max_length:1500}]),row([{type:4,custom_id:'edition',label:'Type 2024 to confirm the rules',style:1,required:true,max_length:4}])]});return true;}
   await i.deferReply({flags:64});let payload;
   if(t.action==='open')payload=entry(userId);
   else if(t.action==='blueprint'){const classId=i.values?.[0];if(!Object.hasOwn(names,classId))throw new EngineError('INVALID_INPUT','Choose a listed blueprint.');payload=card([text(`## ${names[classId]}`),text('The complete mechanical build is fixed and reviewed. Choose guided creation or a previously approved character import.'),row([button(userId,'Create character','form',{classId,kind:'guided'}),button(userId,'Use approved import','form',{classId,kind:'approved-import'}),button(userId,'Back','open')])]);}
   else if(t.action==='submit'){const input={classId:t.classId,sourceKind:t.kind,name:t.kind==='guided'?i.fields.getTextInputValue('name'):undefined,narrative:i.fields.getTextInputValue('narrative'),edition:i.fields.getTextInputValue('edition')};if(t.kind==='approved-import'){const current=await enrollment.approvedImport(scope(userId));if(!current)throw new EngineError('STALE_IMPORT','No approved import exists for your account. Use the existing import desk first.');input.expectedImportRevision=current.revision;}const result=await enrollment.preview(scope(userId),input);for(const [id,p]of previews)if(p.expiresAt<=now())previews.delete(id);if(previews.size>=100)previews.delete(previews.keys().next().value);previews.set(result.candidateId,result);payload=previewCard(userId,result.candidateId);}
   else if(t.action==='queue')payload=await queue(userId,t.offset??0);
   else if(t.action==='candidate'||t.action==='preview'&&t.gm){if(userId!==gmUserId)throw new EngineError('ACCESS_DENIED','DM access required.');const id=t.action==='candidate'?i.values?.[0]:t.id;if(t.ids&&!t.ids.includes(id))throw new EngineError('INVALID_INPUT','Choose a listed candidate.');const candidate=(await enrollment.list(scope(userId))).find(c=>c.candidateId===id);if(!candidate)throw new EngineError('STALE_CANDIDATE','Candidate expired.');candidate.currentRevision=await enrollment.currentRevision(scope(userId));payload=previewCard(userId,id,t.page??0,candidate);}
   else if(t.action==='preview')payload=previewCard(userId,t.id,t.page);
   else if(t.action==='approve'){if(userId!==gmUserId)throw new EngineError('ACCESS_DENIED','DM access required.');const receipt=await enrollment.approve(scope(userId),t);try{if(!receipt.replayed)await onCommitted({scope:scope(userId),receipt});}catch{}payload=card([text('## Character enrolled'),text(`The supported character is ready. Revision ${receipt.revision}${receipt.replayed?' · Original result recovered':''}.`)]);}
   if(!await access(userId))throw new EngineError('ACCESS_DENIED','Access changed.');await i.editReply(payload??entry(userId));
  }catch(error){const payload=card([text('## Enrollment needs attention'),text(error instanceof EngineError?safe(error.message,1200):'The result could not be confirmed. Reopen the review or recover the original approval.')]);if(t.action==='approve')payload.components[0].components.push(row([button(userId,'Recover original approval','approve',{candidateId:t.candidateId,commandId:t.commandId,expectedRevision:t.expectedRevision})]));if(i.deferred||i.replied)await i.editReply(payload);else await i.reply(payload);}
  return true;
 }
 return Object.freeze({matches,handleInteraction,openEntry,entryButton({userId}={}){return closed||!userId?null:button(userId,'Character setup','open');},close(){closed=true;controls.clear();previews.clear();}});
}
