import test from 'node:test';
import assert from 'node:assert/strict';
import {createEnrollmentAdapter} from './enrollment.mjs';
const scope={userId:'123'},view={candidateId:'candidate',eligible:true,expiresAt:9999999999999,mismatches:[],preview:{name:'Mara',narrative:'Coastal scout',actor:{classId:'fighter',primaryHealthMaximum:31,armorClass:19,scores:{strength:16},sheet:{features:[{id:'second-wind',resolution:'automated'}]}},inventory:{items:[]}}};
function setup(){let allowed=true,attempt=0,previewInput,approvedInputs=[];const enrollment={preview:async(s,input)=>{previewInput={s,input};return view;},approvedImport:async()=>({revision:7}),list:async()=>[{...view,candidateId:'candidate'}],currentRevision:async()=>4,approve:async(s,input)=>{approvedInputs.push({...input});if(attempt++===0)throw new Error('Lost acknowledgement');return {revision:5,replayed:true};}};const adapter=createEnrollmentAdapter({enrollment,campaignId:'c',gmUserId:'999',guildId:'g',applicationId:'a',authorize:async()=>allowed});return {adapter,enrollment,approvedInputs,get previewInput(){return previewInput;},revoke(){allowed=false;}};}
function interaction(customId,userId='123',values=[]){return {customId,user:{id:userId},guildId:'g',applicationId:'a',values,async deferReply(){this.deferred=true;},async editReply(p){this.output=p;},async reply(p){this.output=p;this.replied=true;},async showModal(p){this.modal=p;},fields:{getTextInputValue(id){return {name:'Mara',narrative:'Coastal scout',edition:'2024'}[id];}}};}
function components(p){return p.components.flatMap(c=>c.components??[]).flatMap(c=>c.components??[c]);}
function button(p,label){return components(p).find(c=>c.label===label);}
async function open(f,user='123'){const i=interaction(f.adapter.entryButton({userId:user}).custom_id,user);await f.adapter.handleInteraction(i);return i.output;}
test('grouped blueprint selection opens manual modal and only sends allowed choices',async()=>{const f=setup(),panel=await open(f),select=components(panel).find(c=>c.type===3);assert.equal(select.options.length,3);let i=interaction(select.custom_id,'123',['fighter']);await f.adapter.handleInteraction(i);i=interaction(button(i.output,'Create character').custom_id);await f.adapter.handleInteraction(i);assert.equal(i.modal.components.length,3);i=interaction(i.modal.custom_id);await f.adapter.handleInteraction(i);assert.deepEqual(f.previewInput,{s:{campaignId:'c',userId:'123'},input:{classId:'fighter',sourceKind:'guided',name:'Mara',narrative:'Coastal scout',edition:'2024'}});assert.match(JSON.stringify(i.output),/Eligible for DM enrollment/);assert.equal(i.output.files[0].name,'character-review.json');});
test('copied control and revoked membership cannot submit previews',async()=>{const f=setup(),id=f.adapter.entryButton(scope).custom_id;let i=interaction(id,'124');await f.adapter.handleInteraction(i);assert.match(i.output.content,/belongs to someone else/);assert.equal(f.previewInput,undefined);f.revoke();i=interaction(id);await f.adapter.handleInteraction(i);assert.equal(f.previewInput,undefined);});
test('approved import obtains revision from authenticated server record',async()=>{const f=setup(),panel=await open(f);let i=interaction(components(panel).find(c=>c.type===3).custom_id,'123',['fighter']);await f.adapter.handleInteraction(i);i=interaction(button(i.output,'Use approved import').custom_id);await f.adapter.handleInteraction(i);assert.equal(i.modal.components.length,2);i=interaction(i.modal.custom_id);await f.adapter.handleInteraction(i);assert.equal(f.previewInput.input.expectedImportRevision,7);assert.equal(f.previewInput.input.name,undefined);});
test('GM queue approval recovery repeats exact command identity and revision',async()=>{const f=setup(),panel=await open(f,'999');let i=interaction(button(panel,'Review enrollment queue').custom_id,'999');await f.adapter.handleInteraction(i);i=interaction(components(i.output).find(c=>c.type===3).custom_id,'999',['candidate']);await f.adapter.handleInteraction(i);i=interaction(button(i.output,'Approve enrollment').custom_id,'999');await f.adapter.handleInteraction(i);i=interaction(button(i.output,'Recover original approval').custom_id,'999');await f.adapter.handleInteraction(i);assert.equal(f.approvedInputs.length,2);assert.equal(f.approvedInputs[0].commandId,f.approvedInputs[1].commandId);assert.equal(f.approvedInputs[0].expectedRevision,4);assert.equal(f.approvedInputs[1].expectedRevision,4);assert.match(JSON.stringify(i.output),/Original result recovered/);});

test('candidate mismatches are visible and cannot offer an approval button',async()=>{const f=setup();f.enrollment.list=async()=>[{...view,eligible:false,mismatches:['armorClass: requires 19; source reports 99.']}];const panel=await open(f,'999');let i=interaction(button(panel,'Review enrollment queue').custom_id,'999');await f.adapter.handleInteraction(i);i=interaction(components(i.output).find(c=>c.type===3).custom_id,'999',['candidate']);await f.adapter.handleInteraction(i);assert.equal(button(i.output,'Approve enrollment'),undefined);assert.match(JSON.stringify(i.output.components),/source reports 99/);});
test('forged blueprint and wrong Discord application never open a creation modal',async()=>{const f=setup(),panel=await open(f),select=components(panel).find(c=>c.type===3);let i=interaction(select.custom_id,'123',['wizard']);await f.adapter.handleInteraction(i);assert.equal(i.modal,undefined);assert.match(JSON.stringify(i.output),/listed blueprint/);i=interaction(select.custom_id,'123',['fighter']);i.applicationId='other';await f.adapter.handleInteraction(i);assert.match(i.output.content,/private enrollment control/);});
