import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createCharacterThreadDelivery} from './character-thread-delivery.mjs';
const ids={parent:'111111111111111111',thread:'222222222222222222',owner:'333333333333333333',bot:'444444444444444444',guild:'555555555555555555',dm:'666666666666666666',foreign:'777777777777777777'};
function fixture(){
 const db=new DatabaseSync(':memory:'),sent=[],members=new Map([[ids.bot,{id:ids.bot}]]),config={campaignId:'saltglass',channelId:ids.parent,guildId:ids.guild,dmIds:[ids.dm]};
 const thread={id:ids.thread,parentId:ids.parent,guildId:ids.guild,ownerId:ids.bot,type:12,invitable:false,archived:false,members:{add:async id=>{sent.push(['member',id]);members.set(id,{id});},fetch:async options=>options?members.get(options.member):members},send:async body=>{sent.push(['thread',body]);return{id:'888888888888888888'};},setArchived:async archived=>{thread.archived=archived;}};
 const parent={id:ids.parent,guildId:ids.guild,type:0,threads:{create:async options=>{sent.push(['create',options]);return thread;}},send:async body=>{sent.push(['parent',body]);return{id:'999999999999999999'};}};
 const client={user:{id:ids.bot},channels:{fetch:async id=>id===ids.parent?parent:thread}};
 const make=()=>createCharacterThreadDelivery({client,config,store:{db}}),scope={campaign:'saltglass',owner:ids.owner},character={name:'Mara',revision:4};
 return {db,sent,members,config,thread,parent,client,make,scope,character};
}
test('approved owner reuses one private thread across name/revision changes',async()=>{const f=fixture();try{const d=f.make(),a=await d.ensure(f.scope,f.character),b=await d.ensure(f.scope,{name:'New name',revision:5});assert.equal(a.reused,false);assert.equal(b.reused,true);assert.equal(a.thread_id,b.thread_id);assert.equal(f.sent.filter(x=>x[0]==='create').length,1);assert.equal(f.sent.filter(x=>x[0]==='parent').length,1);assert.ok(f.members.has(ids.owner)&&f.members.has(ids.dm));assert.equal(f.config.characterThreadIds.has(ids.thread),true);assert.deepEqual(f.sent.find(x=>x[0]==='thread')[1].allowed_mentions,{parse:[]});}finally{f.db.close();}});
test('concurrent requests share a single creation',async()=>{const f=fixture();try{const d=f.make();await Promise.all(Array.from({length:10},()=>d.ensure(f.scope,f.character)));assert.equal(f.sent.filter(x=>x[0]==='create').length,1);assert.equal(f.sent.filter(x=>x[0]==='thread').length,1);}finally{f.db.close();}});
test('campaign mismatch is rejected before external requests',async()=>{const f=fixture();try{await assert.rejects(f.make().ensure({...f.scope,campaign:'another'},f.character),/matching campaign/);assert.equal(f.sent.length,0);}finally{f.db.close();}});
test('saved thread privacy drift is rejected rather than recreated',async()=>{const f=fixture();try{const d=f.make();await d.ensure(f.scope,f.character);f.thread.type=11;await assert.rejects(d.ensure(f.scope,f.character),/not privately bound/);assert.equal(f.sent.filter(x=>x[0]==='create').length,1);}finally{f.db.close();}});
test('unexpected members stop delivery without removing anybody',async()=>{const f=fixture();try{f.members.set(ids.foreign,{id:ids.foreign});await assert.rejects(f.make().ensure(f.scope,f.character),/Unexpected members/);assert.ok(f.members.has(ids.foreign));assert.equal(f.sent.filter(x=>x[0]==='thread').length,0);assert.equal(f.db.prepare('SELECT thread_id FROM character_threads').get().thread_id,ids.thread);}finally{f.db.close();}});
test('membership failure preserves remote ID and retries same thread after restart',async()=>{const f=fixture();try{const add=f.thread.members.add;f.thread.members.add=async()=>{throw Error('offline');};await assert.rejects(f.make().ensure(f.scope,f.character),/offline/);assert.equal(f.db.prepare('SELECT thread_id FROM character_threads').get().thread_id,ids.thread);f.thread.members.add=add;const result=await f.make().ensure(f.scope,f.character);assert.equal(result.reused,true);assert.equal(f.sent.filter(x=>x[0]==='create').length,1);assert.equal(f.sent.filter(x=>x[0]==='thread').length,1);}finally{f.db.close();}});
test('ambiguous creation remains reserved and is never automatically repeated',async()=>{const f=fixture();try{let creates=0;f.parent.threads.create=async()=>{creates++;throw Error('response lost');};await assert.rejects(f.make().ensure(f.scope,f.character),/response lost/);await assert.rejects(f.make().ensure(f.scope,f.character),/reconciliation/);assert.equal(creates,1);}finally{f.db.close();}});
test('uncertain welcome is not resent on recovery and is reported for review',async()=>{const f=fixture();try{let sends=0;f.thread.send=async()=>{sends++;throw Error('response lost');};await assert.rejects(f.make().ensure(f.scope,f.character),/response lost/);const result=await f.make().ensure(f.scope,f.character);assert.equal(result.deliveryNeedsReview,true);assert.equal(sends,1);assert.equal(f.sent.filter(x=>x[0]==='create').length,1);}finally{f.db.close();}});
test('two service instances cannot race-create a private thread',async()=>{const f=fixture();try{let resume;f.parent.threads.create=async options=>{f.sent.push(['create',options]);await new Promise(r=>resume=r);return f.thread;};const first=f.make().ensure(f.scope,f.character);await new Promise(r=>setImmediate(r));await assert.rejects(f.make().ensure(f.scope,f.character),/reconciliation/);resume();await first;assert.equal(f.sent.filter(x=>x[0]==='create').length,1);}finally{f.db.close();}});
